2024-05-09 09:19:06,207 - util.py[DEBUG]: Cloud-init v. 22.2.2 running 'init' at Thu, 09 May 2024 09:19:06 +0000. Up 5.94 seconds.
2024-05-09 09:19:06,208 - main.py[DEBUG]: No kernel command line url found.
2024-05-09 09:19:06,208 - main.py[DEBUG]: Closing stdin.
2024-05-09 09:19:06,209 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud (recursive=False)
2024-05-09 09:19:06,210 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud (recursive=True)
2024-05-09 09:19:06,238 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/scripts (recursive=False)
2024-05-09 09:19:06,240 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/scripts (recursive=True)
2024-05-09 09:19:06,244 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/scripts/per-instance (recursive=False)
2024-05-09 09:19:06,252 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/scripts (recursive=True)
2024-05-09 09:19:06,259 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/scripts/per-once (recursive=False)
2024-05-09 09:19:06,260 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/scripts (recursive=True)
2024-05-09 09:19:06,279 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/scripts/per-boot (recursive=False)
2024-05-09 09:19:06,280 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/scripts (recursive=True)
2024-05-09 09:19:06,312 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/scripts/vendor (recursive=False)
2024-05-09 09:19:06,314 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud (recursive=True)
2024-05-09 09:19:06,343 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/seed (recursive=False)
2024-05-09 09:19:06,344 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud (recursive=True)
2024-05-09 09:19:06,375 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances (recursive=False)
2024-05-09 09:19:06,376 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud (recursive=True)
2024-05-09 09:19:06,407 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/handlers (recursive=False)
2024-05-09 09:19:06,408 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud (recursive=True)
2024-05-09 09:19:06,454 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/sem (recursive=False)
2024-05-09 09:19:06,455 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/data (recursive=False)
2024-05-09 09:19:06,455 - util.py[DEBUG]: Restoring selinux mode for /run/cloud-init (recursive=True)
2024-05-09 09:19:06,457 - util.py[DEBUG]: Restoring selinux mode for /run/cloud-init/sem (recursive=False)
2024-05-09 09:19:06,458 - util.py[DEBUG]: Writing to /var/log/cloud-init.log - ab: [640] 0 bytes
2024-05-09 09:19:06,460 - util.py[DEBUG]: Restoring selinux mode for /var/log/cloud-init.log (recursive=False)
2024-05-09 09:19:06,461 - util.py[DEBUG]: Restoring selinux mode for /var/log/cloud-init.log (recursive=False)
2024-05-09 09:19:06,462 - util.py[DEBUG]: Changing the ownership of /var/log/cloud-init.log to 0:4
2024-05-09 09:19:06,462 - util.py[DEBUG]: Writing to /var/lib/cloud/data/python-version - wb: [644] 3 bytes
2024-05-09 09:19:06,463 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/data/python-version (recursive=False)
2024-05-09 09:19:06,464 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/data/python-version (recursive=False)
2024-05-09 09:19:06,465 - subp.py[DEBUG]: Running command ['ip', '--json', 'addr'] with allowed return codes [0] (shell=False, capture=True)
2024-05-09 09:19:06,483 - subp.py[DEBUG]: Running command ['ip', '-o', 'route', 'list'] with allowed return codes [0] (shell=False, capture=True)
2024-05-09 09:19:06,492 - subp.py[DEBUG]: Running command ['ip', '--oneline', '-6', 'route', 'list', 'table', 'all'] with allowed return codes [0, 1] (shell=False, capture=True)
2024-05-09 09:19:06,503 - handlers.py[DEBUG]: start: init-network/check-cache: attempting to read from cache [trust]
2024-05-09 09:19:06,504 - util.py[DEBUG]: Reading from /var/lib/cloud/instance/obj.pkl (quiet=False)
2024-05-09 09:19:06,504 - stages.py[DEBUG]: no cache found
2024-05-09 09:19:06,504 - handlers.py[DEBUG]: finish: init-network/check-cache: SUCCESS: no cache found
2024-05-09 09:19:06,504 - util.py[DEBUG]: Attempting to remove /var/lib/cloud/instance
2024-05-09 09:19:06,558 - stages.py[DEBUG]: Using distro class <class 'cloudinit.distros.amazon.Distro'>
2024-05-09 09:19:06,559 - __init__.py[DEBUG]: Looking for data source in: ['Ec2', 'None'], via packages ['', 'cloudinit.sources'] that matches dependencies ['FILESYSTEM', 'NETWORK']
2024-05-09 09:19:06,605 - __init__.py[DEBUG]: Searching for network data source in: ['DataSourceEc2', 'DataSourceNone']
2024-05-09 09:19:06,606 - handlers.py[DEBUG]: start: init-network/search-Ec2: searching for network data from DataSourceEc2
2024-05-09 09:19:06,606 - __init__.py[DEBUG]: Seeing if we can get any data from <class 'cloudinit.sources.DataSourceEc2.DataSourceEc2'>
2024-05-09 09:19:06,606 - __init__.py[DEBUG]: Update datasource metadata and network config due to events: boot-new-instance
2024-05-09 09:19:06,606 - util.py[DEBUG]: Reading from /sys/hypervisor/uuid (quiet=False)
2024-05-09 09:19:06,606 - dmi.py[DEBUG]: querying dmi data /sys/class/dmi/id/product_uuid
2024-05-09 09:19:06,606 - dmi.py[DEBUG]: querying dmi data /sys/class/dmi/id/product_serial
2024-05-09 09:19:06,606 - dmi.py[DEBUG]: querying dmi data /sys/class/dmi/id/chassis_asset_tag
2024-05-09 09:19:06,606 - dmi.py[DEBUG]: querying dmi data /sys/class/dmi/id/sys_vendor
2024-05-09 09:19:06,607 - DataSourceEc2.py[DEBUG]: strict_mode: warn, cloud_name=aws cloud_platform=ec2
2024-05-09 09:19:06,607 - util.py[DEBUG]: Skipping DNS checks of IP address 169.254.169.254
2024-05-09 09:19:06,607 - util.py[DEBUG]: Resolving URL: http://169.254.169.254:80 took 0.000 seconds
2024-05-09 09:19:06,607 - util.py[DEBUG]: Skipping DNS checks of IP address fd00:ec2::254
2024-05-09 09:19:06,607 - util.py[DEBUG]: Resolving URL: http://[fd00:ec2::254]:80 took 0.000 seconds
2024-05-09 09:19:06,607 - DataSourceEc2.py[DEBUG]: Fetching Ec2 IMDSv2 API Token
2024-05-09 09:19:06,608 - url_helper.py[DEBUG]: [0/1] open 'http://169.254.169.254:80/latest/api/token' with {'url': 'http://169.254.169.254:80/latest/api/token', 'allow_redirects': True, 'method': 'PUT', 'timeout': 50.0, 'headers': {'User-Agent': 'Cloud-Init/22.2.2', 'X-aws-ec2-metadata-token-ttl-seconds': 'REDACTED'}} configuration
2024-05-09 09:19:06,623 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/latest/api/token (200, 56b) after 1 attempts
2024-05-09 09:19:06,624 - DataSourceEc2.py[DEBUG]: Using metadata source: 'http://169.254.169.254:80'
2024-05-09 09:19:06,624 - url_helper.py[DEBUG]: [0/1] open 'http://169.254.169.254:80/2021-03-23/meta-data/instance-id' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/instance-id', 'allow_redirects': True, 'method': 'GET', 'headers': {'User-Agent': 'Cloud-Init/22.2.2', 'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-05-09 09:19:06,632 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/instance-id (200, 19b) after 1 attempts
2024-05-09 09:19:06,633 - DataSourceEc2.py[DEBUG]: Found preferred metadata version 2021-03-23
2024-05-09 09:19:06,633 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/user-data' with {'url': 'http://169.254.169.254:80/2021-03-23/user-data', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-05-09 09:19:06,636 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/user-data (200, 2533b) after 1 attempts
2024-05-09 09:19:06,636 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-05-09 09:19:06,638 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/ (200, 305b) after 1 attempts
2024-05-09 09:19:06,639 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/block-device-mapping/' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/block-device-mapping/', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-05-09 09:19:06,642 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/block-device-mapping/ (200, 8b) after 1 attempts
2024-05-09 09:19:06,643 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/block-device-mapping/ami' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/block-device-mapping/ami', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-05-09 09:19:06,653 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/block-device-mapping/ami (200, 4b) after 1 attempts
2024-05-09 09:19:06,653 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/block-device-mapping/root' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/block-device-mapping/root', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-05-09 09:19:06,656 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/block-device-mapping/root (200, 9b) after 1 attempts
2024-05-09 09:19:06,656 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/events/' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/events/', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-05-09 09:19:06,663 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/events/ (200, 12b) after 1 attempts
2024-05-09 09:19:06,663 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/events/maintenance/' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/events/maintenance/', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-05-09 09:19:06,666 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/events/maintenance/ (200, 17b) after 1 attempts
2024-05-09 09:19:06,666 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/events/maintenance/history' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/events/maintenance/history', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-05-09 09:19:06,683 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/events/maintenance/history (200, 2b) after 1 attempts
2024-05-09 09:19:06,684 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/events/maintenance/scheduled' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/events/maintenance/scheduled', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-05-09 09:19:06,687 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/events/maintenance/scheduled (200, 2b) after 1 attempts
2024-05-09 09:19:06,687 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/iam/' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/iam/', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-05-09 09:19:06,693 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/iam/ (200, 26b) after 1 attempts
2024-05-09 09:19:06,693 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/iam/info' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/iam/info', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-05-09 09:19:06,696 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/iam/info (200, 216b) after 1 attempts
2024-05-09 09:19:06,696 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/identity-credentials/' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/identity-credentials/', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-05-09 09:19:06,701 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/identity-credentials/ (200, 4b) after 1 attempts
2024-05-09 09:19:06,702 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/identity-credentials/ec2/' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/identity-credentials/ec2/', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-05-09 09:19:06,704 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/identity-credentials/ec2/ (200, 26b) after 1 attempts
2024-05-09 09:19:06,705 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/identity-credentials/ec2/info' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/identity-credentials/ec2/info', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-05-09 09:19:06,707 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/identity-credentials/ec2/info (200, 98b) after 1 attempts
2024-05-09 09:19:06,708 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/metrics/' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/metrics/', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-05-09 09:19:06,713 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/metrics/ (200, 7b) after 1 attempts
2024-05-09 09:19:06,713 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/metrics/vhostmd' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/metrics/vhostmd', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-05-09 09:19:06,718 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/metrics/vhostmd (200, 38b) after 1 attempts
2024-05-09 09:19:06,718 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-05-09 09:19:06,720 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/ (200, 11b) after 1 attempts
2024-05-09 09:19:06,721 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-05-09 09:19:06,733 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/ (200, 5b) after 1 attempts
2024-05-09 09:19:06,733 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-05-09 09:19:06,736 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/ (200, 18b) after 1 attempts
2024-05-09 09:19:06,737 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/06:0c:43:f7:86:47/' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/06:0c:43:f7:86:47/', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-05-09 09:19:06,743 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/06:0c:43:f7:86:47/ (200, 230b) after 1 attempts
2024-05-09 09:19:06,743 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/06:0c:43:f7:86:47/ipv4-associations/' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/06:0c:43:f7:86:47/ipv4-associations/', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-05-09 09:19:06,747 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/06:0c:43:f7:86:47/ipv4-associations/ (200, 12b) after 1 attempts
2024-05-09 09:19:06,747 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/06:0c:43:f7:86:47/ipv4-associations/13.55.216.35' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/06:0c:43:f7:86:47/ipv4-associations/13.55.216.35', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-05-09 09:19:06,753 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/06:0c:43:f7:86:47/ipv4-associations/13.55.216.35 (200, 12b) after 1 attempts
2024-05-09 09:19:06,753 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/06:0c:43:f7:86:47/device-number' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/06:0c:43:f7:86:47/device-number', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-05-09 09:19:06,756 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/06:0c:43:f7:86:47/device-number (200, 1b) after 1 attempts
2024-05-09 09:19:06,756 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/06:0c:43:f7:86:47/interface-id' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/06:0c:43:f7:86:47/interface-id', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-05-09 09:19:06,763 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/06:0c:43:f7:86:47/interface-id (200, 21b) after 1 attempts
2024-05-09 09:19:06,763 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/06:0c:43:f7:86:47/local-hostname' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/06:0c:43:f7:86:47/local-hostname', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-05-09 09:19:06,766 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/06:0c:43:f7:86:47/local-hostname (200, 47b) after 1 attempts
2024-05-09 09:19:06,766 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/06:0c:43:f7:86:47/local-ipv4s' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/06:0c:43:f7:86:47/local-ipv4s', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-05-09 09:19:06,774 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/06:0c:43:f7:86:47/local-ipv4s (200, 12b) after 1 attempts
2024-05-09 09:19:06,774 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/06:0c:43:f7:86:47/mac' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/06:0c:43:f7:86:47/mac', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-05-09 09:19:06,777 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/06:0c:43:f7:86:47/mac (200, 17b) after 1 attempts
2024-05-09 09:19:06,777 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/06:0c:43:f7:86:47/owner-id' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/06:0c:43:f7:86:47/owner-id', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-05-09 09:19:06,779 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/06:0c:43:f7:86:47/owner-id (200, 12b) after 1 attempts
2024-05-09 09:19:06,779 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/06:0c:43:f7:86:47/public-hostname' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/06:0c:43:f7:86:47/public-hostname', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-05-09 09:19:06,792 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/06:0c:43:f7:86:47/public-hostname (200, 53b) after 1 attempts
2024-05-09 09:19:06,793 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/06:0c:43:f7:86:47/public-ipv4s' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/06:0c:43:f7:86:47/public-ipv4s', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-05-09 09:19:06,796 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/06:0c:43:f7:86:47/public-ipv4s (200, 12b) after 1 attempts
2024-05-09 09:19:06,796 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/06:0c:43:f7:86:47/security-group-ids' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/06:0c:43:f7:86:47/security-group-ids', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-05-09 09:19:06,805 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/06:0c:43:f7:86:47/security-group-ids (200, 20b) after 1 attempts
2024-05-09 09:19:06,805 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/06:0c:43:f7:86:47/security-groups' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/06:0c:43:f7:86:47/security-groups', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-05-09 09:19:06,813 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/06:0c:43:f7:86:47/security-groups (200, 56b) after 1 attempts
2024-05-09 09:19:06,813 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/06:0c:43:f7:86:47/subnet-id' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/06:0c:43:f7:86:47/subnet-id', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-05-09 09:19:06,816 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/06:0c:43:f7:86:47/subnet-id (200, 24b) after 1 attempts
2024-05-09 09:19:06,816 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/06:0c:43:f7:86:47/subnet-ipv4-cidr-block' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/06:0c:43:f7:86:47/subnet-ipv4-cidr-block', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-05-09 09:19:06,819 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/06:0c:43:f7:86:47/subnet-ipv4-cidr-block (200, 14b) after 1 attempts
2024-05-09 09:19:06,819 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/06:0c:43:f7:86:47/vpc-id' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/06:0c:43:f7:86:47/vpc-id', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-05-09 09:19:06,822 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/06:0c:43:f7:86:47/vpc-id (200, 21b) after 1 attempts
2024-05-09 09:19:06,823 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/06:0c:43:f7:86:47/vpc-ipv4-cidr-block' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/06:0c:43:f7:86:47/vpc-ipv4-cidr-block', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-05-09 09:19:06,835 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/06:0c:43:f7:86:47/vpc-ipv4-cidr-block (200, 13b) after 1 attempts
2024-05-09 09:19:06,836 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/06:0c:43:f7:86:47/vpc-ipv4-cidr-blocks' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/06:0c:43:f7:86:47/vpc-ipv4-cidr-blocks', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-05-09 09:19:06,840 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/06:0c:43:f7:86:47/vpc-ipv4-cidr-blocks (200, 13b) after 1 attempts
2024-05-09 09:19:06,840 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/placement/' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/placement/', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-05-09 09:19:06,853 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/placement/ (200, 45b) after 1 attempts
2024-05-09 09:19:06,853 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/placement/availability-zone' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/placement/availability-zone', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-05-09 09:19:06,856 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/placement/availability-zone (200, 15b) after 1 attempts
2024-05-09 09:19:06,857 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/placement/availability-zone-id' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/placement/availability-zone-id', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-05-09 09:19:06,863 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/placement/availability-zone-id (200, 9b) after 1 attempts
2024-05-09 09:19:06,863 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/placement/region' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/placement/region', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-05-09 09:19:06,867 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/placement/region (200, 14b) after 1 attempts
2024-05-09 09:19:06,868 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/services/' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/services/', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-05-09 09:19:06,870 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/services/ (200, 16b) after 1 attempts
2024-05-09 09:19:06,870 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/services/domain' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/services/domain', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-05-09 09:19:06,873 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/services/domain (200, 13b) after 1 attempts
2024-05-09 09:19:06,873 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/services/partition' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/services/partition', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-05-09 09:19:06,883 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/services/partition (200, 3b) after 1 attempts
2024-05-09 09:19:06,883 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/ami-id' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/ami-id', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-05-09 09:19:06,885 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/ami-id (200, 21b) after 1 attempts
2024-05-09 09:19:06,886 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/ami-launch-index' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/ami-launch-index', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-05-09 09:19:06,888 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/ami-launch-index (200, 1b) after 1 attempts
2024-05-09 09:19:06,888 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/ami-manifest-path' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/ami-manifest-path', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-05-09 09:19:06,903 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/ami-manifest-path (200, 9b) after 1 attempts
2024-05-09 09:19:06,903 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/hostname' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/hostname', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-05-09 09:19:06,906 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/hostname (200, 47b) after 1 attempts
2024-05-09 09:19:06,906 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/instance-action' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/instance-action', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-05-09 09:19:06,912 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/instance-action (200, 4b) after 1 attempts
2024-05-09 09:19:06,913 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/instance-id' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/instance-id', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-05-09 09:19:06,915 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/instance-id (200, 19b) after 1 attempts
2024-05-09 09:19:06,916 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/instance-life-cycle' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/instance-life-cycle', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-05-09 09:19:06,920 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/instance-life-cycle (200, 9b) after 1 attempts
2024-05-09 09:19:06,920 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/instance-type' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/instance-type', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-05-09 09:19:06,934 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/instance-type (200, 8b) after 1 attempts
2024-05-09 09:19:06,934 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/local-hostname' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/local-hostname', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-05-09 09:19:06,941 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/local-hostname (200, 47b) after 1 attempts
2024-05-09 09:19:06,941 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/local-ipv4' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/local-ipv4', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-05-09 09:19:06,953 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/local-ipv4 (200, 12b) after 1 attempts
2024-05-09 09:19:06,954 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/mac' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/mac', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-05-09 09:19:06,957 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/mac (200, 17b) after 1 attempts
2024-05-09 09:19:06,957 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/profile' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/profile', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-05-09 09:19:06,962 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/profile (200, 11b) after 1 attempts
2024-05-09 09:19:06,963 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/public-hostname' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/public-hostname', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-05-09 09:19:06,973 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/public-hostname (200, 53b) after 1 attempts
2024-05-09 09:19:06,973 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/public-ipv4' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/public-ipv4', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-05-09 09:19:06,983 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/public-ipv4 (200, 12b) after 1 attempts
2024-05-09 09:19:06,983 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/reservation-id' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/reservation-id', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-05-09 09:19:06,988 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/reservation-id (200, 19b) after 1 attempts
2024-05-09 09:19:06,988 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/security-groups' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/security-groups', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-05-09 09:19:07,003 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/security-groups (200, 56b) after 1 attempts
2024-05-09 09:19:07,003 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/dynamic/instance-identity' with {'url': 'http://169.254.169.254:80/2021-03-23/dynamic/instance-identity', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-05-09 09:19:07,009 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/dynamic/instance-identity (200, 32b) after 1 attempts
2024-05-09 09:19:07,009 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/dynamic/instance-identity/document' with {'url': 'http://169.254.169.254:80/2021-03-23/dynamic/instance-identity/document', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-05-09 09:19:07,023 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/dynamic/instance-identity/document (200, 486b) after 1 attempts
2024-05-09 09:19:07,024 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/dynamic/instance-identity/pkcs7' with {'url': 'http://169.254.169.254:80/2021-03-23/dynamic/instance-identity/pkcs7', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-05-09 09:19:07,027 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/dynamic/instance-identity/pkcs7 (200, 1187b) after 1 attempts
2024-05-09 09:19:07,027 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/dynamic/instance-identity/rsa2048' with {'url': 'http://169.254.169.254:80/2021-03-23/dynamic/instance-identity/rsa2048', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-05-09 09:19:07,033 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/dynamic/instance-identity/rsa2048 (200, 1503b) after 1 attempts
2024-05-09 09:19:07,033 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/dynamic/instance-identity/signature' with {'url': 'http://169.254.169.254:80/2021-03-23/dynamic/instance-identity/signature', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-05-09 09:19:07,036 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/dynamic/instance-identity/signature (200, 174b) after 1 attempts
2024-05-09 09:19:07,036 - util.py[DEBUG]: Crawl of metadata service took 0.429 seconds
2024-05-09 09:19:07,040 - util.py[DEBUG]: Writing to /run/cloud-init/cloud-id-aws - wb: [644] 4 bytes
2024-05-09 09:19:07,041 - util.py[DEBUG]: Restoring selinux mode for /run/cloud-init/cloud-id-aws (recursive=False)
2024-05-09 09:19:07,042 - util.py[DEBUG]: Restoring selinux mode for /run/cloud-init/cloud-id-aws (recursive=False)
2024-05-09 09:19:07,042 - util.py[DEBUG]: Creating symbolic link from '/run/cloud-init/cloud-id' => '/run/cloud-init/cloud-id-aws'
2024-05-09 09:19:07,043 - atomic_helper.py[DEBUG]: Atomically writing to file /run/cloud-init/instance-data-sensitive.json (via temporary file /run/cloud-init/tmps9n2y6ap) - w: [600] 12105 bytes/chars
2024-05-09 09:19:07,045 - atomic_helper.py[DEBUG]: Atomically writing to file /run/cloud-init/instance-data.json (via temporary file /run/cloud-init/tmpk4tm6juy) - w: [644] 7963 bytes/chars
2024-05-09 09:19:07,045 - handlers.py[DEBUG]: finish: init-network/search-Ec2: SUCCESS: found network data from DataSourceEc2
2024-05-09 09:19:07,045 - stages.py[INFO]: Loaded datasource DataSourceEc2 - DataSourceEc2
2024-05-09 09:19:07,045 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg (quiet=False)
2024-05-09 09:19:07,045 - util.py[DEBUG]: Read 2553 bytes from /etc/cloud/cloud.cfg
2024-05-09 09:19:07,045 - util.py[DEBUG]: Attempting to load yaml from string of length 2553 with allowed root types (<class 'dict'>,)
2024-05-09 09:19:07,082 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/40_selinux-reboot.cfg (quiet=False)
2024-05-09 09:19:07,082 - util.py[DEBUG]: Read 174 bytes from /etc/cloud/cloud.cfg.d/40_selinux-reboot.cfg
2024-05-09 09:19:07,082 - util.py[DEBUG]: Attempting to load yaml from string of length 174 with allowed root types (<class 'dict'>,)
2024-05-09 09:19:07,085 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/10_aws_dnfvars.cfg (quiet=False)
2024-05-09 09:19:07,085 - util.py[DEBUG]: Read 591 bytes from /etc/cloud/cloud.cfg.d/10_aws_dnfvars.cfg
2024-05-09 09:19:07,085 - util.py[DEBUG]: Attempting to load yaml from string of length 591 with allowed root types (<class 'dict'>,)
2024-05-09 09:19:07,089 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/05_logging.cfg (quiet=False)
2024-05-09 09:19:07,090 - util.py[DEBUG]: Read 2070 bytes from /etc/cloud/cloud.cfg.d/05_logging.cfg
2024-05-09 09:19:07,090 - util.py[DEBUG]: Attempting to load yaml from string of length 2070 with allowed root types (<class 'dict'>,)
2024-05-09 09:19:07,096 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/01_amazon-ec2.cfg (quiet=False)
2024-05-09 09:19:07,097 - util.py[DEBUG]: Read 237 bytes from /etc/cloud/cloud.cfg.d/01_amazon-ec2.cfg
2024-05-09 09:19:07,097 - util.py[DEBUG]: Attempting to load yaml from string of length 237 with allowed root types (<class 'dict'>,)
2024-05-09 09:19:07,100 - util.py[DEBUG]: Reading from /run/cloud-init/cloud.cfg (quiet=False)
2024-05-09 09:19:07,100 - util.py[DEBUG]: Attempting to load yaml from string of length 0 with allowed root types (<class 'dict'>,)
2024-05-09 09:19:07,100 - util.py[DEBUG]: loaded blob returned None, returning default.
2024-05-09 09:19:07,101 - util.py[DEBUG]: Attempting to remove /var/lib/cloud/instance
2024-05-09 09:19:07,101 - util.py[DEBUG]: Creating symbolic link from '/var/lib/cloud/instance' => '/var/lib/cloud/instances/i-058d20c0b3bfe358b'
2024-05-09 09:19:07,102 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-058d20c0b3bfe358b (recursive=True)
2024-05-09 09:19:07,108 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-058d20c0b3bfe358b/handlers (recursive=False)
2024-05-09 09:19:07,109 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-058d20c0b3bfe358b (recursive=True)
2024-05-09 09:19:07,116 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-058d20c0b3bfe358b/scripts (recursive=False)
2024-05-09 09:19:07,117 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-058d20c0b3bfe358b (recursive=True)
2024-05-09 09:19:07,137 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-058d20c0b3bfe358b/sem (recursive=False)
2024-05-09 09:19:07,138 - util.py[DEBUG]: Reading from /var/lib/cloud/instances/i-058d20c0b3bfe358b/datasource (quiet=False)
2024-05-09 09:19:07,138 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-058d20c0b3bfe358b/datasource - wb: [644] 29 bytes
2024-05-09 09:19:07,139 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-058d20c0b3bfe358b/datasource (recursive=False)
2024-05-09 09:19:07,140 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-058d20c0b3bfe358b/datasource (recursive=False)
2024-05-09 09:19:07,140 - util.py[DEBUG]: Writing to /var/lib/cloud/data/previous-datasource - wb: [644] 29 bytes
2024-05-09 09:19:07,142 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/data/previous-datasource (recursive=False)
2024-05-09 09:19:07,149 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/data/previous-datasource (recursive=False)
2024-05-09 09:19:07,149 - util.py[DEBUG]: Reading from /var/lib/cloud/data/instance-id (quiet=False)
2024-05-09 09:19:07,149 - stages.py[DEBUG]: previous iid found to be NO_PREVIOUS_INSTANCE_ID
2024-05-09 09:19:07,150 - util.py[DEBUG]: Writing to /var/lib/cloud/data/instance-id - wb: [644] 20 bytes
2024-05-09 09:19:07,153 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/data/instance-id (recursive=False)
2024-05-09 09:19:07,154 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/data/instance-id (recursive=False)
2024-05-09 09:19:07,155 - util.py[DEBUG]: Writing to /run/cloud-init/.instance-id - wb: [644] 20 bytes
2024-05-09 09:19:07,155 - util.py[DEBUG]: Restoring selinux mode for /run/cloud-init/.instance-id (recursive=False)
2024-05-09 09:19:07,156 - util.py[DEBUG]: Restoring selinux mode for /run/cloud-init/.instance-id (recursive=False)
2024-05-09 09:19:07,156 - util.py[DEBUG]: Writing to /var/lib/cloud/data/previous-instance-id - wb: [644] 24 bytes
2024-05-09 09:19:07,158 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/data/previous-instance-id (recursive=False)
2024-05-09 09:19:07,159 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/data/previous-instance-id (recursive=False)
2024-05-09 09:19:07,160 - util.py[DEBUG]: Writing to /var/lib/cloud/instance/obj.pkl - wb: [400] 12736 bytes
2024-05-09 09:19:07,161 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-058d20c0b3bfe358b/obj.pkl (recursive=False)
2024-05-09 09:19:07,162 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-058d20c0b3bfe358b/obj.pkl (recursive=False)
2024-05-09 09:19:07,162 - main.py[DEBUG]: [net] init will now be targeting instance id: i-058d20c0b3bfe358b. new=True
2024-05-09 09:19:07,163 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg (quiet=False)
2024-05-09 09:19:07,163 - util.py[DEBUG]: Read 2553 bytes from /etc/cloud/cloud.cfg
2024-05-09 09:19:07,163 - util.py[DEBUG]: Attempting to load yaml from string of length 2553 with allowed root types (<class 'dict'>,)
2024-05-09 09:19:07,187 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/40_selinux-reboot.cfg (quiet=False)
2024-05-09 09:19:07,187 - util.py[DEBUG]: Read 174 bytes from /etc/cloud/cloud.cfg.d/40_selinux-reboot.cfg
2024-05-09 09:19:07,187 - util.py[DEBUG]: Attempting to load yaml from string of length 174 with allowed root types (<class 'dict'>,)
2024-05-09 09:19:07,188 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/10_aws_dnfvars.cfg (quiet=False)
2024-05-09 09:19:07,188 - util.py[DEBUG]: Read 591 bytes from /etc/cloud/cloud.cfg.d/10_aws_dnfvars.cfg
2024-05-09 09:19:07,188 - util.py[DEBUG]: Attempting to load yaml from string of length 591 with allowed root types (<class 'dict'>,)
2024-05-09 09:19:07,202 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/05_logging.cfg (quiet=False)
2024-05-09 09:19:07,202 - util.py[DEBUG]: Read 2070 bytes from /etc/cloud/cloud.cfg.d/05_logging.cfg
2024-05-09 09:19:07,202 - util.py[DEBUG]: Attempting to load yaml from string of length 2070 with allowed root types (<class 'dict'>,)
2024-05-09 09:19:07,208 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/01_amazon-ec2.cfg (quiet=False)
2024-05-09 09:19:07,208 - util.py[DEBUG]: Read 237 bytes from /etc/cloud/cloud.cfg.d/01_amazon-ec2.cfg
2024-05-09 09:19:07,208 - util.py[DEBUG]: Attempting to load yaml from string of length 237 with allowed root types (<class 'dict'>,)
2024-05-09 09:19:07,211 - util.py[DEBUG]: Reading from /run/cloud-init/cloud.cfg (quiet=False)
2024-05-09 09:19:07,211 - util.py[DEBUG]: Attempting to load yaml from string of length 0 with allowed root types (<class 'dict'>,)
2024-05-09 09:19:07,211 - util.py[DEBUG]: loaded blob returned None, returning default.
2024-05-09 09:19:07,212 - util.py[DEBUG]: Reading from /sys/class/net/ens5/address (quiet=False)
2024-05-09 09:19:07,213 - util.py[DEBUG]: Read 18 bytes from /sys/class/net/ens5/address
2024-05-09 09:19:07,213 - util.py[DEBUG]: Reading from /sys/class/net/lo/address (quiet=False)
2024-05-09 09:19:07,213 - util.py[DEBUG]: Read 18 bytes from /sys/class/net/lo/address
2024-05-09 09:19:07,213 - util.py[DEBUG]: Reading from /sys/class/net/ens5/name_assign_type (quiet=False)
2024-05-09 09:19:07,213 - util.py[DEBUG]: Read 2 bytes from /sys/class/net/ens5/name_assign_type
2024-05-09 09:19:07,213 - util.py[DEBUG]: Reading from /sys/class/net/ens5/address (quiet=False)
2024-05-09 09:19:07,213 - util.py[DEBUG]: Read 18 bytes from /sys/class/net/ens5/address
2024-05-09 09:19:07,214 - util.py[DEBUG]: Reading from /sys/class/net/ens5/carrier (quiet=False)
2024-05-09 09:19:07,214 - util.py[DEBUG]: Read 2 bytes from /sys/class/net/ens5/carrier
2024-05-09 09:19:07,214 - util.py[DEBUG]: Reading from /sys/class/net/ens5/addr_assign_type (quiet=False)
2024-05-09 09:19:07,214 - util.py[DEBUG]: Read 2 bytes from /sys/class/net/ens5/addr_assign_type
2024-05-09 09:19:07,214 - util.py[DEBUG]: Reading from /sys/class/net/ens5/uevent (quiet=False)
2024-05-09 09:19:07,214 - util.py[DEBUG]: Read 25 bytes from /sys/class/net/ens5/uevent
2024-05-09 09:19:07,214 - util.py[DEBUG]: Reading from /sys/class/net/ens5/address (quiet=False)
2024-05-09 09:19:07,214 - util.py[DEBUG]: Read 18 bytes from /sys/class/net/ens5/address
2024-05-09 09:19:07,214 - __init__.py[DEBUG]: ovs-vsctl not in PATH; not detecting Open vSwitch interfaces
2024-05-09 09:19:07,214 - util.py[DEBUG]: Reading from /sys/class/net/ens5/device/device (quiet=False)
2024-05-09 09:19:07,214 - util.py[DEBUG]: Read 7 bytes from /sys/class/net/ens5/device/device
2024-05-09 09:19:07,215 - util.py[DEBUG]: Reading from /sys/class/net/lo/addr_assign_type (quiet=False)
2024-05-09 09:19:07,215 - util.py[DEBUG]: Read 2 bytes from /sys/class/net/lo/addr_assign_type
2024-05-09 09:19:07,215 - util.py[DEBUG]: Reading from /sys/class/net/lo/uevent (quiet=False)
2024-05-09 09:19:07,215 - util.py[DEBUG]: Read 23 bytes from /sys/class/net/lo/uevent
2024-05-09 09:19:07,215 - util.py[DEBUG]: Reading from /sys/class/net/lo/address (quiet=False)
2024-05-09 09:19:07,215 - util.py[DEBUG]: Read 18 bytes from /sys/class/net/lo/address
2024-05-09 09:19:07,215 - util.py[DEBUG]: Reading from /sys/class/net/lo/device/device (quiet=False)
2024-05-09 09:19:07,215 - util.py[DEBUG]: Reading from /sys/class/net/ens5/type (quiet=False)
2024-05-09 09:19:07,215 - util.py[DEBUG]: Read 2 bytes from /sys/class/net/ens5/type
2024-05-09 09:19:07,215 - util.py[DEBUG]: Reading from /sys/class/net/lo/type (quiet=False)
2024-05-09 09:19:07,215 - util.py[DEBUG]: Read 4 bytes from /sys/class/net/lo/type
2024-05-09 09:19:07,215 - stages.py[DEBUG]: network config disabled by system_cfg
2024-05-09 09:19:07,215 - stages.py[INFO]: network config is disabled by system_cfg
2024-05-09 09:19:07,216 - handlers.py[DEBUG]: start: init-network/setup-datasource: setting up datasource
2024-05-09 09:19:07,216 - handlers.py[DEBUG]: finish: init-network/setup-datasource: SUCCESS: setting up datasource
2024-05-09 09:19:07,216 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-058d20c0b3bfe358b/user-data.txt - wb: [600] 2533 bytes
2024-05-09 09:19:07,216 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-058d20c0b3bfe358b/user-data.txt (recursive=False)
2024-05-09 09:19:07,218 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-058d20c0b3bfe358b/user-data.txt (recursive=False)
2024-05-09 09:19:07,220 - util.py[DEBUG]: Attempting to load yaml from string of length 104 with allowed root types (<class 'dict'>,)
2024-05-09 09:19:07,233 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-058d20c0b3bfe358b/user-data.txt.i - wb: [600] 2555 bytes
2024-05-09 09:19:07,234 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-058d20c0b3bfe358b/user-data.txt.i (recursive=False)
2024-05-09 09:19:07,235 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-058d20c0b3bfe358b/user-data.txt.i (recursive=False)
2024-05-09 09:19:07,236 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-058d20c0b3bfe358b/vendor-data.txt - wb: [600] 0 bytes
2024-05-09 09:19:07,237 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-058d20c0b3bfe358b/vendor-data.txt (recursive=False)
2024-05-09 09:19:07,238 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-058d20c0b3bfe358b/vendor-data.txt (recursive=False)
2024-05-09 09:19:07,240 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-058d20c0b3bfe358b/vendor-data.txt.i - wb: [600] 308 bytes
2024-05-09 09:19:07,240 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-058d20c0b3bfe358b/vendor-data.txt.i (recursive=False)
2024-05-09 09:19:07,241 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-058d20c0b3bfe358b/vendor-data.txt.i (recursive=False)
2024-05-09 09:19:07,243 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-058d20c0b3bfe358b/vendor-data2.txt - wb: [600] 0 bytes
2024-05-09 09:19:07,244 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-058d20c0b3bfe358b/vendor-data2.txt (recursive=False)
2024-05-09 09:19:07,245 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-058d20c0b3bfe358b/vendor-data2.txt (recursive=False)
2024-05-09 09:19:07,247 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-058d20c0b3bfe358b/vendor-data2.txt.i - wb: [600] 308 bytes
2024-05-09 09:19:07,248 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-058d20c0b3bfe358b/vendor-data2.txt.i (recursive=False)
2024-05-09 09:19:07,249 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-058d20c0b3bfe358b/vendor-data2.txt.i (recursive=False)
2024-05-09 09:19:07,251 - stages.py[DEBUG]: Using distro class <class 'cloudinit.distros.amazon.Distro'>
2024-05-09 09:19:07,262 - cc_set_hostname.py[DEBUG]: Setting the hostname to ip-172-31-40-43.ap-southeast-2.compute.internal (ip-172-31-40-43)
2024-05-09 09:19:07,262 - subp.py[DEBUG]: Running command ['hostnamectl', 'set-hostname', 'ip-172-31-40-43.ap-southeast-2.compute.internal'] with allowed return codes [0] (shell=False, capture=True)
2024-05-09 09:19:07,500 - __init__.py[DEBUG]: Non-persistently setting the system hostname to ip-172-31-40-43.ap-southeast-2.compute.internal
2024-05-09 09:19:07,501 - subp.py[DEBUG]: Running command ['hostname', 'ip-172-31-40-43.ap-southeast-2.compute.internal'] with allowed return codes [0] (shell=False, capture=True)
2024-05-09 09:19:07,507 - atomic_helper.py[DEBUG]: Atomically writing to file /var/lib/cloud/data/set-hostname (via temporary file /var/lib/cloud/data/tmpqe1xpu9s) - w: [644] 95 bytes/chars
2024-05-09 09:19:07,509 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-058d20c0b3bfe358b/sem/consume_data - wb: [644] 24 bytes
2024-05-09 09:19:07,512 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-058d20c0b3bfe358b/sem/consume_data (recursive=False)
2024-05-09 09:19:07,514 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-058d20c0b3bfe358b/sem/consume_data (recursive=False)
2024-05-09 09:19:07,515 - helpers.py[DEBUG]: Running consume_data using lock (<FileLock using file '/var/lib/cloud/instances/i-058d20c0b3bfe358b/sem/consume_data'>)
2024-05-09 09:19:07,516 - handlers.py[DEBUG]: start: init-network/consume-user-data: reading and applying user-data
2024-05-09 09:19:07,516 - launch_index.py[DEBUG]: Discarding 0 multipart messages which do not match launch index 0
2024-05-09 09:19:07,517 - stages.py[DEBUG]: Added default handler for {'text/cloud-config', 'text/cloud-config-jsonp'} from CloudConfigPartHandler: [['text/cloud-config', 'text/cloud-config-jsonp']]
2024-05-09 09:19:07,517 - stages.py[DEBUG]: Added default handler for {'text/x-shellscript'} from ShellScriptPartHandler: [['text/x-shellscript']]
2024-05-09 09:19:07,517 - stages.py[DEBUG]: Added default handler for {'text/x-shellscript-per-boot'} from ShellScriptByFreqPartHandler: [['text/x-shellscript-per-boot']]
2024-05-09 09:19:07,517 - stages.py[DEBUG]: Added default handler for {'text/x-shellscript-per-instance'} from ShellScriptByFreqPartHandler: [['text/x-shellscript-per-instance']]
2024-05-09 09:19:07,517 - stages.py[DEBUG]: Added default handler for {'text/x-shellscript-per-once'} from ShellScriptByFreqPartHandler: [['text/x-shellscript-per-once']]
2024-05-09 09:19:07,517 - stages.py[DEBUG]: Added default handler for {'text/cloud-boothook'} from BootHookPartHandler: [['text/cloud-boothook']]
2024-05-09 09:19:07,517 - stages.py[DEBUG]: Added default handler for {'text/jinja2'} from JinjaTemplatePartHandler: [['text/jinja2']]
2024-05-09 09:19:07,518 - __init__.py[DEBUG]: Calling handler CloudConfigPartHandler: [['text/cloud-config', 'text/cloud-config-jsonp']] (__begin__, None, 3) with frequency once-per-instance
2024-05-09 09:19:07,518 - __init__.py[DEBUG]: Calling handler ShellScriptPartHandler: [['text/x-shellscript']] (__begin__, None, 2) with frequency once-per-instance
2024-05-09 09:19:07,518 - __init__.py[DEBUG]: Calling handler ShellScriptByFreqPartHandler: [['text/x-shellscript-per-boot']] (__begin__, None, 2) with frequency once-per-instance
2024-05-09 09:19:07,518 - __init__.py[DEBUG]: Calling handler ShellScriptByFreqPartHandler: [['text/x-shellscript-per-instance']] (__begin__, None, 2) with frequency once-per-instance
2024-05-09 09:19:07,518 - __init__.py[DEBUG]: Calling handler ShellScriptByFreqPartHandler: [['text/x-shellscript-per-once']] (__begin__, None, 2) with frequency once-per-instance
2024-05-09 09:19:07,518 - __init__.py[DEBUG]: Calling handler BootHookPartHandler: [['text/cloud-boothook']] (__begin__, None, 2) with frequency once-per-instance
2024-05-09 09:19:07,518 - __init__.py[DEBUG]: Calling handler JinjaTemplatePartHandler: [['text/jinja2']] (__begin__, None, 3) with frequency once-per-instance
2024-05-09 09:19:07,519 - __init__.py[DEBUG]: {'Content-Type': 'text/cloud-config; charset="us-ascii"', 'MIME-Version': '1.0', 'Content-Transfer-Encoding': '7bit', 'Content-Disposition': 'attachment; filename="cloud-config.txt"'}
2024-05-09 09:19:07,519 - __init__.py[DEBUG]: Calling handler CloudConfigPartHandler: [['text/cloud-config', 'text/cloud-config-jsonp']] (text/cloud-config, cloud-config.txt, 3) with frequency once-per-instance
2024-05-09 09:19:07,519 - util.py[DEBUG]: Attempting to load yaml from string of length 104 with allowed root types (<class 'dict'>,)
2024-05-09 09:19:07,521 - cloud_config.py[DEBUG]: Merging by applying [('dict', ['replace']), ('list', []), ('str', [])]
2024-05-09 09:19:07,521 - __init__.py[DEBUG]: {'Content-Type': 'text/x-shellscript; charset="us-ascii"', 'MIME-Version': '1.0', 'Content-Transfer-Encoding': '7bit', 'Content-Disposition': 'attachment; filename="user-data.txt"'}
2024-05-09 09:19:07,521 - __init__.py[DEBUG]: Calling handler ShellScriptPartHandler: [['text/x-shellscript']] (text/x-shellscript, user-data.txt, 2) with frequency once-per-instance
2024-05-09 09:19:07,522 - util.py[DEBUG]: Writing to /var/lib/cloud/instance/scripts/user-data.txt - wb: [700] 1884 bytes
2024-05-09 09:19:07,523 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-058d20c0b3bfe358b/scripts/user-data.txt (recursive=False)
2024-05-09 09:19:07,525 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-058d20c0b3bfe358b/scripts/user-data.txt (recursive=False)
2024-05-09 09:19:07,525 - __init__.py[DEBUG]: Calling handler CloudConfigPartHandler: [['text/cloud-config', 'text/cloud-config-jsonp']] (__end__, None, 3) with frequency once-per-instance
2024-05-09 09:19:07,526 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-058d20c0b3bfe358b/cloud-config.txt - wb: [600] 154 bytes
2024-05-09 09:19:07,527 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-058d20c0b3bfe358b/cloud-config.txt (recursive=False)
2024-05-09 09:19:07,529 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-058d20c0b3bfe358b/cloud-config.txt (recursive=False)
2024-05-09 09:19:07,530 - __init__.py[DEBUG]: Calling handler ShellScriptPartHandler: [['text/x-shellscript']] (__end__, None, 2) with frequency once-per-instance
2024-05-09 09:19:07,530 - __init__.py[DEBUG]: Calling handler ShellScriptByFreqPartHandler: [['text/x-shellscript-per-boot']] (__end__, None, 2) with frequency once-per-instance
2024-05-09 09:19:07,530 - __init__.py[DEBUG]: Calling handler ShellScriptByFreqPartHandler: [['text/x-shellscript-per-instance']] (__end__, None, 2) with frequency once-per-instance
2024-05-09 09:19:07,530 - __init__.py[DEBUG]: Calling handler ShellScriptByFreqPartHandler: [['text/x-shellscript-per-once']] (__end__, None, 2) with frequency once-per-instance
2024-05-09 09:19:07,530 - __init__.py[DEBUG]: Calling handler BootHookPartHandler: [['text/cloud-boothook']] (__end__, None, 2) with frequency once-per-instance
2024-05-09 09:19:07,530 - __init__.py[DEBUG]: Calling handler JinjaTemplatePartHandler: [['text/jinja2']] (__end__, None, 3) with frequency once-per-instance
2024-05-09 09:19:07,530 - handlers.py[DEBUG]: finish: init-network/consume-user-data: SUCCESS: reading and applying user-data
2024-05-09 09:19:07,531 - handlers.py[DEBUG]: start: init-network/consume-vendor-data: reading and applying vendor-data
2024-05-09 09:19:07,531 - stages.py[DEBUG]: no vendordata from datasource
2024-05-09 09:19:07,531 - handlers.py[DEBUG]: finish: init-network/consume-vendor-data: SUCCESS: reading and applying vendor-data
2024-05-09 09:19:07,531 - handlers.py[DEBUG]: start: init-network/consume-vendor-data2: reading and applying vendor-data2
2024-05-09 09:19:07,531 - stages.py[DEBUG]: no vendordata2 from datasource
2024-05-09 09:19:07,531 - handlers.py[DEBUG]: finish: init-network/consume-vendor-data2: SUCCESS: reading and applying vendor-data2
2024-05-09 09:19:07,552 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg (quiet=False)
2024-05-09 09:19:07,552 - util.py[DEBUG]: Read 2553 bytes from /etc/cloud/cloud.cfg
2024-05-09 09:19:07,552 - util.py[DEBUG]: Attempting to load yaml from string of length 2553 with allowed root types (<class 'dict'>,)
2024-05-09 09:19:07,568 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/40_selinux-reboot.cfg (quiet=False)
2024-05-09 09:19:07,568 - util.py[DEBUG]: Read 174 bytes from /etc/cloud/cloud.cfg.d/40_selinux-reboot.cfg
2024-05-09 09:19:07,568 - util.py[DEBUG]: Attempting to load yaml from string of length 174 with allowed root types (<class 'dict'>,)
2024-05-09 09:19:07,569 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/10_aws_dnfvars.cfg (quiet=False)
2024-05-09 09:19:07,569 - util.py[DEBUG]: Read 591 bytes from /etc/cloud/cloud.cfg.d/10_aws_dnfvars.cfg
2024-05-09 09:19:07,569 - util.py[DEBUG]: Attempting to load yaml from string of length 591 with allowed root types (<class 'dict'>,)
2024-05-09 09:19:07,583 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/05_logging.cfg (quiet=False)
2024-05-09 09:19:07,583 - util.py[DEBUG]: Read 2070 bytes from /etc/cloud/cloud.cfg.d/05_logging.cfg
2024-05-09 09:19:07,583 - util.py[DEBUG]: Attempting to load yaml from string of length 2070 with allowed root types (<class 'dict'>,)
2024-05-09 09:19:07,590 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/01_amazon-ec2.cfg (quiet=False)
2024-05-09 09:19:07,590 - util.py[DEBUG]: Read 237 bytes from /etc/cloud/cloud.cfg.d/01_amazon-ec2.cfg
2024-05-09 09:19:07,590 - util.py[DEBUG]: Attempting to load yaml from string of length 237 with allowed root types (<class 'dict'>,)
2024-05-09 09:19:07,593 - util.py[DEBUG]: Reading from /run/cloud-init/cloud.cfg (quiet=False)
2024-05-09 09:19:07,593 - util.py[DEBUG]: Attempting to load yaml from string of length 0 with allowed root types (<class 'dict'>,)
2024-05-09 09:19:07,593 - util.py[DEBUG]: loaded blob returned None, returning default.
2024-05-09 09:19:07,593 - util.py[DEBUG]: Reading from /var/lib/cloud/instance/cloud-config.txt (quiet=False)
2024-05-09 09:19:07,593 - util.py[DEBUG]: Read 154 bytes from /var/lib/cloud/instance/cloud-config.txt
2024-05-09 09:19:07,594 - util.py[DEBUG]: Attempting to load yaml from string of length 154 with allowed root types (<class 'dict'>,)
2024-05-09 09:19:07,596 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2024-05-09 09:19:07,596 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2024-05-09 09:19:07,709 - util.py[DEBUG]: Reading from /var/lib/cloud/instance/cloud-config.txt (quiet=False)
2024-05-09 09:19:07,710 - util.py[DEBUG]: Read 154 bytes from /var/lib/cloud/instance/cloud-config.txt
2024-05-09 09:19:07,710 - util.py[DEBUG]: Attempting to load yaml from string of length 154 with allowed root types (<class 'dict'>,)
2024-05-09 09:19:07,716 - handlers.py[DEBUG]: start: init-network/activate-datasource: activating datasource
2024-05-09 09:19:07,717 - util.py[DEBUG]: Writing to /var/lib/cloud/instance/obj.pkl - wb: [400] 16968 bytes
2024-05-09 09:19:07,732 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-058d20c0b3bfe358b/obj.pkl (recursive=False)
2024-05-09 09:19:07,734 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-058d20c0b3bfe358b/obj.pkl (recursive=False)
2024-05-09 09:19:07,735 - handlers.py[DEBUG]: finish: init-network/activate-datasource: SUCCESS: activating datasource
2024-05-09 09:19:07,736 - main.py[DEBUG]: no di_report found in config.
2024-05-09 09:19:07,739 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2024-05-09 09:19:07,740 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2024-05-09 09:19:07,743 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2024-05-09 09:19:07,744 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2024-05-09 09:19:07,752 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2024-05-09 09:19:07,752 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2024-05-09 09:19:07,756 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2024-05-09 09:19:07,757 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2024-05-09 09:19:07,763 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2024-05-09 09:19:07,763 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2024-05-09 09:19:07,768 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2024-05-09 09:19:07,768 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2024-05-09 09:19:07,783 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2024-05-09 09:19:07,784 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2024-05-09 09:19:07,790 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2024-05-09 09:19:07,790 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2024-05-09 09:19:07,795 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2024-05-09 09:19:07,795 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2024-05-09 09:19:07,802 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2024-05-09 09:19:07,802 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2024-05-09 09:19:07,806 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2024-05-09 09:19:07,806 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2024-05-09 09:19:07,812 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2024-05-09 09:19:07,812 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2024-05-09 09:19:07,818 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2024-05-09 09:19:07,818 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2024-05-09 09:19:07,836 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2024-05-09 09:19:07,837 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2024-05-09 09:19:07,845 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2024-05-09 09:19:07,846 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2024-05-09 09:19:07,851 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2024-05-09 09:19:07,851 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2024-05-09 09:19:07,857 - stages.py[DEBUG]: Using distro class <class 'cloudinit.distros.amazon.Distro'>
2024-05-09 09:19:07,858 - modules.py[DEBUG]: Running module migrator (<module 'cloudinit.config.cc_migrator' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_migrator.py'>) with frequency always
2024-05-09 09:19:07,859 - handlers.py[DEBUG]: start: init-network/config-migrator: running config-migrator with frequency always
2024-05-09 09:19:07,859 - helpers.py[DEBUG]: Running config-migrator using lock (<cloudinit.helpers.DummyLock object at 0x7f3f6d28de80>)
2024-05-09 09:19:07,859 - cc_migrator.py[DEBUG]: Migrated 0 semaphore files to there canonicalized names
2024-05-09 09:19:07,859 - handlers.py[DEBUG]: finish: init-network/config-migrator: SUCCESS: config-migrator ran successfully
2024-05-09 09:19:07,859 - modules.py[DEBUG]: Running module seed_random (<module 'cloudinit.config.cc_seed_random' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_seed_random.py'>) with frequency once-per-instance
2024-05-09 09:19:07,860 - handlers.py[DEBUG]: start: init-network/config-seed_random: running config-seed_random with frequency once-per-instance
2024-05-09 09:19:07,860 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-058d20c0b3bfe358b/sem/config_seed_random - wb: [644] 25 bytes
2024-05-09 09:19:07,861 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-058d20c0b3bfe358b/sem/config_seed_random (recursive=False)
2024-05-09 09:19:07,874 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-058d20c0b3bfe358b/sem/config_seed_random (recursive=False)
2024-05-09 09:19:07,875 - helpers.py[DEBUG]: Running config-seed_random using lock (<FileLock using file '/var/lib/cloud/instances/i-058d20c0b3bfe358b/sem/config_seed_random'>)
2024-05-09 09:19:07,875 - cc_seed_random.py[DEBUG]: no command provided
2024-05-09 09:19:07,875 - handlers.py[DEBUG]: finish: init-network/config-seed_random: SUCCESS: config-seed_random ran successfully
2024-05-09 09:19:07,875 - modules.py[DEBUG]: Running module bootcmd (<module 'cloudinit.config.cc_bootcmd' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_bootcmd.py'>) with frequency always
2024-05-09 09:19:07,876 - handlers.py[DEBUG]: start: init-network/config-bootcmd: running config-bootcmd with frequency always
2024-05-09 09:19:07,876 - helpers.py[DEBUG]: Running config-bootcmd using lock (<cloudinit.helpers.DummyLock object at 0x7f3f6d28de80>)
2024-05-09 09:19:07,876 - cc_bootcmd.py[DEBUG]: Skipping module named bootcmd, no 'bootcmd' key in configuration
2024-05-09 09:19:07,876 - handlers.py[DEBUG]: finish: init-network/config-bootcmd: SUCCESS: config-bootcmd ran successfully
2024-05-09 09:19:07,876 - modules.py[DEBUG]: Running module write-files (<module 'cloudinit.config.cc_write_files' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_write_files.py'>) with frequency once-per-instance
2024-05-09 09:19:07,876 - handlers.py[DEBUG]: start: init-network/config-write-files: running config-write-files with frequency once-per-instance
2024-05-09 09:19:07,877 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-058d20c0b3bfe358b/sem/config_write_files - wb: [644] 24 bytes
2024-05-09 09:19:07,878 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-058d20c0b3bfe358b/sem/config_write_files (recursive=False)
2024-05-09 09:19:07,879 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-058d20c0b3bfe358b/sem/config_write_files (recursive=False)
2024-05-09 09:19:07,880 - helpers.py[DEBUG]: Running config-write-files using lock (<FileLock using file '/var/lib/cloud/instances/i-058d20c0b3bfe358b/sem/config_write_files'>)
2024-05-09 09:19:07,880 - cc_write_files.py[DEBUG]: Skipping module named write-files, no/empty 'write_files' key in configuration
2024-05-09 09:19:07,881 - handlers.py[DEBUG]: finish: init-network/config-write-files: SUCCESS: config-write-files ran successfully
2024-05-09 09:19:07,882 - modules.py[DEBUG]: Running module write-metadata (<module 'cloudinit.config.cc_write_metadata' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_write_metadata.py'>) with frequency once-per-instance
2024-05-09 09:19:07,882 - handlers.py[DEBUG]: start: init-network/config-write-metadata: running config-write-metadata with frequency once-per-instance
2024-05-09 09:19:07,883 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-058d20c0b3bfe358b/sem/config_write_metadata - wb: [644] 23 bytes
2024-05-09 09:19:07,884 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-058d20c0b3bfe358b/sem/config_write_metadata (recursive=False)
2024-05-09 09:19:07,885 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-058d20c0b3bfe358b/sem/config_write_metadata (recursive=False)
2024-05-09 09:19:07,886 - helpers.py[DEBUG]: Running config-write-metadata using lock (<FileLock using file '/var/lib/cloud/instances/i-058d20c0b3bfe358b/sem/config_write_metadata'>)
2024-05-09 09:19:07,886 - util.py[DEBUG]: Writing to /etc/dnf/vars/awsregion - wb: [644] 14 bytes
2024-05-09 09:19:07,890 - util.py[DEBUG]: Restoring selinux mode for /etc/dnf/vars/awsregion (recursive=False)
2024-05-09 09:19:07,892 - util.py[DEBUG]: Restoring selinux mode for /etc/dnf/vars/awsregion (recursive=False)
2024-05-09 09:19:07,893 - util.py[DEBUG]: Changing the ownership of /etc/dnf/vars/awsregion to 0:0
2024-05-09 09:19:07,893 - util.py[DEBUG]: Writing to /etc/dnf/vars/awsdomain - wb: [644] 13 bytes
2024-05-09 09:19:07,894 - util.py[DEBUG]: Restoring selinux mode for /etc/dnf/vars/awsdomain (recursive=False)
2024-05-09 09:19:07,903 - util.py[DEBUG]: Restoring selinux mode for /etc/dnf/vars/awsdomain (recursive=False)
2024-05-09 09:19:07,903 - util.py[DEBUG]: Changing the ownership of /etc/dnf/vars/awsdomain to 0:0
2024-05-09 09:19:07,904 - handlers.py[DEBUG]: finish: init-network/config-write-metadata: SUCCESS: config-write-metadata ran successfully
2024-05-09 09:19:07,904 - modules.py[DEBUG]: Running module growpart (<module 'cloudinit.config.cc_growpart' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_growpart.py'>) with frequency always
2024-05-09 09:19:07,904 - handlers.py[DEBUG]: start: init-network/config-growpart: running config-growpart with frequency always
2024-05-09 09:19:07,904 - helpers.py[DEBUG]: Running config-growpart using lock (<cloudinit.helpers.DummyLock object at 0x7f3f6d28df70>)
2024-05-09 09:19:07,904 - cc_growpart.py[DEBUG]: No 'growpart' entry in cfg.  Using default: {'mode': 'auto', 'devices': ['/'], 'ignore_growroot_disabled': False}
2024-05-09 09:19:07,904 - subp.py[DEBUG]: Running command ['growpart', '--help'] with allowed return codes [0] (shell=False, capture=True)
2024-05-09 09:19:07,929 - util.py[DEBUG]: Reading from /proc/1452/mountinfo (quiet=False)
2024-05-09 09:19:07,930 - util.py[DEBUG]: Read 2926 bytes from /proc/1452/mountinfo
2024-05-09 09:19:07,930 - util.py[DEBUG]: Reading from /sys/class/block/nvme0n1p1/partition (quiet=False)
2024-05-09 09:19:07,930 - util.py[DEBUG]: Read 2 bytes from /sys/class/block/nvme0n1p1/partition
2024-05-09 09:19:07,930 - util.py[DEBUG]: Reading from /sys/devices/pci0000:00/0000:00:04.0/nvme/nvme0/nvme0n1/dev (quiet=False)
2024-05-09 09:19:07,930 - util.py[DEBUG]: Read 6 bytes from /sys/devices/pci0000:00/0000:00:04.0/nvme/nvme0/nvme0n1/dev
2024-05-09 09:19:07,931 - subp.py[DEBUG]: Running command ['growpart', '--dry-run', '/dev/nvme0n1', '1'] with allowed return codes [0] (shell=False, capture=True)
2024-05-09 09:19:08,050 - util.py[DEBUG]: resize_devices took 0.121 seconds
2024-05-09 09:19:08,051 - cc_growpart.py[DEBUG]: '/' NOCHANGE: no change necessary (/dev/nvme0n1, 1)
2024-05-09 09:19:08,051 - handlers.py[DEBUG]: finish: init-network/config-growpart: SUCCESS: config-growpart ran successfully
2024-05-09 09:19:08,051 - modules.py[DEBUG]: Running module resizefs (<module 'cloudinit.config.cc_resizefs' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_resizefs.py'>) with frequency always
2024-05-09 09:19:08,052 - handlers.py[DEBUG]: start: init-network/config-resizefs: running config-resizefs with frequency always
2024-05-09 09:19:08,052 - helpers.py[DEBUG]: Running config-resizefs using lock (<cloudinit.helpers.DummyLock object at 0x7f3f6d28dd00>)
2024-05-09 09:19:08,052 - util.py[DEBUG]: Reading from /proc/1452/mountinfo (quiet=False)
2024-05-09 09:19:08,052 - util.py[DEBUG]: Read 2926 bytes from /proc/1452/mountinfo
2024-05-09 09:19:08,052 - cc_resizefs.py[DEBUG]: resize_info: dev=/dev/nvme0n1p1 mnt_point=/ path=/
2024-05-09 09:19:08,052 - cc_resizefs.py[DEBUG]: Resizing / (xfs) using xfs_growfs /
2024-05-09 09:19:08,054 - util.py[DEBUG]: Forked child 1585 who will run callback log_time
2024-05-09 09:19:08,054 - cc_resizefs.py[DEBUG]: Resizing (via forking) root filesystem (type=xfs, val=noblock)
2024-05-09 09:19:08,054 - subp.py[DEBUG]: Running command ('xfs_growfs', '/') with allowed return codes [0] (shell=False, capture=True)
2024-05-09 09:19:08,055 - handlers.py[DEBUG]: finish: init-network/config-resizefs: SUCCESS: config-resizefs ran successfully
2024-05-09 09:19:08,055 - modules.py[DEBUG]: Running module disk_setup (<module 'cloudinit.config.cc_disk_setup' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_disk_setup.py'>) with frequency once-per-instance
2024-05-09 09:19:08,056 - handlers.py[DEBUG]: start: init-network/config-disk_setup: running config-disk_setup with frequency once-per-instance
2024-05-09 09:19:08,056 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-058d20c0b3bfe358b/sem/config_disk_setup - wb: [644] 25 bytes
2024-05-09 09:19:08,058 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-058d20c0b3bfe358b/sem/config_disk_setup (recursive=False)
2024-05-09 09:19:08,061 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-058d20c0b3bfe358b/sem/config_disk_setup (recursive=False)
2024-05-09 09:19:08,082 - helpers.py[DEBUG]: Running config-disk_setup using lock (<FileLock using file '/var/lib/cloud/instances/i-058d20c0b3bfe358b/sem/config_disk_setup'>)
2024-05-09 09:19:08,082 - handlers.py[DEBUG]: finish: init-network/config-disk_setup: SUCCESS: config-disk_setup ran successfully
2024-05-09 09:19:08,082 - modules.py[DEBUG]: Running module mounts (<module 'cloudinit.config.cc_mounts' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_mounts.py'>) with frequency once-per-instance
2024-05-09 09:19:08,083 - handlers.py[DEBUG]: start: init-network/config-mounts: running config-mounts with frequency once-per-instance
2024-05-09 09:19:08,083 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-058d20c0b3bfe358b/sem/config_mounts - wb: [644] 23 bytes
2024-05-09 09:19:08,084 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-058d20c0b3bfe358b/sem/config_mounts (recursive=False)
2024-05-09 09:19:08,085 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-058d20c0b3bfe358b/sem/config_mounts (recursive=False)
2024-05-09 09:19:08,086 - helpers.py[DEBUG]: Running config-mounts using lock (<FileLock using file '/var/lib/cloud/instances/i-058d20c0b3bfe358b/sem/config_mounts'>)
2024-05-09 09:19:08,086 - cc_mounts.py[DEBUG]: mounts configuration is []
2024-05-09 09:19:08,087 - util.py[DEBUG]: Reading from /etc/fstab (quiet=False)
2024-05-09 09:19:08,087 - util.py[DEBUG]: Read 217 bytes from /etc/fstab
2024-05-09 09:19:08,087 - cc_mounts.py[DEBUG]: Attempting to determine the real name of ephemeral0
2024-05-09 09:19:08,087 - DataSourceEc2.py[DEBUG]: Unable to convert ephemeral0 to a device
2024-05-09 09:19:08,087 - cc_mounts.py[DEBUG]: changed default device ephemeral0 => None
2024-05-09 09:19:08,087 - cc_mounts.py[DEBUG]: Ignoring nonexistent default named mount ephemeral0
2024-05-09 09:19:08,087 - cc_mounts.py[DEBUG]: Attempting to determine the real name of swap
2024-05-09 09:19:08,087 - DataSourceEc2.py[DEBUG]: Unable to convert swap to a device
2024-05-09 09:19:08,087 - cc_mounts.py[DEBUG]: changed default device swap => None
2024-05-09 09:19:08,087 - cc_mounts.py[DEBUG]: Ignoring nonexistent default named mount swap
2024-05-09 09:19:08,087 - cc_mounts.py[DEBUG]: no need to setup swap
2024-05-09 09:19:08,087 - cc_mounts.py[DEBUG]: No modifications to fstab needed
2024-05-09 09:19:08,087 - handlers.py[DEBUG]: finish: init-network/config-mounts: SUCCESS: config-mounts ran successfully
2024-05-09 09:19:08,087 - modules.py[DEBUG]: Running module set_hostname (<module 'cloudinit.config.cc_set_hostname' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_set_hostname.py'>) with frequency always
2024-05-09 09:19:08,088 - handlers.py[DEBUG]: start: init-network/config-set_hostname: running config-set_hostname with frequency always
2024-05-09 09:19:08,088 - helpers.py[DEBUG]: Running config-set_hostname using lock (<cloudinit.helpers.DummyLock object at 0x7f3f6d2cd940>)
2024-05-09 09:19:08,088 - util.py[DEBUG]: Reading from /var/lib/cloud/data/set-hostname (quiet=False)
2024-05-09 09:19:08,088 - util.py[DEBUG]: Read 95 bytes from /var/lib/cloud/data/set-hostname
2024-05-09 09:19:08,088 - cc_set_hostname.py[DEBUG]: No hostname changes. Skipping set-hostname
2024-05-09 09:19:08,088 - handlers.py[DEBUG]: finish: init-network/config-set_hostname: SUCCESS: config-set_hostname ran successfully
2024-05-09 09:19:08,088 - modules.py[DEBUG]: Running module update_hostname (<module 'cloudinit.config.cc_update_hostname' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_update_hostname.py'>) with frequency always
2024-05-09 09:19:08,089 - handlers.py[DEBUG]: start: init-network/config-update_hostname: running config-update_hostname with frequency always
2024-05-09 09:19:08,089 - helpers.py[DEBUG]: Running config-update_hostname using lock (<cloudinit.helpers.DummyLock object at 0x7f3f6d28dd00>)
2024-05-09 09:19:08,089 - cc_update_hostname.py[DEBUG]: Updating hostname to ip-172-31-40-43.ap-southeast-2.compute.internal (ip-172-31-40-43)
2024-05-09 09:19:08,089 - subp.py[DEBUG]: Running command ['hostname'] with allowed return codes [0] (shell=False, capture=True)
2024-05-09 09:19:08,093 - __init__.py[DEBUG]: Attempting to update hostname to ip-172-31-40-43.ap-southeast-2.compute.internal in 1 files
2024-05-09 09:19:08,094 - util.py[DEBUG]: Writing to /var/lib/cloud/data/previous-hostname - wb: [644] 47 bytes
2024-05-09 09:19:08,095 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/data/previous-hostname (recursive=False)
2024-05-09 09:19:08,102 - util.py[DEBUG]: backgrounded Resizing took 0.048 seconds
2024-05-09 09:19:08,104 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/data/previous-hostname (recursive=False)
2024-05-09 09:19:08,105 - handlers.py[DEBUG]: finish: init-network/config-update_hostname: SUCCESS: config-update_hostname ran successfully
2024-05-09 09:19:08,105 - modules.py[DEBUG]: Running module update_etc_hosts (<module 'cloudinit.config.cc_update_etc_hosts' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_update_etc_hosts.py'>) with frequency always
2024-05-09 09:19:08,105 - handlers.py[DEBUG]: start: init-network/config-update_etc_hosts: running config-update_etc_hosts with frequency always
2024-05-09 09:19:08,105 - helpers.py[DEBUG]: Running config-update_etc_hosts using lock (<cloudinit.helpers.DummyLock object at 0x7f3f6d28dfd0>)
2024-05-09 09:19:08,106 - cc_update_etc_hosts.py[DEBUG]: Configuration option 'manage_etc_hosts' is not set, not managing /etc/hosts in module update_etc_hosts
2024-05-09 09:19:08,106 - handlers.py[DEBUG]: finish: init-network/config-update_etc_hosts: SUCCESS: config-update_etc_hosts ran successfully
2024-05-09 09:19:08,106 - modules.py[DEBUG]: Running module ca-certs (<module 'cloudinit.config.cc_ca_certs' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_ca_certs.py'>) with frequency once-per-instance
2024-05-09 09:19:08,106 - handlers.py[DEBUG]: start: init-network/config-ca-certs: running config-ca-certs with frequency once-per-instance
2024-05-09 09:19:08,106 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-058d20c0b3bfe358b/sem/config_ca_certs - wb: [644] 25 bytes
2024-05-09 09:19:08,107 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-058d20c0b3bfe358b/sem/config_ca_certs (recursive=False)
2024-05-09 09:19:08,108 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-058d20c0b3bfe358b/sem/config_ca_certs (recursive=False)
2024-05-09 09:19:08,109 - helpers.py[DEBUG]: Running config-ca-certs using lock (<FileLock using file '/var/lib/cloud/instances/i-058d20c0b3bfe358b/sem/config_ca_certs'>)
2024-05-09 09:19:08,109 - cc_ca_certs.py[DEBUG]: Skipping module named ca-certs, no 'ca_certs' key in configuration
2024-05-09 09:19:08,109 - handlers.py[DEBUG]: finish: init-network/config-ca-certs: SUCCESS: config-ca-certs ran successfully
2024-05-09 09:19:08,109 - modules.py[DEBUG]: Running module rsyslog (<module 'cloudinit.config.cc_rsyslog' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_rsyslog.py'>) with frequency once-per-instance
2024-05-09 09:19:08,109 - handlers.py[DEBUG]: start: init-network/config-rsyslog: running config-rsyslog with frequency once-per-instance
2024-05-09 09:19:08,109 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-058d20c0b3bfe358b/sem/config_rsyslog - wb: [644] 24 bytes
2024-05-09 09:19:08,110 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-058d20c0b3bfe358b/sem/config_rsyslog (recursive=False)
2024-05-09 09:19:08,111 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-058d20c0b3bfe358b/sem/config_rsyslog (recursive=False)
2024-05-09 09:19:08,112 - helpers.py[DEBUG]: Running config-rsyslog using lock (<FileLock using file '/var/lib/cloud/instances/i-058d20c0b3bfe358b/sem/config_rsyslog'>)
2024-05-09 09:19:08,112 - cc_rsyslog.py[DEBUG]: Skipping module named rsyslog, no 'rsyslog' key in configuration
2024-05-09 09:19:08,112 - handlers.py[DEBUG]: finish: init-network/config-rsyslog: SUCCESS: config-rsyslog ran successfully
2024-05-09 09:19:08,112 - modules.py[DEBUG]: Running module selinux (<module 'cloudinit.config.cc_selinux' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_selinux.py'>) with frequency once-per-instance
2024-05-09 09:19:08,113 - handlers.py[DEBUG]: start: init-network/config-selinux: running config-selinux with frequency once-per-instance
2024-05-09 09:19:08,113 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-058d20c0b3bfe358b/sem/config_selinux - wb: [644] 24 bytes
2024-05-09 09:19:08,114 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-058d20c0b3bfe358b/sem/config_selinux (recursive=False)
2024-05-09 09:19:08,115 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-058d20c0b3bfe358b/sem/config_selinux (recursive=False)
2024-05-09 09:19:08,116 - helpers.py[DEBUG]: Running config-selinux using lock (<FileLock using file '/var/lib/cloud/instances/i-058d20c0b3bfe358b/sem/config_selinux'>)
2024-05-09 09:19:08,125 - cc_selinux.py[DEBUG]: Current SELinux state is enabled
2024-05-09 09:19:08,125 - cc_selinux.py[DEBUG]: Current SELinux mode is permissive
2024-05-09 09:19:08,125 - cc_selinux.py[DEBUG]: Configured SELinux mode is permissive
2024-05-09 09:19:08,125 - cc_selinux.py[DEBUG]: Current SELinux policy is targeted
2024-05-09 09:19:08,125 - cc_selinux.py[DEBUG]: No SELinux configuration, skipping
2024-05-09 09:19:08,125 - handlers.py[DEBUG]: finish: init-network/config-selinux: SUCCESS: config-selinux ran successfully
2024-05-09 09:19:08,125 - modules.py[DEBUG]: Running module users-groups (<module 'cloudinit.config.cc_users_groups' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_users_groups.py'>) with frequency once-per-instance
2024-05-09 09:19:08,126 - handlers.py[DEBUG]: start: init-network/config-users-groups: running config-users-groups with frequency once-per-instance
2024-05-09 09:19:08,126 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-058d20c0b3bfe358b/sem/config_users_groups - wb: [644] 25 bytes
2024-05-09 09:19:08,127 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-058d20c0b3bfe358b/sem/config_users_groups (recursive=False)
2024-05-09 09:19:08,129 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-058d20c0b3bfe358b/sem/config_users_groups (recursive=False)
2024-05-09 09:19:08,130 - helpers.py[DEBUG]: Running config-users-groups using lock (<FileLock using file '/var/lib/cloud/instances/i-058d20c0b3bfe358b/sem/config_users_groups'>)
2024-05-09 09:19:08,131 - __init__.py[INFO]: User ec2-user already exists, skipping.
2024-05-09 09:19:08,131 - subp.py[DEBUG]: Running command ['passwd', '-l', 'ec2-user'] with allowed return codes [0] (shell=False, capture=True)
2024-05-09 09:19:08,181 - util.py[DEBUG]: Reading from /etc/sudoers (quiet=False)
2024-05-09 09:19:08,182 - util.py[DEBUG]: Read 4375 bytes from /etc/sudoers
2024-05-09 09:19:08,184 - util.py[DEBUG]: Restoring selinux mode for /etc/sudoers.d (recursive=False)
2024-05-09 09:19:08,185 - util.py[DEBUG]: Writing to /etc/sudoers.d/90-cloud-init-users - ab: [None] 59 bytes
2024-05-09 09:19:08,186 - util.py[DEBUG]: Restoring selinux mode for /etc/sudoers.d/90-cloud-init-users (recursive=False)
2024-05-09 09:19:08,187 - handlers.py[DEBUG]: finish: init-network/config-users-groups: SUCCESS: config-users-groups ran successfully
2024-05-09 09:19:08,187 - modules.py[DEBUG]: Running module ssh (<module 'cloudinit.config.cc_ssh' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_ssh.py'>) with frequency once-per-instance
2024-05-09 09:19:08,187 - handlers.py[DEBUG]: start: init-network/config-ssh: running config-ssh with frequency once-per-instance
2024-05-09 09:19:08,187 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-058d20c0b3bfe358b/sem/config_ssh - wb: [644] 25 bytes
2024-05-09 09:19:08,189 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-058d20c0b3bfe358b/sem/config_ssh (recursive=False)
2024-05-09 09:19:08,191 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-058d20c0b3bfe358b/sem/config_ssh (recursive=False)
2024-05-09 09:19:08,191 - helpers.py[DEBUG]: Running config-ssh using lock (<FileLock using file '/var/lib/cloud/instances/i-058d20c0b3bfe358b/sem/config_ssh'>)
2024-05-09 09:19:08,192 - subp.py[DEBUG]: Running command ['ssh-keygen', '-t', 'ed25519', '-N', '', '-f', '/etc/ssh/ssh_host_ed25519_key'] with allowed return codes [0] (shell=False, capture=True)
2024-05-09 09:19:08,218 - util.py[DEBUG]: Restoring selinux mode for /etc/ssh (recursive=True)
2024-05-09 09:19:08,235 - subp.py[DEBUG]: Running command ['ssh-keygen', '-t', 'ecdsa', '-N', '', '-f', '/etc/ssh/ssh_host_ecdsa_key'] with allowed return codes [0] (shell=False, capture=True)
2024-05-09 09:19:08,255 - util.py[DEBUG]: Restoring selinux mode for /etc/ssh (recursive=True)
2024-05-09 09:19:08,274 - util.py[DEBUG]: Reading from /etc/ssh/ssh_host_ed25519_key.pub (quiet=False)
2024-05-09 09:19:08,274 - util.py[DEBUG]: Read 134 bytes from /etc/ssh/ssh_host_ed25519_key.pub
2024-05-09 09:19:08,274 - util.py[DEBUG]: Reading from /etc/ssh/ssh_host_ecdsa_key.pub (quiet=False)
2024-05-09 09:19:08,275 - util.py[DEBUG]: Read 214 bytes from /etc/ssh/ssh_host_ecdsa_key.pub
2024-05-09 09:19:08,275 - util.py[DEBUG]: Reading from /etc/ssh/sshd_config (quiet=False)
2024-05-09 09:19:08,281 - util.py[DEBUG]: Read 3854 bytes from /etc/ssh/sshd_config
2024-05-09 09:19:08,283 - util.py[DEBUG]: Changing the ownership of /home/ec2-user/.ssh to 1000:1000
2024-05-09 09:19:08,284 - util.py[DEBUG]: Restoring selinux mode for /home/ec2-user/.ssh (recursive=False)
2024-05-09 09:19:08,284 - util.py[DEBUG]: Writing to /home/ec2-user/.ssh/authorized_keys - wb: [600] 0 bytes
2024-05-09 09:19:08,285 - util.py[DEBUG]: Restoring selinux mode for /home/ec2-user/.ssh/authorized_keys (recursive=False)
2024-05-09 09:19:08,285 - util.py[DEBUG]: Restoring selinux mode for /home/ec2-user/.ssh/authorized_keys (recursive=False)
2024-05-09 09:19:08,285 - util.py[DEBUG]: Changing the ownership of /home/ec2-user/.ssh/authorized_keys to 1000:1000
2024-05-09 09:19:08,285 - util.py[DEBUG]: Reading from /home/ec2-user/.ssh/authorized_keys (quiet=False)
2024-05-09 09:19:08,286 - util.py[DEBUG]: Read 0 bytes from /home/ec2-user/.ssh/authorized_keys
2024-05-09 09:19:08,286 - util.py[DEBUG]: Writing to /home/ec2-user/.ssh/authorized_keys - wb: [600] 0 bytes
2024-05-09 09:19:08,286 - util.py[DEBUG]: Restoring selinux mode for /home/ec2-user/.ssh/authorized_keys (recursive=False)
2024-05-09 09:19:08,286 - util.py[DEBUG]: Restoring selinux mode for /home/ec2-user/.ssh/authorized_keys (recursive=False)
2024-05-09 09:19:08,287 - util.py[DEBUG]: Restoring selinux mode for /home/ec2-user/.ssh (recursive=True)
2024-05-09 09:19:08,290 - util.py[DEBUG]: Reading from /etc/ssh/sshd_config (quiet=False)
2024-05-09 09:19:08,290 - util.py[DEBUG]: Read 3854 bytes from /etc/ssh/sshd_config
2024-05-09 09:19:08,290 - util.py[DEBUG]: Restoring selinux mode for /root/.ssh (recursive=True)
2024-05-09 09:19:08,303 - util.py[DEBUG]: Writing to /root/.ssh/authorized_keys - wb: [600] 0 bytes
2024-05-09 09:19:08,304 - util.py[DEBUG]: Restoring selinux mode for /root/.ssh/authorized_keys (recursive=False)
2024-05-09 09:19:08,304 - util.py[DEBUG]: Restoring selinux mode for /root/.ssh/authorized_keys (recursive=False)
2024-05-09 09:19:08,305 - util.py[DEBUG]: Changing the ownership of /root/.ssh/authorized_keys to 0:0
2024-05-09 09:19:08,305 - util.py[DEBUG]: Reading from /root/.ssh/authorized_keys (quiet=False)
2024-05-09 09:19:08,305 - util.py[DEBUG]: Read 0 bytes from /root/.ssh/authorized_keys
2024-05-09 09:19:08,306 - util.py[DEBUG]: Writing to /root/.ssh/authorized_keys - wb: [600] 0 bytes
2024-05-09 09:19:08,306 - util.py[DEBUG]: Restoring selinux mode for /root/.ssh/authorized_keys (recursive=False)
2024-05-09 09:19:08,306 - util.py[DEBUG]: Restoring selinux mode for /root/.ssh/authorized_keys (recursive=False)
2024-05-09 09:19:08,306 - util.py[DEBUG]: Restoring selinux mode for /root/.ssh (recursive=True)
2024-05-09 09:19:08,309 - handlers.py[DEBUG]: finish: init-network/config-ssh: SUCCESS: config-ssh ran successfully
2024-05-09 09:19:08,310 - main.py[DEBUG]: Ran 17 modules with 0 failures
2024-05-09 09:19:08,310 - atomic_helper.py[DEBUG]: Atomically writing to file /var/lib/cloud/data/status.json (via temporary file /var/lib/cloud/data/tmpegabyo9r) - w: [644] 486 bytes/chars
2024-05-09 09:19:08,311 - util.py[DEBUG]: Reading from /proc/uptime (quiet=False)
2024-05-09 09:19:08,311 - util.py[DEBUG]: Read 10 bytes from /proc/uptime
2024-05-09 09:19:08,311 - util.py[DEBUG]: cloud-init mode 'init' took 2.301 seconds (2.30)
2024-05-09 09:19:08,311 - handlers.py[DEBUG]: finish: init-network: SUCCESS: searching for network datasources
2024-05-09 09:19:09,526 - util.py[DEBUG]: Cloud-init v. 22.2.2 running 'modules:config' at Thu, 09 May 2024 09:19:09 +0000. Up 9.15 seconds.
2024-05-09 09:19:09,544 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2024-05-09 09:19:09,545 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2024-05-09 09:19:09,552 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2024-05-09 09:19:09,552 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2024-05-09 09:19:09,562 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2024-05-09 09:19:09,562 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2024-05-09 09:19:09,566 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2024-05-09 09:19:09,566 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2024-05-09 09:19:09,572 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2024-05-09 09:19:09,573 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2024-05-09 09:19:09,582 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2024-05-09 09:19:09,582 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2024-05-09 09:19:09,586 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2024-05-09 09:19:09,587 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2024-05-09 09:19:09,602 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2024-05-09 09:19:09,603 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2024-05-09 09:19:09,606 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2024-05-09 09:19:09,606 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2024-05-09 09:19:09,609 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2024-05-09 09:19:09,610 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2024-05-09 09:19:09,612 - stages.py[DEBUG]: Using distro class <class 'cloudinit.distros.amazon.Distro'>
2024-05-09 09:19:09,613 - modules.py[INFO]: Skipping modules 'ssh-import-id' because they are not verified on distro 'amazon'.  To run anyway, add them to 'unverified_modules' in config.
2024-05-09 09:19:09,613 - modules.py[DEBUG]: Running module keyboard (<module 'cloudinit.config.cc_keyboard' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_keyboard.py'>) with frequency once-per-instance
2024-05-09 09:19:09,614 - handlers.py[DEBUG]: start: modules-config/config-keyboard: running config-keyboard with frequency once-per-instance
2024-05-09 09:19:09,614 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-058d20c0b3bfe358b/sem/config_keyboard - wb: [644] 25 bytes
2024-05-09 09:19:09,618 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-058d20c0b3bfe358b/sem/config_keyboard (recursive=False)
2024-05-09 09:19:09,634 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-058d20c0b3bfe358b/sem/config_keyboard (recursive=False)
2024-05-09 09:19:09,635 - helpers.py[DEBUG]: Running config-keyboard using lock (<FileLock using file '/var/lib/cloud/instances/i-058d20c0b3bfe358b/sem/config_keyboard'>)
2024-05-09 09:19:09,636 - cc_keyboard.py[DEBUG]: Skipping module named keyboard, no 'keyboard' section found
2024-05-09 09:19:09,636 - handlers.py[DEBUG]: finish: modules-config/config-keyboard: SUCCESS: config-keyboard ran successfully
2024-05-09 09:19:09,636 - modules.py[DEBUG]: Running module locale (<module 'cloudinit.config.cc_locale' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_locale.py'>) with frequency once-per-instance
2024-05-09 09:19:09,636 - handlers.py[DEBUG]: start: modules-config/config-locale: running config-locale with frequency once-per-instance
2024-05-09 09:19:09,637 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-058d20c0b3bfe358b/sem/config_locale - wb: [644] 24 bytes
2024-05-09 09:19:09,639 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-058d20c0b3bfe358b/sem/config_locale (recursive=False)
2024-05-09 09:19:09,640 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-058d20c0b3bfe358b/sem/config_locale (recursive=False)
2024-05-09 09:19:09,641 - helpers.py[DEBUG]: Running config-locale using lock (<FileLock using file '/var/lib/cloud/instances/i-058d20c0b3bfe358b/sem/config_locale'>)
2024-05-09 09:19:09,641 - util.py[DEBUG]: Reading from /etc/locale.conf (quiet=False)
2024-05-09 09:19:09,641 - util.py[DEBUG]: Read 17 bytes from /etc/locale.conf
2024-05-09 09:19:09,642 - cc_locale.py[DEBUG]: Setting locale to en_US.UTF-8
2024-05-09 09:19:09,642 - util.py[DEBUG]: Reading from /etc/locale.conf (quiet=False)
2024-05-09 09:19:09,642 - util.py[DEBUG]: Read 17 bytes from /etc/locale.conf
2024-05-09 09:19:09,642 - util.py[DEBUG]: Writing to /etc/locale.conf - wb: [644] 17 bytes
2024-05-09 09:19:09,654 - util.py[DEBUG]: Restoring selinux mode for /etc/locale.conf (recursive=False)
2024-05-09 09:19:09,658 - util.py[DEBUG]: Restoring selinux mode for /etc/locale.conf (recursive=False)
2024-05-09 09:19:09,658 - handlers.py[DEBUG]: finish: modules-config/config-locale: SUCCESS: config-locale ran successfully
2024-05-09 09:19:09,658 - modules.py[DEBUG]: Running module set-passwords (<module 'cloudinit.config.cc_set_passwords' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_set_passwords.py'>) with frequency once-per-instance
2024-05-09 09:19:09,659 - handlers.py[DEBUG]: start: modules-config/config-set-passwords: running config-set-passwords with frequency once-per-instance
2024-05-09 09:19:09,659 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-058d20c0b3bfe358b/sem/config_set_passwords - wb: [644] 25 bytes
2024-05-09 09:19:09,660 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-058d20c0b3bfe358b/sem/config_set_passwords (recursive=False)
2024-05-09 09:19:09,661 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-058d20c0b3bfe358b/sem/config_set_passwords (recursive=False)
2024-05-09 09:19:09,670 - helpers.py[DEBUG]: Running config-set-passwords using lock (<FileLock using file '/var/lib/cloud/instances/i-058d20c0b3bfe358b/sem/config_set_passwords'>)
2024-05-09 09:19:09,671 - subp.py[DEBUG]: Running command ['systemctl', 'status', 'sshd'] with allowed return codes [0] (shell=False, capture=True)
2024-05-09 09:19:09,707 - util.py[DEBUG]: Reading from /etc/ssh/sshd_config (quiet=False)
2024-05-09 09:19:09,707 - util.py[DEBUG]: Read 3854 bytes from /etc/ssh/sshd_config
2024-05-09 09:19:09,707 - ssh_util.py[DEBUG]: line 65: option PasswordAuthentication already set to no
2024-05-09 09:19:09,708 - cc_set_passwords.py[DEBUG]: No need to restart SSH service, PasswordAuthentication not updated.
2024-05-09 09:19:09,708 - handlers.py[DEBUG]: finish: modules-config/config-set-passwords: SUCCESS: config-set-passwords ran successfully
2024-05-09 09:19:09,708 - modules.py[DEBUG]: Running module yum-variables (<module 'cloudinit.config.cc_yum_variables' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_yum_variables.py'>) with frequency once-per-instance
2024-05-09 09:19:09,708 - handlers.py[DEBUG]: start: modules-config/config-yum-variables: running config-yum-variables with frequency once-per-instance
2024-05-09 09:19:09,709 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-058d20c0b3bfe358b/sem/config_yum_variables - wb: [644] 24 bytes
2024-05-09 09:19:09,710 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-058d20c0b3bfe358b/sem/config_yum_variables (recursive=False)
2024-05-09 09:19:09,711 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-058d20c0b3bfe358b/sem/config_yum_variables (recursive=False)
2024-05-09 09:19:09,712 - helpers.py[DEBUG]: Running config-yum-variables using lock (<FileLock using file '/var/lib/cloud/instances/i-058d20c0b3bfe358b/sem/config_yum_variables'>)
2024-05-09 09:19:09,712 - cc_yum_variables.py[INFO]: handling yum-variables
2024-05-09 09:19:09,712 - cc_yum_variables.py[INFO]: cfg = {'cloud_final_modules': [['scripts-user', 'always']], 'repo_releasever': 2023.4, 'repo_upgrade': 'none', 'power_state': {'delay': 'now', 'mode': 'reboot', 'message': 'Rebooting machine to apply SELinux kernel commandline setting', 'condition': 'test -f /run/cloud-init-selinux-reboot'}, 'write_metadata': [{'path': '/etc/dnf/vars/awsregion', 'data': [{'identity': 'region'}, 'default']}, {'path': '/etc/dnf/vars/awsdomain', 'data': [{'metadata': 'services/domain'}, 'amazonaws.com']}], '_log': ['[loggers]\nkeys=root,cloudinit\n\n[handlers]\nkeys=consoleHandler,cloudLogHandler\n\n[formatters]\nkeys=simpleFormatter,arg0Formatter\n\n[logger_root]\nlevel=DEBUG\nhandlers=consoleHandler,cloudLogHandler\n\n[logger_cloudinit]\nlevel=DEBUG\nqualname=cloudinit\nhandlers=\npropagate=1\n\n[handler_consoleHandler]\nclass=StreamHandler\nlevel=WARNING\nformatter=arg0Formatter\nargs=(sys.stderr,)\n\n[formatter_arg0Formatter]\nformat=%(asctime)s - %(filename)s[%(levelname)s]: %(message)s\n\n[formatter_simpleFormatter]\nformat=[CLOUDINIT] %(filename)s[%(levelname)s]: %(message)s\n', "[handler_cloudLogHandler]\nclass=FileHandler\nlevel=DEBUG\nformatter=arg0Formatter\nargs=('/var/log/cloud-init.log', 'a', 'UTF-8')\n", '[handler_cloudLogHandler]\nclass=handlers.SysLogHandler\nlevel=DEBUG\nformatter=simpleFormatter\nargs=("/dev/log", handlers.SysLogHandler.LOG_USER)\n'], 'log_cfgs': [['[loggers]\nkeys=root,cloudinit\n\n[handlers]\nkeys=consoleHandler,cloudLogHandler\n\n[formatters]\nkeys=simpleFormatter,arg0Formatter\n\n[logger_root]\nlevel=DEBUG\nhandlers=consoleHandler,cloudLogHandler\n\n[logger_cloudinit]\nlevel=DEBUG\nqualname=cloudinit\nhandlers=\npropagate=1\n\n[handler_consoleHandler]\nclass=StreamHandler\nlevel=WARNING\nformatter=arg0Formatter\nargs=(sys.stderr,)\n\n[formatter_arg0Formatter]\nformat=%(asctime)s - %(filename)s[%(levelname)s]: %(message)s\n\n[formatter_simpleFormatter]\nformat=[CLOUDINIT] %(filename)s[%(levelname)s]: %(message)s\n', "[handler_cloudLogHandler]\nclass=FileHandler\nlevel=DEBUG\nformatter=arg0Formatter\nargs=('/var/log/cloud-init.log', 'a', 'UTF-8')\n"]], 'output': {'all': '| tee -a /var/log/cloud-init-output.log'}, 'network': {'config': 'disabled'}, 'datasource_list': ['Ec2', 'None'], 'datasource': {'Ec2': {'metadata_urls': ['http://169.254.169.254:80', 'http://[fd00:ec2::254]:80'], 'apply_full_imds_network_config': False}}, 'ssh_genkeytypes': ['ed25519', 'ecdsa'], 'users': ['default'], 'disable_root': True, 'mount_default_fields': [None, None, 'auto', 'defaults,nofail', '0', '2'], 'resize_rootfs': 'noblock', 'resize_rootfs_tmp': '/dev', 'ssh_pwauth': False, 'preserve_hostname': False, 'cloud_init_modules': ['migrator', 'seed_random', 'bootcmd', 'write-files', 'write-metadata', 'growpart', 'resizefs', 'disk_setup', 'mounts', 'set_hostname', 'update_hostname', 'update_etc_hosts', 'ca-certs', 'rsyslog', 'selinux', 'users-groups', 'ssh'], 'cloud_config_modules': ['ssh-import-id', 'keyboard', 'locale', 'set-passwords', 'yum-variables', 'yum-add-repo', 'ntp', 'timezone', 'disable-ec2-metadata', 'runcmd'], 'def_log_file': '/var/log/cloud-init.log', 'syslog_fix_perms': ['syslog:adm', 'root:adm', 'root:wheel', 'root:root'], 'vendor_data': {'enabled': True, 'prefix': []}, 'vendor_data2': {'enabled': True, 'prefix': []}}
2024-05-09 09:19:09,712 - cc_yum_variables.py[INFO]: No yum vars to delete
2024-05-09 09:19:09,712 - cc_yum_variables.py[INFO]: No yum vars to set
2024-05-09 09:19:09,712 - handlers.py[DEBUG]: finish: modules-config/config-yum-variables: SUCCESS: config-yum-variables ran successfully
2024-05-09 09:19:09,712 - modules.py[DEBUG]: Running module yum-add-repo (<module 'cloudinit.config.cc_yum_add_repo' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_yum_add_repo.py'>) with frequency once-per-instance
2024-05-09 09:19:09,713 - handlers.py[DEBUG]: start: modules-config/config-yum-add-repo: running config-yum-add-repo with frequency once-per-instance
2024-05-09 09:19:09,713 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-058d20c0b3bfe358b/sem/config_yum_add_repo - wb: [644] 25 bytes
2024-05-09 09:19:09,714 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-058d20c0b3bfe358b/sem/config_yum_add_repo (recursive=False)
2024-05-09 09:19:09,715 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-058d20c0b3bfe358b/sem/config_yum_add_repo (recursive=False)
2024-05-09 09:19:09,716 - helpers.py[DEBUG]: Running config-yum-add-repo using lock (<FileLock using file '/var/lib/cloud/instances/i-058d20c0b3bfe358b/sem/config_yum_add_repo'>)
2024-05-09 09:19:09,716 - cc_yum_add_repo.py[DEBUG]: Skipping module named yum-add-repo, no 'yum_repos' configuration found
2024-05-09 09:19:09,716 - handlers.py[DEBUG]: finish: modules-config/config-yum-add-repo: SUCCESS: config-yum-add-repo ran successfully
2024-05-09 09:19:09,716 - modules.py[DEBUG]: Running module ntp (<module 'cloudinit.config.cc_ntp' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_ntp.py'>) with frequency once-per-instance
2024-05-09 09:19:09,716 - handlers.py[DEBUG]: start: modules-config/config-ntp: running config-ntp with frequency once-per-instance
2024-05-09 09:19:09,716 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-058d20c0b3bfe358b/sem/config_ntp - wb: [644] 23 bytes
2024-05-09 09:19:09,717 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-058d20c0b3bfe358b/sem/config_ntp (recursive=False)
2024-05-09 09:19:09,718 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-058d20c0b3bfe358b/sem/config_ntp (recursive=False)
2024-05-09 09:19:09,719 - helpers.py[DEBUG]: Running config-ntp using lock (<FileLock using file '/var/lib/cloud/instances/i-058d20c0b3bfe358b/sem/config_ntp'>)
2024-05-09 09:19:09,719 - cc_ntp.py[DEBUG]: Skipping module named ntp, not present or disabled by cfg
2024-05-09 09:19:09,719 - handlers.py[DEBUG]: finish: modules-config/config-ntp: SUCCESS: config-ntp ran successfully
2024-05-09 09:19:09,719 - modules.py[DEBUG]: Running module timezone (<module 'cloudinit.config.cc_timezone' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_timezone.py'>) with frequency once-per-instance
2024-05-09 09:19:09,719 - handlers.py[DEBUG]: start: modules-config/config-timezone: running config-timezone with frequency once-per-instance
2024-05-09 09:19:09,719 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-058d20c0b3bfe358b/sem/config_timezone - wb: [644] 25 bytes
2024-05-09 09:19:09,720 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-058d20c0b3bfe358b/sem/config_timezone (recursive=False)
2024-05-09 09:19:09,721 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-058d20c0b3bfe358b/sem/config_timezone (recursive=False)
2024-05-09 09:19:09,742 - helpers.py[DEBUG]: Running config-timezone using lock (<FileLock using file '/var/lib/cloud/instances/i-058d20c0b3bfe358b/sem/config_timezone'>)
2024-05-09 09:19:09,742 - cc_timezone.py[DEBUG]: Skipping module named timezone, no 'timezone' specified
2024-05-09 09:19:09,743 - handlers.py[DEBUG]: finish: modules-config/config-timezone: SUCCESS: config-timezone ran successfully
2024-05-09 09:19:09,743 - modules.py[DEBUG]: Running module disable-ec2-metadata (<module 'cloudinit.config.cc_disable_ec2_metadata' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_disable_ec2_metadata.py'>) with frequency always
2024-05-09 09:19:09,743 - handlers.py[DEBUG]: start: modules-config/config-disable-ec2-metadata: running config-disable-ec2-metadata with frequency always
2024-05-09 09:19:09,743 - helpers.py[DEBUG]: Running config-disable-ec2-metadata using lock (<cloudinit.helpers.DummyLock object at 0x7fa5800d4820>)
2024-05-09 09:19:09,743 - cc_disable_ec2_metadata.py[DEBUG]: Skipping module named disable-ec2-metadata, disabling the ec2 route not enabled
2024-05-09 09:19:09,743 - handlers.py[DEBUG]: finish: modules-config/config-disable-ec2-metadata: SUCCESS: config-disable-ec2-metadata ran successfully
2024-05-09 09:19:09,743 - modules.py[DEBUG]: Running module runcmd (<module 'cloudinit.config.cc_runcmd' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_runcmd.py'>) with frequency once-per-instance
2024-05-09 09:19:09,744 - handlers.py[DEBUG]: start: modules-config/config-runcmd: running config-runcmd with frequency once-per-instance
2024-05-09 09:19:09,744 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-058d20c0b3bfe358b/sem/config_runcmd - wb: [644] 25 bytes
2024-05-09 09:19:09,745 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-058d20c0b3bfe358b/sem/config_runcmd (recursive=False)
2024-05-09 09:19:09,746 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-058d20c0b3bfe358b/sem/config_runcmd (recursive=False)
2024-05-09 09:19:09,747 - helpers.py[DEBUG]: Running config-runcmd using lock (<FileLock using file '/var/lib/cloud/instances/i-058d20c0b3bfe358b/sem/config_runcmd'>)
2024-05-09 09:19:09,747 - cc_runcmd.py[DEBUG]: Skipping module named runcmd, no 'runcmd' key in configuration
2024-05-09 09:19:09,747 - handlers.py[DEBUG]: finish: modules-config/config-runcmd: SUCCESS: config-runcmd ran successfully
2024-05-09 09:19:09,747 - main.py[DEBUG]: Ran 9 modules with 0 failures
2024-05-09 09:19:09,748 - atomic_helper.py[DEBUG]: Atomically writing to file /var/lib/cloud/data/status.json (via temporary file /var/lib/cloud/data/tmptoz9m7sg) - w: [644] 513 bytes/chars
2024-05-09 09:19:09,748 - util.py[DEBUG]: Reading from /proc/uptime (quiet=False)
2024-05-09 09:19:09,748 - util.py[DEBUG]: Read 10 bytes from /proc/uptime
2024-05-09 09:19:09,748 - util.py[DEBUG]: cloud-init mode 'modules' took 0.442 seconds (0.44)
2024-05-09 09:19:09,748 - handlers.py[DEBUG]: finish: modules-config: SUCCESS: running modules for config
2024-05-09 09:19:10,647 - util.py[DEBUG]: Cloud-init v. 22.2.2 running 'modules:final' at Thu, 09 May 2024 09:19:10 +0000. Up 10.27 seconds.
2024-05-09 09:19:10,650 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2024-05-09 09:19:10,650 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2024-05-09 09:19:10,653 - stages.py[DEBUG]: Using distro class <class 'cloudinit.distros.amazon.Distro'>
2024-05-09 09:19:10,654 - modules.py[DEBUG]: Running module scripts-user (<module 'cloudinit.config.cc_scripts_user' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_scripts_user.py'>) with frequency always
2024-05-09 09:19:10,655 - handlers.py[DEBUG]: start: modules-final/config-scripts-user: running config-scripts-user with frequency always
2024-05-09 09:19:10,655 - helpers.py[DEBUG]: Running config-scripts-user using lock (<cloudinit.helpers.DummyLock object at 0x7f48e3b1cf40>)
2024-05-09 09:19:10,655 - subp.py[DEBUG]: Running command ['/var/lib/cloud/instance/scripts/user-data.txt'] with allowed return codes [0] (shell=False, capture=False)
2024-05-09 09:19:52,260 - handlers.py[DEBUG]: finish: modules-final/config-scripts-user: SUCCESS: config-scripts-user ran successfully
2024-05-09 09:19:52,260 - main.py[DEBUG]: Ran 1 modules with 0 failures
2024-05-09 09:19:52,261 - atomic_helper.py[DEBUG]: Atomically writing to file /var/lib/cloud/data/status.json (via temporary file /var/lib/cloud/data/tmpj_7v_1ra) - w: [644] 540 bytes/chars
2024-05-09 09:19:52,262 - atomic_helper.py[DEBUG]: Atomically writing to file /var/lib/cloud/data/result.json (via temporary file /var/lib/cloud/data/tmplqpagtb_) - w: [644] 64 bytes/chars
2024-05-09 09:19:52,262 - util.py[DEBUG]: Creating symbolic link from '/run/cloud-init/result.json' => '../../var/lib/cloud/data/result.json'
2024-05-09 09:19:52,262 - util.py[DEBUG]: Reading from /proc/uptime (quiet=False)
2024-05-09 09:19:52,262 - util.py[DEBUG]: Read 12 bytes from /proc/uptime
2024-05-09 09:19:52,262 - util.py[DEBUG]: cloud-init mode 'modules' took 41.829 seconds (41.20)
2024-05-09 09:19:52,262 - handlers.py[DEBUG]: finish: modules-final: SUCCESS: running modules for final
