May  9 09:19:51 ip-172-31-40-43 web[2016]: [2024-05-09 09:19:51 +0000] [2016] [INFO] Starting gunicorn 22.0.0
May  9 09:19:51 ip-172-31-40-43 web[2016]: [2024-05-09 09:19:51 +0000] [2016] [INFO] Listening at: http://127.0.0.1:8000 (2016)
May  9 09:19:51 ip-172-31-40-43 web[2016]: [2024-05-09 09:19:51 +0000] [2016] [INFO] Using worker: gthread
May  9 09:19:51 ip-172-31-40-43 web[2024]: [2024-05-09 09:19:51 +0000] [2024] [INFO] Booting worker with pid: 2024
May  9 09:23:55 ip-172-31-40-43 web[2016]: [2024-05-09 09:23:55 +0000] [2016] [INFO] Handling signal: term
May  9 09:23:56 ip-172-31-40-43 web[2024]: [2024-05-09 09:23:56 +0000] [2024] [INFO] Worker exiting (pid: 2024)
May  9 09:23:56 ip-172-31-40-43 web[2024]: Program package initialized!
May  9 09:23:56 ip-172-31-40-43 web[2024]: {'TableNames': ['Clients', 'login', 'music'], 'ResponseMetadata': {'RequestId': 'J19KH5ASBJ5GIGSFSS541PR6G3VV4KQNSO5AEMVJF66Q9ASUAAJG', 'HTTPStatusCode': 200, 'HTTPHeaders': {'server': 'Server', 'date': 'Thu, 09 May 2024 09:19:52 GMT', 'content-type': 'application/x-amz-json-1.0', 'content-length': '42', 'connection': 'keep-alive', 'x-amzn-requestid': 'J19KH5ASBJ5GIGSFSS541PR6G3VV4KQNSO5AEMVJF66Q9ASUAAJG', 'x-amz-crc32': '1807579339'}, 'RetryAttempts': 0}}
May  9 09:23:56 ip-172-31-40-43 web[2016]: [2024-05-09 09:23:56 +0000] [2016] [INFO] Shutting down: Master
May  9 09:23:59 ip-172-31-40-43 web[2683]: [2024-05-09 09:23:59 +0000] [2683] [INFO] Starting gunicorn 22.0.0
May  9 09:23:59 ip-172-31-40-43 web[2683]: [2024-05-09 09:23:59 +0000] [2683] [INFO] Listening at: http://127.0.0.1:8000 (2683)
May  9 09:23:59 ip-172-31-40-43 web[2683]: [2024-05-09 09:23:59 +0000] [2683] [INFO] Using worker: gthread
May  9 09:23:59 ip-172-31-40-43 web[2691]: [2024-05-09 09:23:59 +0000] [2691] [INFO] Booting worker with pid: 2691
May  9 09:25:14 ip-172-31-40-43 web[2683]: [2024-05-09 09:25:14 +0000] [2683] [INFO] Handling signal: term
May  9 09:25:14 ip-172-31-40-43 web[2691]: [2024-05-09 09:25:14 +0000] [2691] [INFO] Worker exiting (pid: 2691)
May  9 09:25:14 ip-172-31-40-43 web[2691]: Program package initialized!
May  9 09:25:14 ip-172-31-40-43 web[2691]: {'TableNames': ['Clients', 'login', 'music'], 'ResponseMetadata': {'RequestId': '370SK6P2JRICDKFLCA50GSTTRRVV4KQNSO5AEMVJF66Q9ASUAAJG', 'HTTPStatusCode': 200, 'HTTPHeaders': {'server': 'Server', 'date': 'Thu, 09 May 2024 09:23:59 GMT', 'content-type': 'application/x-amz-json-1.0', 'content-length': '42', 'connection': 'keep-alive', 'x-amzn-requestid': '370SK6P2JRICDKFLCA50GSTTRRVV4KQNSO5AEMVJF66Q9ASUAAJG', 'x-amz-crc32': '1807579339'}, 'RetryAttempts': 0}}
May  9 09:25:14 ip-172-31-40-43 web[2683]: [2024-05-09 09:25:14 +0000] [2683] [INFO] Shutting down: Master
May  9 09:25:16 ip-172-31-40-43 web[3195]: [2024-05-09 09:25:16 +0000] [3195] [INFO] Starting gunicorn 22.0.0
May  9 09:25:16 ip-172-31-40-43 web[3195]: [2024-05-09 09:25:16 +0000] [3195] [INFO] Listening at: http://127.0.0.1:8000 (3195)
May  9 09:25:16 ip-172-31-40-43 web[3195]: [2024-05-09 09:25:16 +0000] [3195] [INFO] Using worker: gthread
May  9 09:25:16 ip-172-31-40-43 web[3204]: [2024-05-09 09:25:16 +0000] [3204] [INFO] Booting worker with pid: 3204
May  9 09:28:27 ip-172-31-40-43 web[3204]: [2024-05-09 09:28:27 +0000] [3204] [ERROR] Error handling request /index
May  9 09:28:27 ip-172-31-40-43 web[3204]: Traceback (most recent call last):
May  9 09:28:27 ip-172-31-40-43 web[3204]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/sqlalchemy/engine/base.py", line 146, in __init__
May  9 09:28:27 ip-172-31-40-43 web[3204]:    self._dbapi_connection = engine.raw_connection()
May  9 09:28:27 ip-172-31-40-43 web[3204]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/sqlalchemy/engine/base.py", line 3304, in raw_connection
May  9 09:28:27 ip-172-31-40-43 web[3204]:    return self.pool.connect()
May  9 09:28:27 ip-172-31-40-43 web[3204]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/sqlalchemy/pool/base.py", line 449, in connect
May  9 09:28:27 ip-172-31-40-43 web[3204]:    return _ConnectionFairy._checkout(self)
May  9 09:28:27 ip-172-31-40-43 web[3204]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/sqlalchemy/pool/base.py", line 1263, in _checkout
May  9 09:28:27 ip-172-31-40-43 web[3204]:    fairy = _ConnectionRecord.checkout(pool)
May  9 09:28:27 ip-172-31-40-43 web[3204]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/sqlalchemy/pool/base.py", line 712, in checkout
May  9 09:28:27 ip-172-31-40-43 web[3204]:    rec = pool._do_get()
May  9 09:28:27 ip-172-31-40-43 web[3204]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/sqlalchemy/pool/impl.py", line 180, in _do_get
May  9 09:28:27 ip-172-31-40-43 web[3204]:    self._dec_overflow()
May  9 09:28:27 ip-172-31-40-43 web[3204]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
May  9 09:28:27 ip-172-31-40-43 web[3204]:    raise exc_value.with_traceback(exc_tb)
May  9 09:28:27 ip-172-31-40-43 web[3204]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/sqlalchemy/pool/impl.py", line 177, in _do_get
May  9 09:28:27 ip-172-31-40-43 web[3204]:    return self._create_connection()
May  9 09:28:27 ip-172-31-40-43 web[3204]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/sqlalchemy/pool/base.py", line 390, in _create_connection
May  9 09:28:27 ip-172-31-40-43 web[3204]:    return _ConnectionRecord(self)
May  9 09:28:27 ip-172-31-40-43 web[3204]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/sqlalchemy/pool/base.py", line 674, in __init__
May  9 09:28:27 ip-172-31-40-43 web[3204]:    self.__connect()
May  9 09:28:27 ip-172-31-40-43 web[3204]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/sqlalchemy/pool/base.py", line 901, in __connect
May  9 09:28:27 ip-172-31-40-43 web[3204]:    pool.logger.debug("Error on connect(): %s", e)
May  9 09:28:27 ip-172-31-40-43 web[3204]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
May  9 09:28:27 ip-172-31-40-43 web[3204]:    raise exc_value.with_traceback(exc_tb)
May  9 09:28:27 ip-172-31-40-43 web[3204]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/sqlalchemy/pool/base.py", line 896, in __connect
May  9 09:28:27 ip-172-31-40-43 web[3204]:    self.dbapi_connection = connection = pool._invoke_creator(self)
May  9 09:28:27 ip-172-31-40-43 web[3204]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/sqlalchemy/engine/create.py", line 643, in connect
May  9 09:28:27 ip-172-31-40-43 web[3204]:    return dialect.connect(*cargs, **cparams)
May  9 09:28:27 ip-172-31-40-43 web[3204]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/sqlalchemy/engine/default.py", line 617, in connect
May  9 09:28:27 ip-172-31-40-43 web[3204]:    return self.loaded_dbapi.connect(*cargs, **cparams)
May  9 09:28:27 ip-172-31-40-43 web[3204]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/psycopg2/__init__.py", line 122, in connect
May  9 09:28:27 ip-172-31-40-43 web[3204]:    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
May  9 09:28:27 ip-172-31-40-43 web[3204]: psycopg2.OperationalError: connection to server at "assignment3.c54y666q6ct9.ap-southeast-2.rds.amazonaws.com" (172.31.13.102), port 5432 failed: Connection timed out
May  9 09:28:27 ip-172-31-40-43 web[3204]: #011Is the server running on that host and accepting TCP/IP connections?
May  9 09:28:27 ip-172-31-40-43 web[3204]: The above exception was the direct cause of the following exception:
May  9 09:28:27 ip-172-31-40-43 web[3204]: Traceback (most recent call last):
May  9 09:28:27 ip-172-31-40-43 web[3204]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/gunicorn/workers/gthread.py", line 282, in handle
May  9 09:28:27 ip-172-31-40-43 web[3204]:    keepalive = self.handle_request(req, conn)
May  9 09:28:27 ip-172-31-40-43 web[3204]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/gunicorn/workers/gthread.py", line 334, in handle_request
May  9 09:28:27 ip-172-31-40-43 web[3204]:    respiter = self.wsgi(environ, resp.start_response)
May  9 09:28:27 ip-172-31-40-43 web[3204]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/flask/app.py", line 1498, in __call__
May  9 09:28:27 ip-172-31-40-43 web[3204]:    return self.wsgi_app(environ, start_response)
May  9 09:28:27 ip-172-31-40-43 web[3204]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/flask/app.py", line 1476, in wsgi_app
May  9 09:28:27 ip-172-31-40-43 web[3204]:    response = self.handle_exception(e)
May  9 09:28:27 ip-172-31-40-43 web[3204]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/flask/app.py", line 1473, in wsgi_app
May  9 09:28:27 ip-172-31-40-43 web[3204]:    response = self.full_dispatch_request()
May  9 09:28:27 ip-172-31-40-43 web[3204]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/flask/app.py", line 882, in full_dispatch_request
May  9 09:28:27 ip-172-31-40-43 web[3204]:    rv = self.handle_user_exception(e)
May  9 09:28:27 ip-172-31-40-43 web[3204]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/flask/app.py", line 880, in full_dispatch_request
May  9 09:28:27 ip-172-31-40-43 web[3204]:    rv = self.dispatch_request()
May  9 09:28:27 ip-172-31-40-43 web[3204]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/flask/app.py", line 865, in dispatch_request
May  9 09:28:27 ip-172-31-40-43 web[3204]:    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
May  9 09:28:27 ip-172-31-40-43 web[3204]:  File "/var/app/current/Program/routes.py", line 51, in index
May  9 09:28:27 ip-172-31-40-43 web[3204]:    products = db_session.query(Product, Inventory.QuantityAvailable).join(Inventory, Product.ProductID == Inventory.ProductID).all()
May  9 09:28:27 ip-172-31-40-43 web[3204]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/sqlalchemy/orm/query.py", line 2673, in all
May  9 09:28:27 ip-172-31-40-43 web[3204]:    return self._iter().all()  # type: ignore
May  9 09:28:27 ip-172-31-40-43 web[3204]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/sqlalchemy/orm/query.py", line 2827, in _iter
May  9 09:28:27 ip-172-31-40-43 web[3204]:    result: Union[ScalarResult[_T], Result[_T]] = self.session.execute(
May  9 09:28:27 ip-172-31-40-43 web[3204]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/sqlalchemy/orm/session.py", line 2306, in execute
May  9 09:28:27 ip-172-31-40-43 web[3204]:    return self._execute_internal(
May  9 09:28:27 ip-172-31-40-43 web[3204]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/sqlalchemy/orm/session.py", line 2181, in _execute_internal
May  9 09:28:27 ip-172-31-40-43 web[3204]:    conn = self._connection_for_bind(bind)
May  9 09:28:27 ip-172-31-40-43 web[3204]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/sqlalchemy/orm/session.py", line 2050, in _connection_for_bind
May  9 09:28:27 ip-172-31-40-43 web[3204]:    return trans._connection_for_bind(engine, execution_options)
May  9 09:28:27 ip-172-31-40-43 web[3204]:  File "<string>", line 2, in _connection_for_bind
May  9 09:28:27 ip-172-31-40-43 web[3204]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
May  9 09:28:27 ip-172-31-40-43 web[3204]:    ret_value = fn(self, *arg, **kw)
May  9 09:28:27 ip-172-31-40-43 web[3204]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/sqlalchemy/orm/session.py", line 1144, in _connection_for_bind
May  9 09:28:27 ip-172-31-40-43 web[3204]:    conn = bind.connect()
May  9 09:28:27 ip-172-31-40-43 web[3204]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/sqlalchemy/engine/base.py", line 3280, in connect
May  9 09:28:27 ip-172-31-40-43 web[3204]:    return self._connection_cls(self)
May  9 09:28:27 ip-172-31-40-43 web[3204]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/sqlalchemy/engine/base.py", line 148, in __init__
May  9 09:28:27 ip-172-31-40-43 web[3204]:    Connection._handle_dbapi_exception_noconnection(
May  9 09:28:27 ip-172-31-40-43 web[3204]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/sqlalchemy/engine/base.py", line 2444, in _handle_dbapi_exception_noconnection
May  9 09:28:27 ip-172-31-40-43 web[3204]:    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
May  9 09:28:27 ip-172-31-40-43 web[3204]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/sqlalchemy/engine/base.py", line 146, in __init__
May  9 09:28:27 ip-172-31-40-43 web[3204]:    self._dbapi_connection = engine.raw_connection()
May  9 09:28:27 ip-172-31-40-43 web[3204]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/sqlalchemy/engine/base.py", line 3304, in raw_connection
May  9 09:28:27 ip-172-31-40-43 web[3204]:    return self.pool.connect()
May  9 09:28:27 ip-172-31-40-43 web[3204]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/sqlalchemy/pool/base.py", line 449, in connect
May  9 09:28:27 ip-172-31-40-43 web[3204]:    return _ConnectionFairy._checkout(self)
May  9 09:28:27 ip-172-31-40-43 web[3204]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/sqlalchemy/pool/base.py", line 1263, in _checkout
May  9 09:28:27 ip-172-31-40-43 web[3204]:    fairy = _ConnectionRecord.checkout(pool)
May  9 09:28:27 ip-172-31-40-43 web[3204]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/sqlalchemy/pool/base.py", line 712, in checkout
May  9 09:28:27 ip-172-31-40-43 web[3204]:    rec = pool._do_get()
May  9 09:28:27 ip-172-31-40-43 web[3204]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/sqlalchemy/pool/impl.py", line 180, in _do_get
May  9 09:28:27 ip-172-31-40-43 web[3204]:    self._dec_overflow()
May  9 09:28:27 ip-172-31-40-43 web[3204]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
May  9 09:28:27 ip-172-31-40-43 web[3204]:    raise exc_value.with_traceback(exc_tb)
May  9 09:28:27 ip-172-31-40-43 web[3204]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/sqlalchemy/pool/impl.py", line 177, in _do_get
May  9 09:28:27 ip-172-31-40-43 web[3204]:    return self._create_connection()
May  9 09:28:27 ip-172-31-40-43 web[3204]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/sqlalchemy/pool/base.py", line 390, in _create_connection
May  9 09:28:27 ip-172-31-40-43 web[3204]:    return _ConnectionRecord(self)
May  9 09:28:27 ip-172-31-40-43 web[3204]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/sqlalchemy/pool/base.py", line 674, in __init__
May  9 09:28:27 ip-172-31-40-43 web[3204]:    self.__connect()
May  9 09:28:27 ip-172-31-40-43 web[3204]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/sqlalchemy/pool/base.py", line 901, in __connect
May  9 09:28:27 ip-172-31-40-43 web[3204]:    pool.logger.debug("Error on connect(): %s", e)
May  9 09:28:27 ip-172-31-40-43 web[3204]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
May  9 09:28:27 ip-172-31-40-43 web[3204]:    raise exc_value.with_traceback(exc_tb)
May  9 09:28:27 ip-172-31-40-43 web[3204]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/sqlalchemy/pool/base.py", line 896, in __connect
May  9 09:28:27 ip-172-31-40-43 web[3204]:    self.dbapi_connection = connection = pool._invoke_creator(self)
May  9 09:28:27 ip-172-31-40-43 web[3204]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/sqlalchemy/engine/create.py", line 643, in connect
May  9 09:28:27 ip-172-31-40-43 web[3204]:    return dialect.connect(*cargs, **cparams)
May  9 09:28:27 ip-172-31-40-43 web[3204]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/sqlalchemy/engine/default.py", line 617, in connect
May  9 09:28:27 ip-172-31-40-43 web[3204]:    return self.loaded_dbapi.connect(*cargs, **cparams)
May  9 09:28:27 ip-172-31-40-43 web[3204]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/psycopg2/__init__.py", line 122, in connect
May  9 09:28:27 ip-172-31-40-43 web[3204]:    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
May  9 09:28:27 ip-172-31-40-43 web[3204]: sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) connection to server at "assignment3.c54y666q6ct9.ap-southeast-2.rds.amazonaws.com" (172.31.13.102), port 5432 failed: Connection timed out
May  9 09:28:27 ip-172-31-40-43 web[3204]: #011Is the server running on that host and accepting TCP/IP connections?
May  9 09:28:27 ip-172-31-40-43 web[3204]: (Background on this error at: https://sqlalche.me/e/20/e3q8)
May  9 09:35:58 ip-172-31-40-43 web[3195]: [2024-05-09 09:35:58 +0000] [3195] [INFO] Handling signal: term
May  9 09:35:59 ip-172-31-40-43 web[3204]: [2024-05-09 09:35:59 +0000] [3204] [INFO] Worker exiting (pid: 3204)
May  9 09:35:59 ip-172-31-40-43 web[3204]: Program package initialized!
May  9 09:35:59 ip-172-31-40-43 web[3204]: {'TableNames': ['Clients', 'login', 'music'], 'ResponseMetadata': {'RequestId': '8L16JE9247QLPT7NNE14EE5PMJVV4KQNSO5AEMVJF66Q9ASUAAJG', 'HTTPStatusCode': 200, 'HTTPHeaders': {'server': 'Server', 'date': 'Thu, 09 May 2024 09:25:17 GMT', 'content-type': 'application/x-amz-json-1.0', 'content-length': '42', 'connection': 'keep-alive', 'x-amzn-requestid': '8L16JE9247QLPT7NNE14EE5PMJVV4KQNSO5AEMVJF66Q9ASUAAJG', 'x-amz-crc32': '1807579339'}, 'RetryAttempts': 0}}
May  9 09:35:59 ip-172-31-40-43 web[3204]: Form validated successfully
May  9 09:35:59 ip-172-31-40-43 web[3195]: [2024-05-09 09:35:59 +0000] [3195] [INFO] Shutting down: Master
May  9 09:36:02 ip-172-31-40-43 web[4087]: [2024-05-09 09:36:02 +0000] [4087] [INFO] Starting gunicorn 22.0.0
May  9 09:36:02 ip-172-31-40-43 web[4087]: [2024-05-09 09:36:02 +0000] [4087] [INFO] Listening at: http://127.0.0.1:8000 (4087)
May  9 09:36:02 ip-172-31-40-43 web[4087]: [2024-05-09 09:36:02 +0000] [4087] [INFO] Using worker: gthread
May  9 09:36:02 ip-172-31-40-43 web[4117]: [2024-05-09 09:36:02 +0000] [4117] [INFO] Booting worker with pid: 4117
May  9 09:43:03 ip-172-31-40-43 web[4087]: [2024-05-09 09:43:03 +0000] [4087] [INFO] Handling signal: term
May  9 09:43:04 ip-172-31-40-43 web[4117]: [2024-05-09 09:43:04 +0000] [4117] [INFO] Worker exiting (pid: 4117)
May  9 09:43:04 ip-172-31-40-43 web[4117]: Program package initialized!
May  9 09:43:04 ip-172-31-40-43 web[4117]: {'TableNames': ['Clients', 'login', 'music'], 'ResponseMetadata': {'RequestId': 'DF7BLS3MGD0A3RQP5MF98G43C3VV4KQNSO5AEMVJF66Q9ASUAAJG', 'HTTPStatusCode': 200, 'HTTPHeaders': {'server': 'Server', 'date': 'Thu, 09 May 2024 09:36:03 GMT', 'content-type': 'application/x-amz-json-1.0', 'content-length': '42', 'connection': 'keep-alive', 'x-amzn-requestid': 'DF7BLS3MGD0A3RQP5MF98G43C3VV4KQNSO5AEMVJF66Q9ASUAAJG', 'x-amz-crc32': '1807579339'}, 'RetryAttempts': 0}}
May  9 09:43:04 ip-172-31-40-43 web[4087]: [2024-05-09 09:43:04 +0000] [4087] [INFO] Shutting down: Master
May  9 09:43:06 ip-172-31-40-43 web[4770]: [2024-05-09 09:43:06 +0000] [4770] [INFO] Starting gunicorn 22.0.0
May  9 09:43:06 ip-172-31-40-43 web[4770]: [2024-05-09 09:43:06 +0000] [4770] [INFO] Listening at: http://127.0.0.1:8000 (4770)
May  9 09:43:06 ip-172-31-40-43 web[4770]: [2024-05-09 09:43:06 +0000] [4770] [INFO] Using worker: gthread
May  9 09:43:06 ip-172-31-40-43 web[4779]: [2024-05-09 09:43:06 +0000] [4779] [INFO] Booting worker with pid: 4779
May  9 09:46:37 ip-172-31-40-43 web[4779]: [2024-05-09 09:46:37 +0000] [4779] [ERROR] Error handling request /index
May  9 09:46:37 ip-172-31-40-43 web[4779]: Traceback (most recent call last):
May  9 09:46:37 ip-172-31-40-43 web[4779]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/sqlalchemy/engine/base.py", line 146, in __init__
May  9 09:46:37 ip-172-31-40-43 web[4779]:    self._dbapi_connection = engine.raw_connection()
May  9 09:46:37 ip-172-31-40-43 web[4779]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/sqlalchemy/engine/base.py", line 3304, in raw_connection
May  9 09:46:37 ip-172-31-40-43 web[4779]:    return self.pool.connect()
May  9 09:46:37 ip-172-31-40-43 web[4779]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/sqlalchemy/pool/base.py", line 449, in connect
May  9 09:46:37 ip-172-31-40-43 web[4779]:    return _ConnectionFairy._checkout(self)
May  9 09:46:37 ip-172-31-40-43 web[4779]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/sqlalchemy/pool/base.py", line 1263, in _checkout
May  9 09:46:37 ip-172-31-40-43 web[4779]:    fairy = _ConnectionRecord.checkout(pool)
May  9 09:46:37 ip-172-31-40-43 web[4779]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/sqlalchemy/pool/base.py", line 712, in checkout
May  9 09:46:37 ip-172-31-40-43 web[4779]:    rec = pool._do_get()
May  9 09:46:37 ip-172-31-40-43 web[4779]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/sqlalchemy/pool/impl.py", line 180, in _do_get
May  9 09:46:37 ip-172-31-40-43 web[4779]:    self._dec_overflow()
May  9 09:46:37 ip-172-31-40-43 web[4779]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
May  9 09:46:37 ip-172-31-40-43 web[4779]:    raise exc_value.with_traceback(exc_tb)
May  9 09:46:37 ip-172-31-40-43 web[4779]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/sqlalchemy/pool/impl.py", line 177, in _do_get
May  9 09:46:37 ip-172-31-40-43 web[4779]:    return self._create_connection()
May  9 09:46:37 ip-172-31-40-43 web[4779]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/sqlalchemy/pool/base.py", line 390, in _create_connection
May  9 09:46:37 ip-172-31-40-43 web[4779]:    return _ConnectionRecord(self)
May  9 09:46:37 ip-172-31-40-43 web[4779]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/sqlalchemy/pool/base.py", line 674, in __init__
May  9 09:46:37 ip-172-31-40-43 web[4779]:    self.__connect()
May  9 09:46:37 ip-172-31-40-43 web[4779]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/sqlalchemy/pool/base.py", line 901, in __connect
May  9 09:46:37 ip-172-31-40-43 web[4779]:    pool.logger.debug("Error on connect(): %s", e)
May  9 09:46:37 ip-172-31-40-43 web[4779]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
May  9 09:46:37 ip-172-31-40-43 web[4779]:    raise exc_value.with_traceback(exc_tb)
May  9 09:46:37 ip-172-31-40-43 web[4779]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/sqlalchemy/pool/base.py", line 896, in __connect
May  9 09:46:37 ip-172-31-40-43 web[4779]:    self.dbapi_connection = connection = pool._invoke_creator(self)
May  9 09:46:37 ip-172-31-40-43 web[4779]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/sqlalchemy/engine/create.py", line 643, in connect
May  9 09:46:37 ip-172-31-40-43 web[4779]:    return dialect.connect(*cargs, **cparams)
May  9 09:46:37 ip-172-31-40-43 web[4779]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/sqlalchemy/engine/default.py", line 617, in connect
May  9 09:46:37 ip-172-31-40-43 web[4779]:    return self.loaded_dbapi.connect(*cargs, **cparams)
May  9 09:46:37 ip-172-31-40-43 web[4779]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/psycopg2/__init__.py", line 122, in connect
May  9 09:46:37 ip-172-31-40-43 web[4779]:    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
May  9 09:46:37 ip-172-31-40-43 web[4779]: psycopg2.OperationalError: connection to server at "assignment3.c54y666q6ct9.ap-southeast-2.rds.amazonaws.com" (172.31.13.102), port 5432 failed: Connection timed out
May  9 09:46:37 ip-172-31-40-43 web[4779]: #011Is the server running on that host and accepting TCP/IP connections?
May  9 09:46:37 ip-172-31-40-43 web[4779]: The above exception was the direct cause of the following exception:
May  9 09:46:37 ip-172-31-40-43 web[4779]: Traceback (most recent call last):
May  9 09:46:37 ip-172-31-40-43 web[4779]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/gunicorn/workers/gthread.py", line 282, in handle
May  9 09:46:37 ip-172-31-40-43 web[4779]:    keepalive = self.handle_request(req, conn)
May  9 09:46:37 ip-172-31-40-43 web[4779]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/gunicorn/workers/gthread.py", line 334, in handle_request
May  9 09:46:37 ip-172-31-40-43 web[4779]:    respiter = self.wsgi(environ, resp.start_response)
May  9 09:46:37 ip-172-31-40-43 web[4779]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/flask/app.py", line 1498, in __call__
May  9 09:46:37 ip-172-31-40-43 web[4779]:    return self.wsgi_app(environ, start_response)
May  9 09:46:37 ip-172-31-40-43 web[4779]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/flask/app.py", line 1476, in wsgi_app
May  9 09:46:37 ip-172-31-40-43 web[4779]:    response = self.handle_exception(e)
May  9 09:46:37 ip-172-31-40-43 web[4779]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/flask/app.py", line 1473, in wsgi_app
May  9 09:46:37 ip-172-31-40-43 web[4779]:    response = self.full_dispatch_request()
May  9 09:46:37 ip-172-31-40-43 web[4779]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/flask/app.py", line 882, in full_dispatch_request
May  9 09:46:37 ip-172-31-40-43 web[4779]:    rv = self.handle_user_exception(e)
May  9 09:46:37 ip-172-31-40-43 web[4779]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/flask/app.py", line 880, in full_dispatch_request
May  9 09:46:37 ip-172-31-40-43 web[4779]:    rv = self.dispatch_request()
May  9 09:46:37 ip-172-31-40-43 web[4779]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/flask/app.py", line 865, in dispatch_request
May  9 09:46:37 ip-172-31-40-43 web[4779]:    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
May  9 09:46:37 ip-172-31-40-43 web[4779]:  File "/var/app/current/Program/routes.py", line 51, in index
May  9 09:46:37 ip-172-31-40-43 web[4779]:    products = db_session.query(Product, Inventory.QuantityAvailable).join(Inventory, Product.ProductID == Inventory.ProductID).all()
May  9 09:46:37 ip-172-31-40-43 web[4779]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/sqlalchemy/orm/query.py", line 2673, in all
May  9 09:46:37 ip-172-31-40-43 web[4779]:    return self._iter().all()  # type: ignore
May  9 09:46:37 ip-172-31-40-43 web[4779]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/sqlalchemy/orm/query.py", line 2827, in _iter
May  9 09:46:37 ip-172-31-40-43 web[4779]:    result: Union[ScalarResult[_T], Result[_T]] = self.session.execute(
May  9 09:46:37 ip-172-31-40-43 web[4779]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/sqlalchemy/orm/session.py", line 2306, in execute
May  9 09:46:37 ip-172-31-40-43 web[4779]:    return self._execute_internal(
May  9 09:46:37 ip-172-31-40-43 web[4779]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/sqlalchemy/orm/session.py", line 2181, in _execute_internal
May  9 09:46:37 ip-172-31-40-43 web[4779]:    conn = self._connection_for_bind(bind)
May  9 09:46:37 ip-172-31-40-43 web[4779]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/sqlalchemy/orm/session.py", line 2050, in _connection_for_bind
May  9 09:46:37 ip-172-31-40-43 web[4779]:    return trans._connection_for_bind(engine, execution_options)
May  9 09:46:37 ip-172-31-40-43 web[4779]:  File "<string>", line 2, in _connection_for_bind
May  9 09:46:37 ip-172-31-40-43 web[4779]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
May  9 09:46:37 ip-172-31-40-43 web[4779]:    ret_value = fn(self, *arg, **kw)
May  9 09:46:37 ip-172-31-40-43 web[4779]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/sqlalchemy/orm/session.py", line 1144, in _connection_for_bind
May  9 09:46:37 ip-172-31-40-43 web[4779]:    conn = bind.connect()
May  9 09:46:37 ip-172-31-40-43 web[4779]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/sqlalchemy/engine/base.py", line 3280, in connect
May  9 09:46:37 ip-172-31-40-43 web[4779]:    return self._connection_cls(self)
May  9 09:46:37 ip-172-31-40-43 web[4779]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/sqlalchemy/engine/base.py", line 148, in __init__
May  9 09:46:37 ip-172-31-40-43 web[4779]:    Connection._handle_dbapi_exception_noconnection(
May  9 09:46:37 ip-172-31-40-43 web[4779]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/sqlalchemy/engine/base.py", line 2444, in _handle_dbapi_exception_noconnection
May  9 09:46:37 ip-172-31-40-43 web[4779]:    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
May  9 09:46:37 ip-172-31-40-43 web[4779]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/sqlalchemy/engine/base.py", line 146, in __init__
May  9 09:46:37 ip-172-31-40-43 web[4779]:    self._dbapi_connection = engine.raw_connection()
May  9 09:46:37 ip-172-31-40-43 web[4779]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/sqlalchemy/engine/base.py", line 3304, in raw_connection
May  9 09:46:37 ip-172-31-40-43 web[4779]:    return self.pool.connect()
May  9 09:46:37 ip-172-31-40-43 web[4779]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/sqlalchemy/pool/base.py", line 449, in connect
May  9 09:46:37 ip-172-31-40-43 web[4779]:    return _ConnectionFairy._checkout(self)
May  9 09:46:37 ip-172-31-40-43 web[4779]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/sqlalchemy/pool/base.py", line 1263, in _checkout
May  9 09:46:37 ip-172-31-40-43 web[4779]:    fairy = _ConnectionRecord.checkout(pool)
May  9 09:46:37 ip-172-31-40-43 web[4779]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/sqlalchemy/pool/base.py", line 712, in checkout
May  9 09:46:37 ip-172-31-40-43 web[4779]:    rec = pool._do_get()
May  9 09:46:37 ip-172-31-40-43 web[4779]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/sqlalchemy/pool/impl.py", line 180, in _do_get
May  9 09:46:37 ip-172-31-40-43 web[4779]:    self._dec_overflow()
May  9 09:46:37 ip-172-31-40-43 web[4779]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
May  9 09:46:37 ip-172-31-40-43 web[4779]:    raise exc_value.with_traceback(exc_tb)
May  9 09:46:37 ip-172-31-40-43 web[4779]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/sqlalchemy/pool/impl.py", line 177, in _do_get
May  9 09:46:37 ip-172-31-40-43 web[4779]:    return self._create_connection()
May  9 09:46:37 ip-172-31-40-43 web[4779]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/sqlalchemy/pool/base.py", line 390, in _create_connection
May  9 09:46:37 ip-172-31-40-43 web[4779]:    return _ConnectionRecord(self)
May  9 09:46:37 ip-172-31-40-43 web[4779]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/sqlalchemy/pool/base.py", line 674, in __init__
May  9 09:46:37 ip-172-31-40-43 web[4779]:    self.__connect()
May  9 09:46:37 ip-172-31-40-43 web[4779]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/sqlalchemy/pool/base.py", line 901, in __connect
May  9 09:46:37 ip-172-31-40-43 web[4779]:    pool.logger.debug("Error on connect(): %s", e)
May  9 09:46:37 ip-172-31-40-43 web[4779]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
May  9 09:46:37 ip-172-31-40-43 web[4779]:    raise exc_value.with_traceback(exc_tb)
May  9 09:46:37 ip-172-31-40-43 web[4779]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/sqlalchemy/pool/base.py", line 896, in __connect
May  9 09:46:37 ip-172-31-40-43 web[4779]:    self.dbapi_connection = connection = pool._invoke_creator(self)
May  9 09:46:37 ip-172-31-40-43 web[4779]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/sqlalchemy/engine/create.py", line 643, in connect
May  9 09:46:37 ip-172-31-40-43 web[4779]:    return dialect.connect(*cargs, **cparams)
May  9 09:46:37 ip-172-31-40-43 web[4779]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/sqlalchemy/engine/default.py", line 617, in connect
May  9 09:46:37 ip-172-31-40-43 web[4779]:    return self.loaded_dbapi.connect(*cargs, **cparams)
May  9 09:46:37 ip-172-31-40-43 web[4779]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/psycopg2/__init__.py", line 122, in connect
May  9 09:46:37 ip-172-31-40-43 web[4779]:    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
May  9 09:46:37 ip-172-31-40-43 web[4779]: sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) connection to server at "assignment3.c54y666q6ct9.ap-southeast-2.rds.amazonaws.com" (172.31.13.102), port 5432 failed: Connection timed out
May  9 09:46:37 ip-172-31-40-43 web[4779]: #011Is the server running on that host and accepting TCP/IP connections?
May  9 09:46:37 ip-172-31-40-43 web[4779]: (Background on this error at: https://sqlalche.me/e/20/e3q8)
May  9 10:01:59 ip-172-31-40-43 web[4770]: [2024-05-09 10:01:59 +0000] [4770] [INFO] Handling signal: term
May  9 10:02:00 ip-172-31-40-43 web[4779]: [2024-05-09 10:02:00 +0000] [4779] [INFO] Worker exiting (pid: 4779)
May  9 10:02:00 ip-172-31-40-43 web[4779]: Program package initialized!
May  9 10:02:00 ip-172-31-40-43 web[4779]: {'TableNames': ['Clients', 'login', 'music'], 'ResponseMetadata': {'RequestId': 'ATLMUFSCSKI7EQ95QION0DT8BRVV4KQNSO5AEMVJF66Q9ASUAAJG', 'HTTPStatusCode': 200, 'HTTPHeaders': {'server': 'Server', 'date': 'Thu, 09 May 2024 09:43:07 GMT', 'content-type': 'application/x-amz-json-1.0', 'content-length': '42', 'connection': 'keep-alive', 'x-amzn-requestid': 'ATLMUFSCSKI7EQ95QION0DT8BRVV4KQNSO5AEMVJF66Q9ASUAAJG', 'x-amz-crc32': '1807579339'}, 'RetryAttempts': 0}}
May  9 10:02:00 ip-172-31-40-43 web[4779]: Form validated successfully
May  9 10:02:00 ip-172-31-40-43 web[4770]: [2024-05-09 10:02:00 +0000] [4770] [INFO] Shutting down: Master
May  9 10:02:03 ip-172-31-40-43 web[5945]: [2024-05-09 10:02:03 +0000] [5945] [INFO] Starting gunicorn 22.0.0
May  9 10:02:03 ip-172-31-40-43 web[5945]: [2024-05-09 10:02:03 +0000] [5945] [INFO] Listening at: http://127.0.0.1:8000 (5945)
May  9 10:02:03 ip-172-31-40-43 web[5945]: [2024-05-09 10:02:03 +0000] [5945] [INFO] Using worker: gthread
May  9 10:02:03 ip-172-31-40-43 web[5967]: [2024-05-09 10:02:03 +0000] [5967] [INFO] Booting worker with pid: 5967
May  9 10:05:08 ip-172-31-40-43 web[5967]: [2024-05-09 10:05:08 +0000] [5967] [ERROR] Socket error processing request.
May  9 10:05:08 ip-172-31-40-43 web[5967]: Traceback (most recent call last):
May  9 10:05:08 ip-172-31-40-43 web[5967]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/sqlalchemy/engine/base.py", line 146, in __init__
May  9 10:05:08 ip-172-31-40-43 web[5967]:    self._dbapi_connection = engine.raw_connection()
May  9 10:05:08 ip-172-31-40-43 web[5967]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/sqlalchemy/engine/base.py", line 3304, in raw_connection
May  9 10:05:08 ip-172-31-40-43 web[5967]:    return self.pool.connect()
May  9 10:05:08 ip-172-31-40-43 web[5967]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/sqlalchemy/pool/base.py", line 449, in connect
May  9 10:05:08 ip-172-31-40-43 web[5967]:    return _ConnectionFairy._checkout(self)
May  9 10:05:08 ip-172-31-40-43 web[5967]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/sqlalchemy/pool/base.py", line 1263, in _checkout
May  9 10:05:08 ip-172-31-40-43 web[5967]:    fairy = _ConnectionRecord.checkout(pool)
May  9 10:05:08 ip-172-31-40-43 web[5967]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/sqlalchemy/pool/base.py", line 712, in checkout
May  9 10:05:08 ip-172-31-40-43 web[5967]:    rec = pool._do_get()
May  9 10:05:08 ip-172-31-40-43 web[5967]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/sqlalchemy/pool/impl.py", line 180, in _do_get
May  9 10:05:08 ip-172-31-40-43 web[5967]:    self._dec_overflow()
May  9 10:05:08 ip-172-31-40-43 web[5967]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
May  9 10:05:08 ip-172-31-40-43 web[5967]:    raise exc_value.with_traceback(exc_tb)
May  9 10:05:08 ip-172-31-40-43 web[5967]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/sqlalchemy/pool/impl.py", line 177, in _do_get
May  9 10:05:08 ip-172-31-40-43 web[5967]:    return self._create_connection()
May  9 10:05:08 ip-172-31-40-43 web[5967]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/sqlalchemy/pool/base.py", line 390, in _create_connection
May  9 10:05:08 ip-172-31-40-43 web[5967]:    return _ConnectionRecord(self)
May  9 10:05:08 ip-172-31-40-43 web[5967]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/sqlalchemy/pool/base.py", line 674, in __init__
May  9 10:05:08 ip-172-31-40-43 web[5967]:    self.__connect()
May  9 10:05:08 ip-172-31-40-43 web[5967]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/sqlalchemy/pool/base.py", line 901, in __connect
May  9 10:05:08 ip-172-31-40-43 web[5967]:    pool.logger.debug("Error on connect(): %s", e)
May  9 10:05:08 ip-172-31-40-43 web[5967]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
May  9 10:05:08 ip-172-31-40-43 web[5967]:    raise exc_value.with_traceback(exc_tb)
May  9 10:05:08 ip-172-31-40-43 web[5967]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/sqlalchemy/pool/base.py", line 896, in __connect
May  9 10:05:08 ip-172-31-40-43 web[5967]:    self.dbapi_connection = connection = pool._invoke_creator(self)
May  9 10:05:08 ip-172-31-40-43 web[5967]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/sqlalchemy/engine/create.py", line 643, in connect
May  9 10:05:08 ip-172-31-40-43 web[5967]:    return dialect.connect(*cargs, **cparams)
May  9 10:05:08 ip-172-31-40-43 web[5967]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/sqlalchemy/engine/default.py", line 617, in connect
May  9 10:05:08 ip-172-31-40-43 web[5967]:    return self.loaded_dbapi.connect(*cargs, **cparams)
May  9 10:05:08 ip-172-31-40-43 web[5967]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/psycopg2/__init__.py", line 122, in connect
May  9 10:05:08 ip-172-31-40-43 web[5967]:    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
May  9 10:05:08 ip-172-31-40-43 web[5967]: psycopg2.OperationalError: connection to server at "assignment3.c54y666q6ct9.ap-southeast-2.rds.amazonaws.com" (172.31.13.102), port 5432 failed: Connection timed out
May  9 10:05:08 ip-172-31-40-43 web[5967]: #011Is the server running on that host and accepting TCP/IP connections?
May  9 10:05:08 ip-172-31-40-43 web[5967]: The above exception was the direct cause of the following exception:
May  9 10:05:08 ip-172-31-40-43 web[5967]: Traceback (most recent call last):
May  9 10:05:08 ip-172-31-40-43 web[5967]:  File "/var/app/current/Program/routes.py", line 54, in index
May  9 10:05:08 ip-172-31-40-43 web[5967]:    products = db_session.query(Product, Inventory.QuantityAvailable).join(Inventory, Product.ProductID == Inventory.ProductID).all()
May  9 10:05:08 ip-172-31-40-43 web[5967]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/sqlalchemy/orm/query.py", line 2673, in all
May  9 10:05:08 ip-172-31-40-43 web[5967]:    return self._iter().all()  # type: ignore
May  9 10:05:08 ip-172-31-40-43 web[5967]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/sqlalchemy/orm/query.py", line 2827, in _iter
May  9 10:05:08 ip-172-31-40-43 web[5967]:    result: Union[ScalarResult[_T], Result[_T]] = self.session.execute(
May  9 10:05:08 ip-172-31-40-43 web[5967]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/sqlalchemy/orm/session.py", line 2306, in execute
May  9 10:05:08 ip-172-31-40-43 web[5967]:    return self._execute_internal(
May  9 10:05:08 ip-172-31-40-43 web[5967]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/sqlalchemy/orm/session.py", line 2181, in _execute_internal
May  9 10:05:08 ip-172-31-40-43 web[5967]:    conn = self._connection_for_bind(bind)
May  9 10:05:08 ip-172-31-40-43 web[5967]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/sqlalchemy/orm/session.py", line 2050, in _connection_for_bind
May  9 10:05:08 ip-172-31-40-43 web[5967]:    return trans._connection_for_bind(engine, execution_options)
May  9 10:05:08 ip-172-31-40-43 web[5967]:  File "<string>", line 2, in _connection_for_bind
May  9 10:05:08 ip-172-31-40-43 web[5967]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
May  9 10:05:08 ip-172-31-40-43 web[5967]:    ret_value = fn(self, *arg, **kw)
May  9 10:05:08 ip-172-31-40-43 web[5967]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/sqlalchemy/orm/session.py", line 1144, in _connection_for_bind
May  9 10:05:08 ip-172-31-40-43 web[5967]:    conn = bind.connect()
May  9 10:05:08 ip-172-31-40-43 web[5967]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/sqlalchemy/engine/base.py", line 3280, in connect
May  9 10:05:08 ip-172-31-40-43 web[5967]:    return self._connection_cls(self)
May  9 10:05:08 ip-172-31-40-43 web[5967]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/sqlalchemy/engine/base.py", line 148, in __init__
May  9 10:05:08 ip-172-31-40-43 web[5967]:    Connection._handle_dbapi_exception_noconnection(
May  9 10:05:08 ip-172-31-40-43 web[5967]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/sqlalchemy/engine/base.py", line 2444, in _handle_dbapi_exception_noconnection
May  9 10:05:08 ip-172-31-40-43 web[5967]:    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
May  9 10:05:08 ip-172-31-40-43 web[5967]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/sqlalchemy/engine/base.py", line 146, in __init__
May  9 10:05:08 ip-172-31-40-43 web[5967]:    self._dbapi_connection = engine.raw_connection()
May  9 10:05:08 ip-172-31-40-43 web[5967]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/sqlalchemy/engine/base.py", line 3304, in raw_connection
May  9 10:05:08 ip-172-31-40-43 web[5967]:    return self.pool.connect()
May  9 10:05:08 ip-172-31-40-43 web[5967]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/sqlalchemy/pool/base.py", line 449, in connect
May  9 10:05:08 ip-172-31-40-43 web[5967]:    return _ConnectionFairy._checkout(self)
May  9 10:05:08 ip-172-31-40-43 web[5967]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/sqlalchemy/pool/base.py", line 1263, in _checkout
May  9 10:05:08 ip-172-31-40-43 web[5967]:    fairy = _ConnectionRecord.checkout(pool)
May  9 10:05:08 ip-172-31-40-43 web[5967]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/sqlalchemy/pool/base.py", line 712, in checkout
May  9 10:05:08 ip-172-31-40-43 web[5967]:    rec = pool._do_get()
May  9 10:05:08 ip-172-31-40-43 web[5967]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/sqlalchemy/pool/impl.py", line 180, in _do_get
May  9 10:05:08 ip-172-31-40-43 web[5967]:    self._dec_overflow()
May  9 10:05:08 ip-172-31-40-43 web[5967]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
May  9 10:05:08 ip-172-31-40-43 web[5967]:    raise exc_value.with_traceback(exc_tb)
May  9 10:05:08 ip-172-31-40-43 web[5967]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/sqlalchemy/pool/impl.py", line 177, in _do_get
May  9 10:05:08 ip-172-31-40-43 web[5967]:    return self._create_connection()
May  9 10:05:08 ip-172-31-40-43 web[5967]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/sqlalchemy/pool/base.py", line 390, in _create_connection
May  9 10:05:08 ip-172-31-40-43 web[5967]:    return _ConnectionRecord(self)
May  9 10:05:08 ip-172-31-40-43 web[5967]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/sqlalchemy/pool/base.py", line 674, in __init__
May  9 10:05:08 ip-172-31-40-43 web[5967]:    self.__connect()
May  9 10:05:08 ip-172-31-40-43 web[5967]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/sqlalchemy/pool/base.py", line 901, in __connect
May  9 10:05:08 ip-172-31-40-43 web[5967]:    pool.logger.debug("Error on connect(): %s", e)
May  9 10:05:08 ip-172-31-40-43 web[5967]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
May  9 10:05:08 ip-172-31-40-43 web[5967]:    raise exc_value.with_traceback(exc_tb)
May  9 10:05:08 ip-172-31-40-43 web[5967]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/sqlalchemy/pool/base.py", line 896, in __connect
May  9 10:05:08 ip-172-31-40-43 web[5967]:    self.dbapi_connection = connection = pool._invoke_creator(self)
May  9 10:05:08 ip-172-31-40-43 web[5967]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/sqlalchemy/engine/create.py", line 643, in connect
May  9 10:05:08 ip-172-31-40-43 web[5967]:    return dialect.connect(*cargs, **cparams)
May  9 10:05:08 ip-172-31-40-43 web[5967]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/sqlalchemy/engine/default.py", line 617, in connect
May  9 10:05:08 ip-172-31-40-43 web[5967]:    return self.loaded_dbapi.connect(*cargs, **cparams)
May  9 10:05:08 ip-172-31-40-43 web[5967]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/psycopg2/__init__.py", line 122, in connect
May  9 10:05:08 ip-172-31-40-43 web[5967]:    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
May  9 10:05:08 ip-172-31-40-43 web[5967]: sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) connection to server at "assignment3.c54y666q6ct9.ap-southeast-2.rds.amazonaws.com" (172.31.13.102), port 5432 failed: Connection timed out
May  9 10:05:08 ip-172-31-40-43 web[5967]: #011Is the server running on that host and accepting TCP/IP connections?
May  9 10:05:08 ip-172-31-40-43 web[5967]: (Background on this error at: https://sqlalche.me/e/20/e3q8)
May  9 10:05:08 ip-172-31-40-43 web[5967]: During handling of the above exception, another exception occurred:
May  9 10:05:08 ip-172-31-40-43 web[5967]: Traceback (most recent call last):
May  9 10:05:08 ip-172-31-40-43 web[5967]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/gunicorn/workers/gthread.py", line 282, in handle
May  9 10:05:08 ip-172-31-40-43 web[5967]:    keepalive = self.handle_request(req, conn)
May  9 10:05:08 ip-172-31-40-43 web[5967]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/gunicorn/workers/gthread.py", line 354, in handle_request
May  9 10:05:08 ip-172-31-40-43 web[5967]:    util.reraise(*sys.exc_info())
May  9 10:05:08 ip-172-31-40-43 web[5967]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/gunicorn/util.py", line 641, in reraise
May  9 10:05:08 ip-172-31-40-43 web[5967]:    raise value
May  9 10:05:08 ip-172-31-40-43 web[5967]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/gunicorn/workers/gthread.py", line 334, in handle_request
May  9 10:05:08 ip-172-31-40-43 web[5967]:    respiter = self.wsgi(environ, resp.start_response)
May  9 10:05:08 ip-172-31-40-43 web[5967]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/flask/app.py", line 1498, in __call__
May  9 10:05:08 ip-172-31-40-43 web[5967]:    return self.wsgi_app(environ, start_response)
May  9 10:05:08 ip-172-31-40-43 web[5967]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/flask/app.py", line 1476, in wsgi_app
May  9 10:05:08 ip-172-31-40-43 web[5967]:    response = self.handle_exception(e)
May  9 10:05:08 ip-172-31-40-43 web[5967]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/flask/app.py", line 1473, in wsgi_app
May  9 10:05:08 ip-172-31-40-43 web[5967]:    response = self.full_dispatch_request()
May  9 10:05:08 ip-172-31-40-43 web[5967]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/flask/app.py", line 882, in full_dispatch_request
May  9 10:05:08 ip-172-31-40-43 web[5967]:    rv = self.handle_user_exception(e)
May  9 10:05:08 ip-172-31-40-43 web[5967]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/flask/app.py", line 880, in full_dispatch_request
May  9 10:05:08 ip-172-31-40-43 web[5967]:    rv = self.dispatch_request()
May  9 10:05:08 ip-172-31-40-43 web[5967]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/flask/app.py", line 865, in dispatch_request
May  9 10:05:08 ip-172-31-40-43 web[5967]:    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
May  9 10:05:08 ip-172-31-40-43 web[5967]:  File "/var/app/current/Program/routes.py", line 63, in index
May  9 10:05:08 ip-172-31-40-43 web[5967]:    return render_template('error.html', error=str(e))
May  9 10:05:08 ip-172-31-40-43 web[5967]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/flask/templating.py", line 149, in render_template
May  9 10:05:08 ip-172-31-40-43 web[5967]:    template = app.jinja_env.get_or_select_template(template_name_or_list)
May  9 10:05:08 ip-172-31-40-43 web[5967]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/jinja2/environment.py", line 1081, in get_or_select_template
May  9 10:05:08 ip-172-31-40-43 web[5967]:    return self.get_template(template_name_or_list, parent, globals)
May  9 10:05:08 ip-172-31-40-43 web[5967]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/jinja2/environment.py", line 1010, in get_template
May  9 10:05:08 ip-172-31-40-43 web[5967]:    return self._load_template(name, globals)
May  9 10:05:08 ip-172-31-40-43 web[5967]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/jinja2/environment.py", line 969, in _load_template
May  9 10:05:08 ip-172-31-40-43 web[5967]:    template = self.loader.load(self, name, self.make_globals(globals))
May  9 10:05:08 ip-172-31-40-43 web[5967]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/jinja2/loaders.py", line 125, in load
May  9 10:05:08 ip-172-31-40-43 web[5967]:    source, filename, uptodate = self.get_source(environment, name)
May  9 10:05:08 ip-172-31-40-43 web[5967]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/flask/templating.py", line 65, in get_source
May  9 10:05:08 ip-172-31-40-43 web[5967]:    return self._get_source_fast(environment, template)
May  9 10:05:08 ip-172-31-40-43 web[5967]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/flask/templating.py", line 99, in _get_source_fast
May  9 10:05:08 ip-172-31-40-43 web[5967]:    raise TemplateNotFound(template)
May  9 10:05:08 ip-172-31-40-43 web[5967]: jinja2.exceptions.TemplateNotFound: error.html
May  9 10:26:23 ip-172-31-40-43 web[5945]: [2024-05-09 10:26:23 +0000] [5945] [INFO] Handling signal: term
May  9 10:26:23 ip-172-31-40-43 web[5967]: [2024-05-09 10:26:23 +0000] [5967] [INFO] Worker exiting (pid: 5967)
May  9 10:26:23 ip-172-31-40-43 web[5967]: Program package initialized!
May  9 10:26:23 ip-172-31-40-43 web[5967]: {'TableNames': ['Clients', 'login', 'music'], 'ResponseMetadata': {'RequestId': 'C467UMFT3NG7JO9839M1PTFCVBVV4KQNSO5AEMVJF66Q9ASUAAJG', 'HTTPStatusCode': 200, 'HTTPHeaders': {'server': 'Server', 'date': 'Thu, 09 May 2024 10:02:04 GMT', 'content-type': 'application/x-amz-json-1.0', 'content-length': '42', 'connection': 'keep-alive', 'x-amzn-requestid': 'C467UMFT3NG7JO9839M1PTFCVBVV4KQNSO5AEMVJF66Q9ASUAAJG', 'x-amz-crc32': '1807579339'}, 'RetryAttempts': 0}}
May  9 10:26:23 ip-172-31-40-43 web[5967]: Form validated successfully
May  9 10:26:23 ip-172-31-40-43 web[5967]: Form validated successfully
May  9 10:26:23 ip-172-31-40-43 web[5967]: Error: (psycopg2.OperationalError) connection to server at "assignment3.c54y666q6ct9.ap-southeast-2.rds.amazonaws.com" (172.31.13.102), port 5432 failed: Connection timed out
May  9 10:26:23 ip-172-31-40-43 web[5967]: #011Is the server running on that host and accepting TCP/IP connections?
May  9 10:26:23 ip-172-31-40-43 web[5967]: (Background on this error at: https://sqlalche.me/e/20/e3q8)
May  9 10:26:23 ip-172-31-40-43 web[5967]: Form validation failed: {'email': ['This field is required.'], 'password': ['This field is required.'], 'csrf_token': ['The CSRF token is missing.']}
May  9 10:26:24 ip-172-31-40-43 web[5945]: [2024-05-09 10:26:24 +0000] [5945] [INFO] Shutting down: Master
May  9 10:26:25 ip-172-31-40-43 web[7245]: [2024-05-09 10:26:25 +0000] [7245] [INFO] Starting gunicorn 22.0.0
May  9 10:26:25 ip-172-31-40-43 web[7245]: [2024-05-09 10:26:25 +0000] [7245] [INFO] Listening at: http://127.0.0.1:8000 (7245)
May  9 10:26:25 ip-172-31-40-43 web[7245]: [2024-05-09 10:26:25 +0000] [7245] [INFO] Using worker: gthread
May  9 10:26:25 ip-172-31-40-43 web[7253]: [2024-05-09 10:26:25 +0000] [7253] [INFO] Booting worker with pid: 7253
May  9 10:30:19 ip-172-31-40-43 web[7245]: [2024-05-09 10:30:19 +0000] [7245] [INFO] Handling signal: term
May  9 10:30:19 ip-172-31-40-43 web[7253]: [2024-05-09 10:30:19 +0000] [7253] [INFO] Worker exiting (pid: 7253)
May  9 10:30:19 ip-172-31-40-43 web[7253]: Program package initialized!
May  9 10:30:19 ip-172-31-40-43 web[7253]: {'TableNames': ['Clients', 'login', 'music'], 'ResponseMetadata': {'RequestId': '1G5IQJALCJNL4HD85U5KHB7F1RVV4KQNSO5AEMVJF66Q9ASUAAJG', 'HTTPStatusCode': 200, 'HTTPHeaders': {'server': 'Server', 'date': 'Thu, 09 May 2024 10:26:26 GMT', 'content-type': 'application/x-amz-json-1.0', 'content-length': '42', 'connection': 'keep-alive', 'x-amzn-requestid': '1G5IQJALCJNL4HD85U5KHB7F1RVV4KQNSO5AEMVJF66Q9ASUAAJG', 'x-amz-crc32': '1807579339'}, 'RetryAttempts': 0}}
May  9 10:30:19 ip-172-31-40-43 web[7245]: [2024-05-09 10:30:19 +0000] [7245] [INFO] Shutting down: Master
May  9 10:30:21 ip-172-31-40-43 web[7822]: [2024-05-09 10:30:21 +0000] [7822] [INFO] Starting gunicorn 22.0.0
May  9 10:30:21 ip-172-31-40-43 web[7822]: [2024-05-09 10:30:21 +0000] [7822] [INFO] Listening at: http://127.0.0.1:8000 (7822)
May  9 10:30:21 ip-172-31-40-43 web[7822]: [2024-05-09 10:30:21 +0000] [7822] [INFO] Using worker: gthread
May  9 10:30:21 ip-172-31-40-43 web[7830]: [2024-05-09 10:30:21 +0000] [7830] [INFO] Booting worker with pid: 7830
May  9 10:33:23 ip-172-31-40-43 web[7830]: [2024-05-09 10:33:23 +0000] [7830] [ERROR] Socket error processing request.
May  9 10:33:23 ip-172-31-40-43 web[7830]: Traceback (most recent call last):
May  9 10:33:23 ip-172-31-40-43 web[7830]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/sqlalchemy/engine/base.py", line 146, in __init__
May  9 10:33:23 ip-172-31-40-43 web[7830]:    self._dbapi_connection = engine.raw_connection()
May  9 10:33:23 ip-172-31-40-43 web[7830]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/sqlalchemy/engine/base.py", line 3304, in raw_connection
May  9 10:33:23 ip-172-31-40-43 web[7830]:    return self.pool.connect()
May  9 10:33:23 ip-172-31-40-43 web[7830]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/sqlalchemy/pool/base.py", line 449, in connect
May  9 10:33:23 ip-172-31-40-43 web[7830]:    return _ConnectionFairy._checkout(self)
May  9 10:33:23 ip-172-31-40-43 web[7830]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/sqlalchemy/pool/base.py", line 1263, in _checkout
May  9 10:33:23 ip-172-31-40-43 web[7830]:    fairy = _ConnectionRecord.checkout(pool)
May  9 10:33:23 ip-172-31-40-43 web[7830]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/sqlalchemy/pool/base.py", line 712, in checkout
May  9 10:33:23 ip-172-31-40-43 web[7830]:    rec = pool._do_get()
May  9 10:33:23 ip-172-31-40-43 web[7830]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/sqlalchemy/pool/impl.py", line 180, in _do_get
May  9 10:33:23 ip-172-31-40-43 web[7830]:    self._dec_overflow()
May  9 10:33:23 ip-172-31-40-43 web[7830]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
May  9 10:33:23 ip-172-31-40-43 web[7830]:    raise exc_value.with_traceback(exc_tb)
May  9 10:33:23 ip-172-31-40-43 web[7830]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/sqlalchemy/pool/impl.py", line 177, in _do_get
May  9 10:33:23 ip-172-31-40-43 web[7830]:    return self._create_connection()
May  9 10:33:23 ip-172-31-40-43 web[7830]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/sqlalchemy/pool/base.py", line 390, in _create_connection
May  9 10:33:23 ip-172-31-40-43 web[7830]:    return _ConnectionRecord(self)
May  9 10:33:23 ip-172-31-40-43 web[7830]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/sqlalchemy/pool/base.py", line 674, in __init__
May  9 10:33:23 ip-172-31-40-43 web[7830]:    self.__connect()
May  9 10:33:23 ip-172-31-40-43 web[7830]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/sqlalchemy/pool/base.py", line 901, in __connect
May  9 10:33:23 ip-172-31-40-43 web[7830]:    pool.logger.debug("Error on connect(): %s", e)
May  9 10:33:23 ip-172-31-40-43 web[7830]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
May  9 10:33:23 ip-172-31-40-43 web[7830]:    raise exc_value.with_traceback(exc_tb)
May  9 10:33:23 ip-172-31-40-43 web[7830]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/sqlalchemy/pool/base.py", line 896, in __connect
May  9 10:33:23 ip-172-31-40-43 web[7830]:    self.dbapi_connection = connection = pool._invoke_creator(self)
May  9 10:33:23 ip-172-31-40-43 web[7830]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/sqlalchemy/engine/create.py", line 643, in connect
May  9 10:33:23 ip-172-31-40-43 web[7830]:    return dialect.connect(*cargs, **cparams)
May  9 10:33:23 ip-172-31-40-43 web[7830]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/sqlalchemy/engine/default.py", line 617, in connect
May  9 10:33:23 ip-172-31-40-43 web[7830]:    return self.loaded_dbapi.connect(*cargs, **cparams)
May  9 10:33:23 ip-172-31-40-43 web[7830]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/psycopg2/__init__.py", line 122, in connect
May  9 10:33:23 ip-172-31-40-43 web[7830]:    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
May  9 10:33:23 ip-172-31-40-43 web[7830]: psycopg2.OperationalError: connection to server at "assignment3.c54y666q6ct9.ap-southeast-2.rds.amazonaws.com" (172.31.13.102), port 5432 failed: Connection timed out
May  9 10:33:23 ip-172-31-40-43 web[7830]: #011Is the server running on that host and accepting TCP/IP connections?
May  9 10:33:23 ip-172-31-40-43 web[7830]: The above exception was the direct cause of the following exception:
May  9 10:33:23 ip-172-31-40-43 web[7830]: Traceback (most recent call last):
May  9 10:33:23 ip-172-31-40-43 web[7830]:  File "/var/app/current/Program/routes.py", line 54, in index
May  9 10:33:23 ip-172-31-40-43 web[7830]:    products = db_session.query(Product, Inventory.QuantityAvailable).join(Inventory, Product.ProductID == Inventory.ProductID).all()
May  9 10:33:23 ip-172-31-40-43 web[7830]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/sqlalchemy/orm/query.py", line 2673, in all
May  9 10:33:23 ip-172-31-40-43 web[7830]:    return self._iter().all()  # type: ignore
May  9 10:33:23 ip-172-31-40-43 web[7830]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/sqlalchemy/orm/query.py", line 2827, in _iter
May  9 10:33:23 ip-172-31-40-43 web[7830]:    result: Union[ScalarResult[_T], Result[_T]] = self.session.execute(
May  9 10:33:23 ip-172-31-40-43 web[7830]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/sqlalchemy/orm/session.py", line 2306, in execute
May  9 10:33:23 ip-172-31-40-43 web[7830]:    return self._execute_internal(
May  9 10:33:23 ip-172-31-40-43 web[7830]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/sqlalchemy/orm/session.py", line 2181, in _execute_internal
May  9 10:33:23 ip-172-31-40-43 web[7830]:    conn = self._connection_for_bind(bind)
May  9 10:33:23 ip-172-31-40-43 web[7830]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/sqlalchemy/orm/session.py", line 2050, in _connection_for_bind
May  9 10:33:23 ip-172-31-40-43 web[7830]:    return trans._connection_for_bind(engine, execution_options)
May  9 10:33:23 ip-172-31-40-43 web[7830]:  File "<string>", line 2, in _connection_for_bind
May  9 10:33:23 ip-172-31-40-43 web[7830]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
May  9 10:33:23 ip-172-31-40-43 web[7830]:    ret_value = fn(self, *arg, **kw)
May  9 10:33:23 ip-172-31-40-43 web[7830]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/sqlalchemy/orm/session.py", line 1144, in _connection_for_bind
May  9 10:33:23 ip-172-31-40-43 web[7830]:    conn = bind.connect()
May  9 10:33:23 ip-172-31-40-43 web[7830]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/sqlalchemy/engine/base.py", line 3280, in connect
May  9 10:33:23 ip-172-31-40-43 web[7830]:    return self._connection_cls(self)
May  9 10:33:23 ip-172-31-40-43 web[7830]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/sqlalchemy/engine/base.py", line 148, in __init__
May  9 10:33:23 ip-172-31-40-43 web[7830]:    Connection._handle_dbapi_exception_noconnection(
May  9 10:33:23 ip-172-31-40-43 web[7830]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/sqlalchemy/engine/base.py", line 2444, in _handle_dbapi_exception_noconnection
May  9 10:33:23 ip-172-31-40-43 web[7830]:    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
May  9 10:33:23 ip-172-31-40-43 web[7830]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/sqlalchemy/engine/base.py", line 146, in __init__
May  9 10:33:23 ip-172-31-40-43 web[7830]:    self._dbapi_connection = engine.raw_connection()
May  9 10:33:23 ip-172-31-40-43 web[7830]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/sqlalchemy/engine/base.py", line 3304, in raw_connection
May  9 10:33:23 ip-172-31-40-43 web[7830]:    return self.pool.connect()
May  9 10:33:23 ip-172-31-40-43 web[7830]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/sqlalchemy/pool/base.py", line 449, in connect
May  9 10:33:23 ip-172-31-40-43 web[7830]:    return _ConnectionFairy._checkout(self)
May  9 10:33:23 ip-172-31-40-43 web[7830]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/sqlalchemy/pool/base.py", line 1263, in _checkout
May  9 10:33:23 ip-172-31-40-43 web[7830]:    fairy = _ConnectionRecord.checkout(pool)
May  9 10:33:23 ip-172-31-40-43 web[7830]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/sqlalchemy/pool/base.py", line 712, in checkout
May  9 10:33:23 ip-172-31-40-43 web[7830]:    rec = pool._do_get()
May  9 10:33:23 ip-172-31-40-43 web[7830]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/sqlalchemy/pool/impl.py", line 180, in _do_get
May  9 10:33:23 ip-172-31-40-43 web[7830]:    self._dec_overflow()
May  9 10:33:23 ip-172-31-40-43 web[7830]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
May  9 10:33:23 ip-172-31-40-43 web[7830]:    raise exc_value.with_traceback(exc_tb)
May  9 10:33:23 ip-172-31-40-43 web[7830]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/sqlalchemy/pool/impl.py", line 177, in _do_get
May  9 10:33:23 ip-172-31-40-43 web[7830]:    return self._create_connection()
May  9 10:33:23 ip-172-31-40-43 web[7830]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/sqlalchemy/pool/base.py", line 390, in _create_connection
May  9 10:33:23 ip-172-31-40-43 web[7830]:    return _ConnectionRecord(self)
May  9 10:33:23 ip-172-31-40-43 web[7830]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/sqlalchemy/pool/base.py", line 674, in __init__
May  9 10:33:23 ip-172-31-40-43 web[7830]:    self.__connect()
May  9 10:33:23 ip-172-31-40-43 web[7830]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/sqlalchemy/pool/base.py", line 901, in __connect
May  9 10:33:23 ip-172-31-40-43 web[7830]:    pool.logger.debug("Error on connect(): %s", e)
May  9 10:33:23 ip-172-31-40-43 web[7830]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
May  9 10:33:23 ip-172-31-40-43 web[7830]:    raise exc_value.with_traceback(exc_tb)
May  9 10:33:23 ip-172-31-40-43 web[7830]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/sqlalchemy/pool/base.py", line 896, in __connect
May  9 10:33:23 ip-172-31-40-43 web[7830]:    self.dbapi_connection = connection = pool._invoke_creator(self)
May  9 10:33:23 ip-172-31-40-43 web[7830]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/sqlalchemy/engine/create.py", line 643, in connect
May  9 10:33:23 ip-172-31-40-43 web[7830]:    return dialect.connect(*cargs, **cparams)
May  9 10:33:23 ip-172-31-40-43 web[7830]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/sqlalchemy/engine/default.py", line 617, in connect
May  9 10:33:23 ip-172-31-40-43 web[7830]:    return self.loaded_dbapi.connect(*cargs, **cparams)
May  9 10:33:23 ip-172-31-40-43 web[7830]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/psycopg2/__init__.py", line 122, in connect
May  9 10:33:23 ip-172-31-40-43 web[7830]:    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
May  9 10:33:23 ip-172-31-40-43 web[7830]: sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) connection to server at "assignment3.c54y666q6ct9.ap-southeast-2.rds.amazonaws.com" (172.31.13.102), port 5432 failed: Connection timed out
May  9 10:33:23 ip-172-31-40-43 web[7830]: #011Is the server running on that host and accepting TCP/IP connections?
May  9 10:33:23 ip-172-31-40-43 web[7830]: (Background on this error at: https://sqlalche.me/e/20/e3q8)
May  9 10:33:23 ip-172-31-40-43 web[7830]: During handling of the above exception, another exception occurred:
May  9 10:33:23 ip-172-31-40-43 web[7830]: Traceback (most recent call last):
May  9 10:33:23 ip-172-31-40-43 web[7830]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/gunicorn/workers/gthread.py", line 282, in handle
May  9 10:33:23 ip-172-31-40-43 web[7830]:    keepalive = self.handle_request(req, conn)
May  9 10:33:23 ip-172-31-40-43 web[7830]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/gunicorn/workers/gthread.py", line 354, in handle_request
May  9 10:33:23 ip-172-31-40-43 web[7830]:    util.reraise(*sys.exc_info())
May  9 10:33:23 ip-172-31-40-43 web[7830]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/gunicorn/util.py", line 641, in reraise
May  9 10:33:23 ip-172-31-40-43 web[7830]:    raise value
May  9 10:33:23 ip-172-31-40-43 web[7830]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/gunicorn/workers/gthread.py", line 334, in handle_request
May  9 10:33:23 ip-172-31-40-43 web[7830]:    respiter = self.wsgi(environ, resp.start_response)
May  9 10:33:23 ip-172-31-40-43 web[7830]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/flask/app.py", line 1498, in __call__
May  9 10:33:23 ip-172-31-40-43 web[7830]:    return self.wsgi_app(environ, start_response)
May  9 10:33:23 ip-172-31-40-43 web[7830]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/flask/app.py", line 1476, in wsgi_app
May  9 10:33:23 ip-172-31-40-43 web[7830]:    response = self.handle_exception(e)
May  9 10:33:23 ip-172-31-40-43 web[7830]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/flask/app.py", line 1473, in wsgi_app
May  9 10:33:23 ip-172-31-40-43 web[7830]:    response = self.full_dispatch_request()
May  9 10:33:23 ip-172-31-40-43 web[7830]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/flask/app.py", line 882, in full_dispatch_request
May  9 10:33:23 ip-172-31-40-43 web[7830]:    rv = self.handle_user_exception(e)
May  9 10:33:23 ip-172-31-40-43 web[7830]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/flask/app.py", line 880, in full_dispatch_request
May  9 10:33:23 ip-172-31-40-43 web[7830]:    rv = self.dispatch_request()
May  9 10:33:23 ip-172-31-40-43 web[7830]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/flask/app.py", line 865, in dispatch_request
May  9 10:33:23 ip-172-31-40-43 web[7830]:    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
May  9 10:33:23 ip-172-31-40-43 web[7830]:  File "/var/app/current/Program/routes.py", line 63, in index
May  9 10:33:23 ip-172-31-40-43 web[7830]:    return render_template('error.html', error=str(e))
May  9 10:33:23 ip-172-31-40-43 web[7830]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/flask/templating.py", line 149, in render_template
May  9 10:33:23 ip-172-31-40-43 web[7830]:    template = app.jinja_env.get_or_select_template(template_name_or_list)
May  9 10:33:23 ip-172-31-40-43 web[7830]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/jinja2/environment.py", line 1081, in get_or_select_template
May  9 10:33:23 ip-172-31-40-43 web[7830]:    return self.get_template(template_name_or_list, parent, globals)
May  9 10:33:23 ip-172-31-40-43 web[7830]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/jinja2/environment.py", line 1010, in get_template
May  9 10:33:23 ip-172-31-40-43 web[7830]:    return self._load_template(name, globals)
May  9 10:33:23 ip-172-31-40-43 web[7830]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/jinja2/environment.py", line 969, in _load_template
May  9 10:33:23 ip-172-31-40-43 web[7830]:    template = self.loader.load(self, name, self.make_globals(globals))
May  9 10:33:23 ip-172-31-40-43 web[7830]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/jinja2/loaders.py", line 125, in load
May  9 10:33:23 ip-172-31-40-43 web[7830]:    source, filename, uptodate = self.get_source(environment, name)
May  9 10:33:23 ip-172-31-40-43 web[7830]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/flask/templating.py", line 65, in get_source
May  9 10:33:23 ip-172-31-40-43 web[7830]:    return self._get_source_fast(environment, template)
May  9 10:33:23 ip-172-31-40-43 web[7830]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/flask/templating.py", line 99, in _get_source_fast
May  9 10:33:23 ip-172-31-40-43 web[7830]:    raise TemplateNotFound(template)
May  9 10:33:23 ip-172-31-40-43 web[7830]: jinja2.exceptions.TemplateNotFound: error.html
May  9 10:57:18 ip-172-31-40-43 web[7822]: [2024-05-09 10:57:18 +0000] [7822] [INFO] Handling signal: term
May  9 10:57:18 ip-172-31-40-43 web[7830]: [2024-05-09 10:57:18 +0000] [7830] [INFO] Worker exiting (pid: 7830)
May  9 10:57:18 ip-172-31-40-43 web[7830]: Program package initialized!
May  9 10:57:18 ip-172-31-40-43 web[7830]: {'TableNames': ['Clients', 'login', 'music'], 'ResponseMetadata': {'RequestId': 'KO4PKEAO6PUA1EUT1J3NUPV62NVV4KQNSO5AEMVJF66Q9ASUAAJG', 'HTTPStatusCode': 200, 'HTTPHeaders': {'server': 'Server', 'date': 'Thu, 09 May 2024 10:30:22 GMT', 'content-type': 'application/x-amz-json-1.0', 'content-length': '42', 'connection': 'keep-alive', 'x-amzn-requestid': 'KO4PKEAO6PUA1EUT1J3NUPV62NVV4KQNSO5AEMVJF66Q9ASUAAJG', 'x-amz-crc32': '1807579339'}, 'RetryAttempts': 0}}
May  9 10:57:18 ip-172-31-40-43 web[7830]: Form validated successfully
May  9 10:57:18 ip-172-31-40-43 web[7830]: Error: (psycopg2.OperationalError) connection to server at "assignment3.c54y666q6ct9.ap-southeast-2.rds.amazonaws.com" (172.31.13.102), port 5432 failed: Connection timed out
May  9 10:57:18 ip-172-31-40-43 web[7830]: #011Is the server running on that host and accepting TCP/IP connections?
May  9 10:57:18 ip-172-31-40-43 web[7830]: (Background on this error at: https://sqlalche.me/e/20/e3q8)
May  9 10:57:18 ip-172-31-40-43 web[7830]: Form validation failed: {'email': ['This field is required.'], 'password': ['This field is required.'], 'csrf_token': ['The CSRF token is missing.']}
May  9 10:57:18 ip-172-31-40-43 web[7830]: Form validation failed: {'email': ['This field is required.'], 'password': ['This field is required.'], 'csrf_token': ['The CSRF token is missing.']}
May  9 10:57:18 ip-172-31-40-43 web[7830]: Form validated successfully
May  9 10:57:18 ip-172-31-40-43 web[7830]: Form validated successfully
May  9 10:57:19 ip-172-31-40-43 web[7822]: [2024-05-09 10:57:19 +0000] [7822] [INFO] Shutting down: Master
May  9 10:57:21 ip-172-31-40-43 web[9133]: [2024-05-09 10:57:21 +0000] [9133] [INFO] Starting gunicorn 22.0.0
May  9 10:57:21 ip-172-31-40-43 web[9133]: [2024-05-09 10:57:21 +0000] [9133] [INFO] Listening at: http://127.0.0.1:8000 (9133)
May  9 10:57:21 ip-172-31-40-43 web[9133]: [2024-05-09 10:57:21 +0000] [9133] [INFO] Using worker: gthread
May  9 10:57:21 ip-172-31-40-43 web[9141]: [2024-05-09 10:57:21 +0000] [9141] [INFO] Booting worker with pid: 9141
May  9 10:57:52 ip-172-31-40-43 web[9141]: [2024-05-09 10:57:52 +0000] [9141] [ERROR] Socket error processing request.
May  9 10:57:52 ip-172-31-40-43 web[9141]: Traceback (most recent call last):
May  9 10:57:52 ip-172-31-40-43 web[9141]:  File "/var/app/current/Program/routes.py", line 58, in index
May  9 10:57:52 ip-172-31-40-43 web[9141]:    return render_template('index.html', user_data=user_data, products=products)
May  9 10:57:52 ip-172-31-40-43 web[9141]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/flask/templating.py", line 150, in render_template
May  9 10:57:52 ip-172-31-40-43 web[9141]:    return _render(app, template, context)
May  9 10:57:52 ip-172-31-40-43 web[9141]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/flask/templating.py", line 131, in _render
May  9 10:57:52 ip-172-31-40-43 web[9141]:    rv = template.render(context)
May  9 10:57:52 ip-172-31-40-43 web[9141]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/jinja2/environment.py", line 1301, in render
May  9 10:57:52 ip-172-31-40-43 web[9141]:    self.environment.handle_exception()
May  9 10:57:52 ip-172-31-40-43 web[9141]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/jinja2/environment.py", line 936, in handle_exception
May  9 10:57:52 ip-172-31-40-43 web[9141]:    raise rewrite_traceback_stack(source=source)
May  9 10:57:52 ip-172-31-40-43 web[9141]:  File "/var/app/current/Program/templates/index.html", line 27, in top-level template code
May  9 10:57:52 ip-172-31-40-43 web[9141]:    <button onclick="location.href='{{ url_for('order_page') }}'">Order</button>
May  9 10:57:52 ip-172-31-40-43 web[9141]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/flask/app.py", line 1084, in url_for
May  9 10:57:52 ip-172-31-40-43 web[9141]:    return self.handle_url_build_error(error, endpoint, values)
May  9 10:57:52 ip-172-31-40-43 web[9141]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/flask/app.py", line 1073, in url_for
May  9 10:57:52 ip-172-31-40-43 web[9141]:    rv = url_adapter.build(  # type: ignore[union-attr]
May  9 10:57:52 ip-172-31-40-43 web[9141]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/werkzeug/routing/map.py", line 926, in build
May  9 10:57:52 ip-172-31-40-43 web[9141]:    raise BuildError(endpoint, values, method, self)
May  9 10:57:52 ip-172-31-40-43 web[9141]: werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'order_page'. Did you mean 'main.register' instead?
May  9 10:57:52 ip-172-31-40-43 web[9141]: During handling of the above exception, another exception occurred:
May  9 10:57:52 ip-172-31-40-43 web[9141]: Traceback (most recent call last):
May  9 10:57:52 ip-172-31-40-43 web[9141]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/gunicorn/workers/gthread.py", line 282, in handle
May  9 10:57:52 ip-172-31-40-43 web[9141]:    keepalive = self.handle_request(req, conn)
May  9 10:57:52 ip-172-31-40-43 web[9141]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/gunicorn/workers/gthread.py", line 354, in handle_request
May  9 10:57:52 ip-172-31-40-43 web[9141]:    util.reraise(*sys.exc_info())
May  9 10:57:52 ip-172-31-40-43 web[9141]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/gunicorn/util.py", line 641, in reraise
May  9 10:57:52 ip-172-31-40-43 web[9141]:    raise value
May  9 10:57:52 ip-172-31-40-43 web[9141]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/gunicorn/workers/gthread.py", line 334, in handle_request
May  9 10:57:52 ip-172-31-40-43 web[9141]:    respiter = self.wsgi(environ, resp.start_response)
May  9 10:57:52 ip-172-31-40-43 web[9141]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/flask/app.py", line 1498, in __call__
May  9 10:57:52 ip-172-31-40-43 web[9141]:    return self.wsgi_app(environ, start_response)
May  9 10:57:52 ip-172-31-40-43 web[9141]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/flask/app.py", line 1476, in wsgi_app
May  9 10:57:52 ip-172-31-40-43 web[9141]:    response = self.handle_exception(e)
May  9 10:57:52 ip-172-31-40-43 web[9141]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/flask/app.py", line 1473, in wsgi_app
May  9 10:57:52 ip-172-31-40-43 web[9141]:    response = self.full_dispatch_request()
May  9 10:57:52 ip-172-31-40-43 web[9141]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/flask/app.py", line 882, in full_dispatch_request
May  9 10:57:52 ip-172-31-40-43 web[9141]:    rv = self.handle_user_exception(e)
May  9 10:57:52 ip-172-31-40-43 web[9141]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/flask/app.py", line 880, in full_dispatch_request
May  9 10:57:52 ip-172-31-40-43 web[9141]:    rv = self.dispatch_request()
May  9 10:57:52 ip-172-31-40-43 web[9141]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/flask/app.py", line 865, in dispatch_request
May  9 10:57:52 ip-172-31-40-43 web[9141]:    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
May  9 10:57:52 ip-172-31-40-43 web[9141]:  File "/var/app/current/Program/routes.py", line 63, in index
May  9 10:57:52 ip-172-31-40-43 web[9141]:    return render_template('error.html', error=str(e))
May  9 10:57:52 ip-172-31-40-43 web[9141]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/flask/templating.py", line 149, in render_template
May  9 10:57:52 ip-172-31-40-43 web[9141]:    template = app.jinja_env.get_or_select_template(template_name_or_list)
May  9 10:57:52 ip-172-31-40-43 web[9141]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/jinja2/environment.py", line 1081, in get_or_select_template
May  9 10:57:52 ip-172-31-40-43 web[9141]:    return self.get_template(template_name_or_list, parent, globals)
May  9 10:57:52 ip-172-31-40-43 web[9141]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/jinja2/environment.py", line 1010, in get_template
May  9 10:57:52 ip-172-31-40-43 web[9141]:    return self._load_template(name, globals)
May  9 10:57:52 ip-172-31-40-43 web[9141]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/jinja2/environment.py", line 969, in _load_template
May  9 10:57:52 ip-172-31-40-43 web[9141]:    template = self.loader.load(self, name, self.make_globals(globals))
May  9 10:57:52 ip-172-31-40-43 web[9141]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/jinja2/loaders.py", line 125, in load
May  9 10:57:52 ip-172-31-40-43 web[9141]:    source, filename, uptodate = self.get_source(environment, name)
May  9 10:57:52 ip-172-31-40-43 web[9141]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/flask/templating.py", line 65, in get_source
May  9 10:57:52 ip-172-31-40-43 web[9141]:    return self._get_source_fast(environment, template)
May  9 10:57:52 ip-172-31-40-43 web[9141]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/flask/templating.py", line 99, in _get_source_fast
May  9 10:57:52 ip-172-31-40-43 web[9141]:    raise TemplateNotFound(template)
May  9 10:57:52 ip-172-31-40-43 web[9141]: jinja2.exceptions.TemplateNotFound: error.html
May  9 10:57:58 ip-172-31-40-43 web[9141]: [2024-05-09 10:57:58 +0000] [9141] [ERROR] Socket error processing request.
May  9 10:57:58 ip-172-31-40-43 web[9141]: Traceback (most recent call last):
May  9 10:57:58 ip-172-31-40-43 web[9141]:  File "/var/app/current/Program/routes.py", line 58, in index
May  9 10:57:58 ip-172-31-40-43 web[9141]:    return render_template('index.html', user_data=user_data, products=products)
May  9 10:57:58 ip-172-31-40-43 web[9141]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/flask/templating.py", line 150, in render_template
May  9 10:57:58 ip-172-31-40-43 web[9141]:    return _render(app, template, context)
May  9 10:57:58 ip-172-31-40-43 web[9141]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/flask/templating.py", line 131, in _render
May  9 10:57:58 ip-172-31-40-43 web[9141]:    rv = template.render(context)
May  9 10:57:58 ip-172-31-40-43 web[9141]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/jinja2/environment.py", line 1301, in render
May  9 10:57:58 ip-172-31-40-43 web[9141]:    self.environment.handle_exception()
May  9 10:57:58 ip-172-31-40-43 web[9141]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/jinja2/environment.py", line 936, in handle_exception
May  9 10:57:58 ip-172-31-40-43 web[9141]:    raise rewrite_traceback_stack(source=source)
May  9 10:57:58 ip-172-31-40-43 web[9141]:  File "/var/app/current/Program/templates/index.html", line 27, in top-level template code
May  9 10:57:58 ip-172-31-40-43 web[9141]:    <button onclick="location.href='{{ url_for('order_page') }}'">Order</button>
May  9 10:57:58 ip-172-31-40-43 web[9141]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/flask/app.py", line 1084, in url_for
May  9 10:57:58 ip-172-31-40-43 web[9141]:    return self.handle_url_build_error(error, endpoint, values)
May  9 10:57:58 ip-172-31-40-43 web[9141]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/flask/app.py", line 1073, in url_for
May  9 10:57:58 ip-172-31-40-43 web[9141]:    rv = url_adapter.build(  # type: ignore[union-attr]
May  9 10:57:58 ip-172-31-40-43 web[9141]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/werkzeug/routing/map.py", line 926, in build
May  9 10:57:58 ip-172-31-40-43 web[9141]:    raise BuildError(endpoint, values, method, self)
May  9 10:57:58 ip-172-31-40-43 web[9141]: werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'order_page'. Did you mean 'main.register' instead?
May  9 10:57:58 ip-172-31-40-43 web[9141]: During handling of the above exception, another exception occurred:
May  9 10:57:58 ip-172-31-40-43 web[9141]: Traceback (most recent call last):
May  9 10:57:58 ip-172-31-40-43 web[9141]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/gunicorn/workers/gthread.py", line 282, in handle
May  9 10:57:58 ip-172-31-40-43 web[9141]:    keepalive = self.handle_request(req, conn)
May  9 10:57:58 ip-172-31-40-43 web[9141]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/gunicorn/workers/gthread.py", line 354, in handle_request
May  9 10:57:58 ip-172-31-40-43 web[9141]:    util.reraise(*sys.exc_info())
May  9 10:57:58 ip-172-31-40-43 web[9141]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/gunicorn/util.py", line 641, in reraise
May  9 10:57:58 ip-172-31-40-43 web[9141]:    raise value
May  9 10:57:58 ip-172-31-40-43 web[9141]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/gunicorn/workers/gthread.py", line 334, in handle_request
May  9 10:57:58 ip-172-31-40-43 web[9141]:    respiter = self.wsgi(environ, resp.start_response)
May  9 10:57:58 ip-172-31-40-43 web[9141]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/flask/app.py", line 1498, in __call__
May  9 10:57:58 ip-172-31-40-43 web[9141]:    return self.wsgi_app(environ, start_response)
May  9 10:57:58 ip-172-31-40-43 web[9141]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/flask/app.py", line 1476, in wsgi_app
May  9 10:57:58 ip-172-31-40-43 web[9141]:    response = self.handle_exception(e)
May  9 10:57:58 ip-172-31-40-43 web[9141]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/flask/app.py", line 1473, in wsgi_app
May  9 10:57:58 ip-172-31-40-43 web[9141]:    response = self.full_dispatch_request()
May  9 10:57:58 ip-172-31-40-43 web[9141]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/flask/app.py", line 882, in full_dispatch_request
May  9 10:57:58 ip-172-31-40-43 web[9141]:    rv = self.handle_user_exception(e)
May  9 10:57:58 ip-172-31-40-43 web[9141]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/flask/app.py", line 880, in full_dispatch_request
May  9 10:57:58 ip-172-31-40-43 web[9141]:    rv = self.dispatch_request()
May  9 10:57:58 ip-172-31-40-43 web[9141]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/flask/app.py", line 865, in dispatch_request
May  9 10:57:58 ip-172-31-40-43 web[9141]:    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
May  9 10:57:58 ip-172-31-40-43 web[9141]:  File "/var/app/current/Program/routes.py", line 63, in index
May  9 10:57:58 ip-172-31-40-43 web[9141]:    return render_template('error.html', error=str(e))
May  9 10:57:58 ip-172-31-40-43 web[9141]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/flask/templating.py", line 149, in render_template
May  9 10:57:58 ip-172-31-40-43 web[9141]:    template = app.jinja_env.get_or_select_template(template_name_or_list)
May  9 10:57:58 ip-172-31-40-43 web[9141]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/jinja2/environment.py", line 1081, in get_or_select_template
May  9 10:57:58 ip-172-31-40-43 web[9141]:    return self.get_template(template_name_or_list, parent, globals)
May  9 10:57:58 ip-172-31-40-43 web[9141]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/jinja2/environment.py", line 1010, in get_template
May  9 10:57:58 ip-172-31-40-43 web[9141]:    return self._load_template(name, globals)
May  9 10:57:58 ip-172-31-40-43 web[9141]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/jinja2/environment.py", line 969, in _load_template
May  9 10:57:58 ip-172-31-40-43 web[9141]:    template = self.loader.load(self, name, self.make_globals(globals))
May  9 10:57:58 ip-172-31-40-43 web[9141]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/jinja2/loaders.py", line 125, in load
May  9 10:57:58 ip-172-31-40-43 web[9141]:    source, filename, uptodate = self.get_source(environment, name)
May  9 10:57:58 ip-172-31-40-43 web[9141]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/flask/templating.py", line 65, in get_source
May  9 10:57:58 ip-172-31-40-43 web[9141]:    return self._get_source_fast(environment, template)
May  9 10:57:58 ip-172-31-40-43 web[9141]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/flask/templating.py", line 99, in _get_source_fast
May  9 10:57:58 ip-172-31-40-43 web[9141]:    raise TemplateNotFound(template)
May  9 10:57:58 ip-172-31-40-43 web[9141]: jinja2.exceptions.TemplateNotFound: error.html
May  9 10:58:46 ip-172-31-40-43 web[9141]: [2024-05-09 10:58:46 +0000] [9141] [ERROR] Socket error processing request.
May  9 10:58:46 ip-172-31-40-43 web[9141]: Traceback (most recent call last):
May  9 10:58:46 ip-172-31-40-43 web[9141]:  File "/var/app/current/Program/routes.py", line 58, in index
May  9 10:58:46 ip-172-31-40-43 web[9141]:    return render_template('index.html', user_data=user_data, products=products)
May  9 10:58:46 ip-172-31-40-43 web[9141]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/flask/templating.py", line 150, in render_template
May  9 10:58:46 ip-172-31-40-43 web[9141]:    return _render(app, template, context)
May  9 10:58:46 ip-172-31-40-43 web[9141]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/flask/templating.py", line 131, in _render
May  9 10:58:46 ip-172-31-40-43 web[9141]:    rv = template.render(context)
May  9 10:58:46 ip-172-31-40-43 web[9141]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/jinja2/environment.py", line 1301, in render
May  9 10:58:46 ip-172-31-40-43 web[9141]:    self.environment.handle_exception()
May  9 10:58:46 ip-172-31-40-43 web[9141]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/jinja2/environment.py", line 936, in handle_exception
May  9 10:58:46 ip-172-31-40-43 web[9141]:    raise rewrite_traceback_stack(source=source)
May  9 10:58:46 ip-172-31-40-43 web[9141]:  File "/var/app/current/Program/templates/index.html", line 27, in top-level template code
May  9 10:58:46 ip-172-31-40-43 web[9141]:    <button onclick="location.href='{{ url_for('order_page') }}'">Order</button>
May  9 10:58:46 ip-172-31-40-43 web[9141]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/flask/app.py", line 1084, in url_for
May  9 10:58:46 ip-172-31-40-43 web[9141]:    return self.handle_url_build_error(error, endpoint, values)
May  9 10:58:46 ip-172-31-40-43 web[9141]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/flask/app.py", line 1073, in url_for
May  9 10:58:46 ip-172-31-40-43 web[9141]:    rv = url_adapter.build(  # type: ignore[union-attr]
May  9 10:58:46 ip-172-31-40-43 web[9141]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/werkzeug/routing/map.py", line 926, in build
May  9 10:58:46 ip-172-31-40-43 web[9141]:    raise BuildError(endpoint, values, method, self)
May  9 10:58:46 ip-172-31-40-43 web[9141]: werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'order_page'. Did you mean 'main.register' instead?
May  9 10:58:46 ip-172-31-40-43 web[9141]: During handling of the above exception, another exception occurred:
May  9 10:58:46 ip-172-31-40-43 web[9141]: Traceback (most recent call last):
May  9 10:58:46 ip-172-31-40-43 web[9141]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/gunicorn/workers/gthread.py", line 282, in handle
May  9 10:58:46 ip-172-31-40-43 web[9141]:    keepalive = self.handle_request(req, conn)
May  9 10:58:46 ip-172-31-40-43 web[9141]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/gunicorn/workers/gthread.py", line 354, in handle_request
May  9 10:58:46 ip-172-31-40-43 web[9141]:    util.reraise(*sys.exc_info())
May  9 10:58:46 ip-172-31-40-43 web[9141]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/gunicorn/util.py", line 641, in reraise
May  9 10:58:46 ip-172-31-40-43 web[9141]:    raise value
May  9 10:58:46 ip-172-31-40-43 web[9141]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/gunicorn/workers/gthread.py", line 334, in handle_request
May  9 10:58:46 ip-172-31-40-43 web[9141]:    respiter = self.wsgi(environ, resp.start_response)
May  9 10:58:46 ip-172-31-40-43 web[9141]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/flask/app.py", line 1498, in __call__
May  9 10:58:46 ip-172-31-40-43 web[9141]:    return self.wsgi_app(environ, start_response)
May  9 10:58:46 ip-172-31-40-43 web[9141]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/flask/app.py", line 1476, in wsgi_app
May  9 10:58:46 ip-172-31-40-43 web[9141]:    response = self.handle_exception(e)
May  9 10:58:46 ip-172-31-40-43 web[9141]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/flask/app.py", line 1473, in wsgi_app
May  9 10:58:46 ip-172-31-40-43 web[9141]:    response = self.full_dispatch_request()
May  9 10:58:46 ip-172-31-40-43 web[9141]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/flask/app.py", line 882, in full_dispatch_request
May  9 10:58:46 ip-172-31-40-43 web[9141]:    rv = self.handle_user_exception(e)
May  9 10:58:46 ip-172-31-40-43 web[9141]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/flask/app.py", line 880, in full_dispatch_request
May  9 10:58:46 ip-172-31-40-43 web[9141]:    rv = self.dispatch_request()
May  9 10:58:46 ip-172-31-40-43 web[9141]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/flask/app.py", line 865, in dispatch_request
May  9 10:58:46 ip-172-31-40-43 web[9141]:    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
May  9 10:58:46 ip-172-31-40-43 web[9141]:  File "/var/app/current/Program/routes.py", line 63, in index
May  9 10:58:46 ip-172-31-40-43 web[9141]:    return render_template('error.html', error=str(e))
May  9 10:58:46 ip-172-31-40-43 web[9141]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/flask/templating.py", line 149, in render_template
May  9 10:58:46 ip-172-31-40-43 web[9141]:    template = app.jinja_env.get_or_select_template(template_name_or_list)
May  9 10:58:46 ip-172-31-40-43 web[9141]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/jinja2/environment.py", line 1081, in get_or_select_template
May  9 10:58:46 ip-172-31-40-43 web[9141]:    return self.get_template(template_name_or_list, parent, globals)
May  9 10:58:46 ip-172-31-40-43 web[9141]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/jinja2/environment.py", line 1010, in get_template
May  9 10:58:46 ip-172-31-40-43 web[9141]:    return self._load_template(name, globals)
May  9 10:58:46 ip-172-31-40-43 web[9141]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/jinja2/environment.py", line 969, in _load_template
May  9 10:58:46 ip-172-31-40-43 web[9141]:    template = self.loader.load(self, name, self.make_globals(globals))
May  9 10:58:46 ip-172-31-40-43 web[9141]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/jinja2/loaders.py", line 125, in load
May  9 10:58:46 ip-172-31-40-43 web[9141]:    source, filename, uptodate = self.get_source(environment, name)
May  9 10:58:46 ip-172-31-40-43 web[9141]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/flask/templating.py", line 65, in get_source
May  9 10:58:46 ip-172-31-40-43 web[9141]:    return self._get_source_fast(environment, template)
May  9 10:58:46 ip-172-31-40-43 web[9141]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/flask/templating.py", line 99, in _get_source_fast
May  9 10:58:46 ip-172-31-40-43 web[9141]:    raise TemplateNotFound(template)
May  9 10:58:46 ip-172-31-40-43 web[9141]: jinja2.exceptions.TemplateNotFound: error.html
May  9 11:00:07 ip-172-31-40-43 web[9133]: [2024-05-09 11:00:07 +0000] [9133] [INFO] Handling signal: term
May  9 11:00:07 ip-172-31-40-43 web[9141]: [2024-05-09 11:00:07 +0000] [9141] [INFO] Worker exiting (pid: 9141)
May  9 11:00:07 ip-172-31-40-43 web[9141]: Program package initialized!
May  9 11:00:07 ip-172-31-40-43 web[9141]: {'TableNames': ['Clients', 'login', 'music'], 'ResponseMetadata': {'RequestId': 'JTOGUPHTO3KF0OE2EGQ34SDDTBVV4KQNSO5AEMVJF66Q9ASUAAJG', 'HTTPStatusCode': 200, 'HTTPHeaders': {'server': 'Server', 'date': 'Thu, 09 May 2024 10:57:22 GMT', 'content-type': 'application/x-amz-json-1.0', 'content-length': '42', 'connection': 'keep-alive', 'x-amzn-requestid': 'JTOGUPHTO3KF0OE2EGQ34SDDTBVV4KQNSO5AEMVJF66Q9ASUAAJG', 'x-amz-crc32': '1807579339'}, 'RetryAttempts': 0}}
May  9 11:00:07 ip-172-31-40-43 web[9141]: Form validated successfully
May  9 11:00:07 ip-172-31-40-43 web[9141]: Error: Could not build url for endpoint 'order_page'. Did you mean 'main.register' instead?
May  9 11:00:07 ip-172-31-40-43 web[9141]: Form validated successfully
May  9 11:00:07 ip-172-31-40-43 web[9141]: Error: Could not build url for endpoint 'order_page'. Did you mean 'main.register' instead?
May  9 11:00:07 ip-172-31-40-43 web[9141]: Form validated successfully
May  9 11:00:07 ip-172-31-40-43 web[9141]: Error: Could not build url for endpoint 'order_page'. Did you mean 'main.register' instead?
May  9 11:00:07 ip-172-31-40-43 web[9141]: Form validation failed: {'email': ['This field is required.'], 'password': ['This field is required.'], 'csrf_token': ['The CSRF token is missing.']}
May  9 11:00:08 ip-172-31-40-43 web[9133]: [2024-05-09 11:00:08 +0000] [9133] [INFO] Shutting down: Master
May  9 11:00:10 ip-172-31-40-43 web[9691]: [2024-05-09 11:00:10 +0000] [9691] [INFO] Starting gunicorn 22.0.0
May  9 11:00:10 ip-172-31-40-43 web[9691]: [2024-05-09 11:00:10 +0000] [9691] [INFO] Listening at: http://127.0.0.1:8000 (9691)
May  9 11:00:10 ip-172-31-40-43 web[9691]: [2024-05-09 11:00:10 +0000] [9691] [INFO] Using worker: gthread
May  9 11:00:10 ip-172-31-40-43 web[9699]: [2024-05-09 11:00:10 +0000] [9699] [INFO] Booting worker with pid: 9699
May  9 11:02:17 ip-172-31-40-43 web[9691]: [2024-05-09 11:02:17 +0000] [9691] [INFO] Handling signal: term
May  9 11:02:17 ip-172-31-40-43 web[9699]: [2024-05-09 11:02:17 +0000] [9699] [INFO] Worker exiting (pid: 9699)
May  9 11:02:17 ip-172-31-40-43 web[9699]: Program package initialized!
May  9 11:02:17 ip-172-31-40-43 web[9699]: {'TableNames': ['Clients', 'login', 'music'], 'ResponseMetadata': {'RequestId': '0JR5KS32IJ6519E8M36QSDGRR3VV4KQNSO5AEMVJF66Q9ASUAAJG', 'HTTPStatusCode': 200, 'HTTPHeaders': {'server': 'Server', 'date': 'Thu, 09 May 2024 11:00:11 GMT', 'content-type': 'application/x-amz-json-1.0', 'content-length': '42', 'connection': 'keep-alive', 'x-amzn-requestid': '0JR5KS32IJ6519E8M36QSDGRR3VV4KQNSO5AEMVJF66Q9ASUAAJG', 'x-amz-crc32': '1807579339'}, 'RetryAttempts': 0}}
May  9 11:02:17 ip-172-31-40-43 web[9699]: Form validated successfully
May  9 11:02:17 ip-172-31-40-43 web[9691]: [2024-05-09 11:02:17 +0000] [9691] [INFO] Shutting down: Master
May  9 11:02:19 ip-172-31-40-43 web[10308]: [2024-05-09 11:02:19 +0000] [10308] [INFO] Starting gunicorn 22.0.0
May  9 11:02:19 ip-172-31-40-43 web[10308]: [2024-05-09 11:02:19 +0000] [10308] [INFO] Listening at: http://127.0.0.1:8000 (10308)
May  9 11:02:19 ip-172-31-40-43 web[10308]: [2024-05-09 11:02:19 +0000] [10308] [INFO] Using worker: gthread
May  9 11:02:19 ip-172-31-40-43 web[10316]: [2024-05-09 11:02:19 +0000] [10316] [INFO] Booting worker with pid: 10316
May  9 11:08:55 ip-172-31-40-43 web[10308]: [2024-05-09 11:08:55 +0000] [10308] [INFO] Handling signal: term
May  9 11:08:56 ip-172-31-40-43 web[10316]: [2024-05-09 11:08:56 +0000] [10316] [INFO] Worker exiting (pid: 10316)
May  9 11:08:56 ip-172-31-40-43 web[10316]: Program package initialized!
May  9 11:08:56 ip-172-31-40-43 web[10316]: {'TableNames': ['Clients', 'login', 'music'], 'ResponseMetadata': {'RequestId': 'RM1GPJVQ1SEBKQALG0RM59F31JVV4KQNSO5AEMVJF66Q9ASUAAJG', 'HTTPStatusCode': 200, 'HTTPHeaders': {'server': 'Server', 'date': 'Thu, 09 May 2024 11:02:20 GMT', 'content-type': 'application/x-amz-json-1.0', 'content-length': '42', 'connection': 'keep-alive', 'x-amzn-requestid': 'RM1GPJVQ1SEBKQALG0RM59F31JVV4KQNSO5AEMVJF66Q9ASUAAJG', 'x-amz-crc32': '1807579339'}, 'RetryAttempts': 0}}
May  9 11:08:56 ip-172-31-40-43 web[10308]: [2024-05-09 11:08:56 +0000] [10308] [INFO] Shutting down: Master
May  9 11:08:58 ip-172-31-40-43 web[10990]: [2024-05-09 11:08:58 +0000] [10990] [INFO] Starting gunicorn 22.0.0
May  9 11:08:58 ip-172-31-40-43 web[10990]: [2024-05-09 11:08:58 +0000] [10990] [INFO] Listening at: http://127.0.0.1:8000 (10990)
May  9 11:08:58 ip-172-31-40-43 web[10990]: [2024-05-09 11:08:58 +0000] [10990] [INFO] Using worker: gthread
May  9 11:08:58 ip-172-31-40-43 web[10998]: [2024-05-09 11:08:58 +0000] [10998] [INFO] Booting worker with pid: 10998
May  9 11:09:16 ip-172-31-40-43 web[10998]: [2024-05-09 11:09:16 +0000] [10998] [ERROR] Socket error processing request.
May  9 11:09:16 ip-172-31-40-43 web[10998]: Traceback (most recent call last):
May  9 11:09:16 ip-172-31-40-43 web[10998]:  File "/var/app/current/Program/routes.py", line 58, in index
May  9 11:09:16 ip-172-31-40-43 web[10998]:    return render_template('index.html', user_data=user_data, products=products)
May  9 11:09:16 ip-172-31-40-43 web[10998]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/flask/templating.py", line 150, in render_template
May  9 11:09:16 ip-172-31-40-43 web[10998]:    return _render(app, template, context)
May  9 11:09:16 ip-172-31-40-43 web[10998]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/flask/templating.py", line 131, in _render
May  9 11:09:16 ip-172-31-40-43 web[10998]:    rv = template.render(context)
May  9 11:09:16 ip-172-31-40-43 web[10998]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/jinja2/environment.py", line 1301, in render
May  9 11:09:16 ip-172-31-40-43 web[10998]:    self.environment.handle_exception()
May  9 11:09:16 ip-172-31-40-43 web[10998]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/jinja2/environment.py", line 936, in handle_exception
May  9 11:09:16 ip-172-31-40-43 web[10998]:    raise rewrite_traceback_stack(source=source)
May  9 11:09:16 ip-172-31-40-43 web[10998]:  File "/var/app/current/Program/templates/index.html", line 27, in top-level template code
May  9 11:09:16 ip-172-31-40-43 web[10998]:    <button onclick="location.href='{{ url_for('place_order') }}'">Order</button>
May  9 11:09:16 ip-172-31-40-43 web[10998]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/flask/app.py", line 1084, in url_for
May  9 11:09:16 ip-172-31-40-43 web[10998]:    return self.handle_url_build_error(error, endpoint, values)
May  9 11:09:16 ip-172-31-40-43 web[10998]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/flask/app.py", line 1073, in url_for
May  9 11:09:16 ip-172-31-40-43 web[10998]:    rv = url_adapter.build(  # type: ignore[union-attr]
May  9 11:09:16 ip-172-31-40-43 web[10998]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/werkzeug/routing/map.py", line 926, in build
May  9 11:09:16 ip-172-31-40-43 web[10998]:    raise BuildError(endpoint, values, method, self)
May  9 11:09:16 ip-172-31-40-43 web[10998]: werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'place_order'. Did you mean 'main.register' instead?
May  9 11:09:16 ip-172-31-40-43 web[10998]: During handling of the above exception, another exception occurred:
May  9 11:09:16 ip-172-31-40-43 web[10998]: Traceback (most recent call last):
May  9 11:09:16 ip-172-31-40-43 web[10998]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/gunicorn/workers/gthread.py", line 282, in handle
May  9 11:09:16 ip-172-31-40-43 web[10998]:    keepalive = self.handle_request(req, conn)
May  9 11:09:16 ip-172-31-40-43 web[10998]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/gunicorn/workers/gthread.py", line 354, in handle_request
May  9 11:09:16 ip-172-31-40-43 web[10998]:    util.reraise(*sys.exc_info())
May  9 11:09:16 ip-172-31-40-43 web[10998]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/gunicorn/util.py", line 641, in reraise
May  9 11:09:16 ip-172-31-40-43 web[10998]:    raise value
May  9 11:09:16 ip-172-31-40-43 web[10998]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/gunicorn/workers/gthread.py", line 334, in handle_request
May  9 11:09:16 ip-172-31-40-43 web[10998]:    respiter = self.wsgi(environ, resp.start_response)
May  9 11:09:16 ip-172-31-40-43 web[10998]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/flask/app.py", line 1498, in __call__
May  9 11:09:16 ip-172-31-40-43 web[10998]:    return self.wsgi_app(environ, start_response)
May  9 11:09:16 ip-172-31-40-43 web[10998]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/flask/app.py", line 1476, in wsgi_app
May  9 11:09:16 ip-172-31-40-43 web[10998]:    response = self.handle_exception(e)
May  9 11:09:16 ip-172-31-40-43 web[10998]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/flask/app.py", line 1473, in wsgi_app
May  9 11:09:16 ip-172-31-40-43 web[10998]:    response = self.full_dispatch_request()
May  9 11:09:16 ip-172-31-40-43 web[10998]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/flask/app.py", line 882, in full_dispatch_request
May  9 11:09:16 ip-172-31-40-43 web[10998]:    rv = self.handle_user_exception(e)
May  9 11:09:16 ip-172-31-40-43 web[10998]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/flask/app.py", line 880, in full_dispatch_request
May  9 11:09:16 ip-172-31-40-43 web[10998]:    rv = self.dispatch_request()
May  9 11:09:16 ip-172-31-40-43 web[10998]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/flask/app.py", line 865, in dispatch_request
May  9 11:09:16 ip-172-31-40-43 web[10998]:    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
May  9 11:09:16 ip-172-31-40-43 web[10998]:  File "/var/app/current/Program/routes.py", line 63, in index
May  9 11:09:16 ip-172-31-40-43 web[10998]:    return render_template('error.html', error=str(e))
May  9 11:09:16 ip-172-31-40-43 web[10998]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/flask/templating.py", line 149, in render_template
May  9 11:09:16 ip-172-31-40-43 web[10998]:    template = app.jinja_env.get_or_select_template(template_name_or_list)
May  9 11:09:16 ip-172-31-40-43 web[10998]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/jinja2/environment.py", line 1081, in get_or_select_template
May  9 11:09:16 ip-172-31-40-43 web[10998]:    return self.get_template(template_name_or_list, parent, globals)
May  9 11:09:16 ip-172-31-40-43 web[10998]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/jinja2/environment.py", line 1010, in get_template
May  9 11:09:16 ip-172-31-40-43 web[10998]:    return self._load_template(name, globals)
May  9 11:09:16 ip-172-31-40-43 web[10998]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/jinja2/environment.py", line 969, in _load_template
May  9 11:09:16 ip-172-31-40-43 web[10998]:    template = self.loader.load(self, name, self.make_globals(globals))
May  9 11:09:16 ip-172-31-40-43 web[10998]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/jinja2/loaders.py", line 125, in load
May  9 11:09:16 ip-172-31-40-43 web[10998]:    source, filename, uptodate = self.get_source(environment, name)
May  9 11:09:16 ip-172-31-40-43 web[10998]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/flask/templating.py", line 65, in get_source
May  9 11:09:16 ip-172-31-40-43 web[10998]:    return self._get_source_fast(environment, template)
May  9 11:09:16 ip-172-31-40-43 web[10998]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/flask/templating.py", line 99, in _get_source_fast
May  9 11:09:16 ip-172-31-40-43 web[10998]:    raise TemplateNotFound(template)
May  9 11:09:16 ip-172-31-40-43 web[10998]: jinja2.exceptions.TemplateNotFound: error.html
May  9 11:15:51 ip-172-31-40-43 web[10990]: [2024-05-09 11:15:51 +0000] [10990] [INFO] Handling signal: term
May  9 11:15:51 ip-172-31-40-43 web[10998]: [2024-05-09 11:15:51 +0000] [10998] [INFO] Worker exiting (pid: 10998)
May  9 11:15:51 ip-172-31-40-43 web[10998]: Program package initialized!
May  9 11:15:51 ip-172-31-40-43 web[10998]: {'TableNames': ['Clients', 'login', 'music'], 'ResponseMetadata': {'RequestId': '9NORGJDKPMCBC208EUJ7T2N2IFVV4KQNSO5AEMVJF66Q9ASUAAJG', 'HTTPStatusCode': 200, 'HTTPHeaders': {'server': 'Server', 'date': 'Thu, 09 May 2024 11:08:59 GMT', 'content-type': 'application/x-amz-json-1.0', 'content-length': '42', 'connection': 'keep-alive', 'x-amzn-requestid': '9NORGJDKPMCBC208EUJ7T2N2IFVV4KQNSO5AEMVJF66Q9ASUAAJG', 'x-amz-crc32': '1807579339'}, 'RetryAttempts': 0}}
May  9 11:15:51 ip-172-31-40-43 web[10998]: Error: Could not build url for endpoint 'place_order'. Did you mean 'main.register' instead?
May  9 11:15:52 ip-172-31-40-43 web[10990]: [2024-05-09 11:15:52 +0000] [10990] [INFO] Shutting down: Master
May  9 11:15:53 ip-172-31-40-43 web[11677]: [2024-05-09 11:15:53 +0000] [11677] [INFO] Starting gunicorn 22.0.0
May  9 11:15:53 ip-172-31-40-43 web[11677]: [2024-05-09 11:15:53 +0000] [11677] [INFO] Listening at: http://127.0.0.1:8000 (11677)
May  9 11:15:53 ip-172-31-40-43 web[11677]: [2024-05-09 11:15:53 +0000] [11677] [INFO] Using worker: gthread
May  9 11:15:53 ip-172-31-40-43 web[11706]: [2024-05-09 11:15:53 +0000] [11706] [INFO] Booting worker with pid: 11706
May  9 11:17:05 ip-172-31-40-43 web[11706]: [2024-05-09 11:17:05 +0000] [11706] [ERROR] Socket error processing request.
May  9 11:17:05 ip-172-31-40-43 web[11706]: Traceback (most recent call last):
May  9 11:17:05 ip-172-31-40-43 web[11706]:  File "/var/app/current/Program/routes.py", line 58, in index
May  9 11:17:05 ip-172-31-40-43 web[11706]:    return render_template('index.html', user_data=user_data, products=products)
May  9 11:17:05 ip-172-31-40-43 web[11706]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/flask/templating.py", line 150, in render_template
May  9 11:17:05 ip-172-31-40-43 web[11706]:    return _render(app, template, context)
May  9 11:17:05 ip-172-31-40-43 web[11706]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/flask/templating.py", line 131, in _render
May  9 11:17:05 ip-172-31-40-43 web[11706]:    rv = template.render(context)
May  9 11:17:05 ip-172-31-40-43 web[11706]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/jinja2/environment.py", line 1301, in render
May  9 11:17:05 ip-172-31-40-43 web[11706]:    self.environment.handle_exception()
May  9 11:17:05 ip-172-31-40-43 web[11706]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/jinja2/environment.py", line 936, in handle_exception
May  9 11:17:05 ip-172-31-40-43 web[11706]:    raise rewrite_traceback_stack(source=source)
May  9 11:17:05 ip-172-31-40-43 web[11706]:  File "/var/app/current/Program/templates/index.html", line 27, in top-level template code
May  9 11:17:05 ip-172-31-40-43 web[11706]:    <button onclick="location.href='{{ url_for('place_order') }}'">Order</button>
May  9 11:17:05 ip-172-31-40-43 web[11706]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/flask/app.py", line 1084, in url_for
May  9 11:17:05 ip-172-31-40-43 web[11706]:    return self.handle_url_build_error(error, endpoint, values)
May  9 11:17:05 ip-172-31-40-43 web[11706]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/flask/app.py", line 1073, in url_for
May  9 11:17:05 ip-172-31-40-43 web[11706]:    rv = url_adapter.build(  # type: ignore[union-attr]
May  9 11:17:05 ip-172-31-40-43 web[11706]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/werkzeug/routing/map.py", line 926, in build
May  9 11:17:05 ip-172-31-40-43 web[11706]:    raise BuildError(endpoint, values, method, self)
May  9 11:17:05 ip-172-31-40-43 web[11706]: werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'place_order'. Did you mean 'main.place_order' instead?
May  9 11:17:05 ip-172-31-40-43 web[11706]: During handling of the above exception, another exception occurred:
May  9 11:17:05 ip-172-31-40-43 web[11706]: Traceback (most recent call last):
May  9 11:17:05 ip-172-31-40-43 web[11706]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/gunicorn/workers/gthread.py", line 282, in handle
May  9 11:17:05 ip-172-31-40-43 web[11706]:    keepalive = self.handle_request(req, conn)
May  9 11:17:05 ip-172-31-40-43 web[11706]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/gunicorn/workers/gthread.py", line 354, in handle_request
May  9 11:17:05 ip-172-31-40-43 web[11706]:    util.reraise(*sys.exc_info())
May  9 11:17:05 ip-172-31-40-43 web[11706]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/gunicorn/util.py", line 641, in reraise
May  9 11:17:05 ip-172-31-40-43 web[11706]:    raise value
May  9 11:17:05 ip-172-31-40-43 web[11706]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/gunicorn/workers/gthread.py", line 334, in handle_request
May  9 11:17:05 ip-172-31-40-43 web[11706]:    respiter = self.wsgi(environ, resp.start_response)
May  9 11:17:05 ip-172-31-40-43 web[11706]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/flask/app.py", line 1498, in __call__
May  9 11:17:05 ip-172-31-40-43 web[11706]:    return self.wsgi_app(environ, start_response)
May  9 11:17:05 ip-172-31-40-43 web[11706]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/flask/app.py", line 1476, in wsgi_app
May  9 11:17:05 ip-172-31-40-43 web[11706]:    response = self.handle_exception(e)
May  9 11:17:05 ip-172-31-40-43 web[11706]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/flask/app.py", line 1473, in wsgi_app
May  9 11:17:05 ip-172-31-40-43 web[11706]:    response = self.full_dispatch_request()
May  9 11:17:05 ip-172-31-40-43 web[11706]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/flask/app.py", line 882, in full_dispatch_request
May  9 11:17:05 ip-172-31-40-43 web[11706]:    rv = self.handle_user_exception(e)
May  9 11:17:05 ip-172-31-40-43 web[11706]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/flask/app.py", line 880, in full_dispatch_request
May  9 11:17:05 ip-172-31-40-43 web[11706]:    rv = self.dispatch_request()
May  9 11:17:05 ip-172-31-40-43 web[11706]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/flask/app.py", line 865, in dispatch_request
May  9 11:17:05 ip-172-31-40-43 web[11706]:    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
May  9 11:17:05 ip-172-31-40-43 web[11706]:  File "/var/app/current/Program/routes.py", line 63, in index
May  9 11:17:05 ip-172-31-40-43 web[11706]:    return render_template('error.html', error=str(e))
May  9 11:17:05 ip-172-31-40-43 web[11706]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/flask/templating.py", line 149, in render_template
May  9 11:17:05 ip-172-31-40-43 web[11706]:    template = app.jinja_env.get_or_select_template(template_name_or_list)
May  9 11:17:05 ip-172-31-40-43 web[11706]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/jinja2/environment.py", line 1081, in get_or_select_template
May  9 11:17:05 ip-172-31-40-43 web[11706]:    return self.get_template(template_name_or_list, parent, globals)
May  9 11:17:05 ip-172-31-40-43 web[11706]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/jinja2/environment.py", line 1010, in get_template
May  9 11:17:05 ip-172-31-40-43 web[11706]:    return self._load_template(name, globals)
May  9 11:17:05 ip-172-31-40-43 web[11706]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/jinja2/environment.py", line 969, in _load_template
May  9 11:17:05 ip-172-31-40-43 web[11706]:    template = self.loader.load(self, name, self.make_globals(globals))
May  9 11:17:05 ip-172-31-40-43 web[11706]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/jinja2/loaders.py", line 125, in load
May  9 11:17:05 ip-172-31-40-43 web[11706]:    source, filename, uptodate = self.get_source(environment, name)
May  9 11:17:05 ip-172-31-40-43 web[11706]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/flask/templating.py", line 65, in get_source
May  9 11:17:05 ip-172-31-40-43 web[11706]:    return self._get_source_fast(environment, template)
May  9 11:17:05 ip-172-31-40-43 web[11706]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/flask/templating.py", line 99, in _get_source_fast
May  9 11:17:05 ip-172-31-40-43 web[11706]:    raise TemplateNotFound(template)
May  9 11:17:05 ip-172-31-40-43 web[11706]: jinja2.exceptions.TemplateNotFound: error.html
May  9 11:18:44 ip-172-31-40-43 web[11677]: [2024-05-09 11:18:44 +0000] [11677] [INFO] Handling signal: term
May  9 11:18:45 ip-172-31-40-43 web[11706]: [2024-05-09 11:18:45 +0000] [11706] [INFO] Worker exiting (pid: 11706)
May  9 11:18:45 ip-172-31-40-43 web[11706]: Program package initialized!
May  9 11:18:45 ip-172-31-40-43 web[11706]: {'TableNames': ['Clients', 'login', 'music'], 'ResponseMetadata': {'RequestId': 'CJFANF23MMU687I7COQ7S7BD47VV4KQNSO5AEMVJF66Q9ASUAAJG', 'HTTPStatusCode': 200, 'HTTPHeaders': {'server': 'Server', 'date': 'Thu, 09 May 2024 11:15:54 GMT', 'content-type': 'application/x-amz-json-1.0', 'content-length': '42', 'connection': 'keep-alive', 'x-amzn-requestid': 'CJFANF23MMU687I7COQ7S7BD47VV4KQNSO5AEMVJF66Q9ASUAAJG', 'x-amz-crc32': '1807579339'}, 'RetryAttempts': 0}}
May  9 11:18:45 ip-172-31-40-43 web[11706]: Form validated successfully
May  9 11:18:45 ip-172-31-40-43 web[11706]: Error: Could not build url for endpoint 'place_order'. Did you mean 'main.place_order' instead?
May  9 11:18:45 ip-172-31-40-43 web[11677]: [2024-05-09 11:18:45 +0000] [11677] [INFO] Shutting down: Master
May  9 11:18:47 ip-172-31-40-43 web[12238]: [2024-05-09 11:18:47 +0000] [12238] [INFO] Starting gunicorn 22.0.0
May  9 11:18:47 ip-172-31-40-43 web[12238]: [2024-05-09 11:18:47 +0000] [12238] [INFO] Listening at: http://127.0.0.1:8000 (12238)
May  9 11:18:47 ip-172-31-40-43 web[12238]: [2024-05-09 11:18:47 +0000] [12238] [INFO] Using worker: gthread
May  9 11:18:47 ip-172-31-40-43 web[12269]: [2024-05-09 11:18:47 +0000] [12269] [INFO] Booting worker with pid: 12269
May  9 11:20:09 ip-172-31-40-43 web[12269]: [2024-05-09 11:20:09 +0000] [12269] [ERROR] Socket error processing request.
May  9 11:20:09 ip-172-31-40-43 web[12269]: Traceback (most recent call last):
May  9 11:20:09 ip-172-31-40-43 web[12269]:  File "/var/app/current/Program/routes.py", line 58, in index
May  9 11:20:09 ip-172-31-40-43 web[12269]:    return render_template('index.html', user_data=user_data, products=products)
May  9 11:20:09 ip-172-31-40-43 web[12269]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/flask/templating.py", line 150, in render_template
May  9 11:20:09 ip-172-31-40-43 web[12269]:    return _render(app, template, context)
May  9 11:20:09 ip-172-31-40-43 web[12269]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/flask/templating.py", line 131, in _render
May  9 11:20:09 ip-172-31-40-43 web[12269]:    rv = template.render(context)
May  9 11:20:09 ip-172-31-40-43 web[12269]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/jinja2/environment.py", line 1301, in render
May  9 11:20:09 ip-172-31-40-43 web[12269]:    self.environment.handle_exception()
May  9 11:20:09 ip-172-31-40-43 web[12269]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/jinja2/environment.py", line 936, in handle_exception
May  9 11:20:09 ip-172-31-40-43 web[12269]:    raise rewrite_traceback_stack(source=source)
May  9 11:20:09 ip-172-31-40-43 web[12269]:  File "/var/app/current/Program/templates/index.html", line 27, in top-level template code
May  9 11:20:09 ip-172-31-40-43 web[12269]:    <button onclick="location.href='{{ url_for('place_order') }}'">Order</button>
May  9 11:20:09 ip-172-31-40-43 web[12269]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/flask/app.py", line 1084, in url_for
May  9 11:20:09 ip-172-31-40-43 web[12269]:    return self.handle_url_build_error(error, endpoint, values)
May  9 11:20:09 ip-172-31-40-43 web[12269]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/flask/app.py", line 1073, in url_for
May  9 11:20:09 ip-172-31-40-43 web[12269]:    rv = url_adapter.build(  # type: ignore[union-attr]
May  9 11:20:09 ip-172-31-40-43 web[12269]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/werkzeug/routing/map.py", line 926, in build
May  9 11:20:09 ip-172-31-40-43 web[12269]:    raise BuildError(endpoint, values, method, self)
May  9 11:20:09 ip-172-31-40-43 web[12269]: werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'place_order'. Did you mean 'main.place_order' instead?
May  9 11:20:09 ip-172-31-40-43 web[12269]: During handling of the above exception, another exception occurred:
May  9 11:20:09 ip-172-31-40-43 web[12269]: Traceback (most recent call last):
May  9 11:20:09 ip-172-31-40-43 web[12269]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/gunicorn/workers/gthread.py", line 282, in handle
May  9 11:20:09 ip-172-31-40-43 web[12269]:    keepalive = self.handle_request(req, conn)
May  9 11:20:09 ip-172-31-40-43 web[12269]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/gunicorn/workers/gthread.py", line 354, in handle_request
May  9 11:20:09 ip-172-31-40-43 web[12269]:    util.reraise(*sys.exc_info())
May  9 11:20:09 ip-172-31-40-43 web[12269]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/gunicorn/util.py", line 641, in reraise
May  9 11:20:09 ip-172-31-40-43 web[12269]:    raise value
May  9 11:20:09 ip-172-31-40-43 web[12269]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/gunicorn/workers/gthread.py", line 334, in handle_request
May  9 11:20:09 ip-172-31-40-43 web[12269]:    respiter = self.wsgi(environ, resp.start_response)
May  9 11:20:09 ip-172-31-40-43 web[12269]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/flask/app.py", line 1498, in __call__
May  9 11:20:09 ip-172-31-40-43 web[12269]:    return self.wsgi_app(environ, start_response)
May  9 11:20:09 ip-172-31-40-43 web[12269]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/flask/app.py", line 1476, in wsgi_app
May  9 11:20:09 ip-172-31-40-43 web[12269]:    response = self.handle_exception(e)
May  9 11:20:09 ip-172-31-40-43 web[12269]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/flask/app.py", line 1473, in wsgi_app
May  9 11:20:09 ip-172-31-40-43 web[12269]:    response = self.full_dispatch_request()
May  9 11:20:09 ip-172-31-40-43 web[12269]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/flask/app.py", line 882, in full_dispatch_request
May  9 11:20:09 ip-172-31-40-43 web[12269]:    rv = self.handle_user_exception(e)
May  9 11:20:09 ip-172-31-40-43 web[12269]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/flask/app.py", line 880, in full_dispatch_request
May  9 11:20:09 ip-172-31-40-43 web[12269]:    rv = self.dispatch_request()
May  9 11:20:09 ip-172-31-40-43 web[12269]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/flask/app.py", line 865, in dispatch_request
May  9 11:20:09 ip-172-31-40-43 web[12269]:    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
May  9 11:20:09 ip-172-31-40-43 web[12269]:  File "/var/app/current/Program/routes.py", line 63, in index
May  9 11:20:09 ip-172-31-40-43 web[12269]:    return render_template('error.html', error=str(e))
May  9 11:20:09 ip-172-31-40-43 web[12269]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/flask/templating.py", line 149, in render_template
May  9 11:20:09 ip-172-31-40-43 web[12269]:    template = app.jinja_env.get_or_select_template(template_name_or_list)
May  9 11:20:09 ip-172-31-40-43 web[12269]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/jinja2/environment.py", line 1081, in get_or_select_template
May  9 11:20:09 ip-172-31-40-43 web[12269]:    return self.get_template(template_name_or_list, parent, globals)
May  9 11:20:09 ip-172-31-40-43 web[12269]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/jinja2/environment.py", line 1010, in get_template
May  9 11:20:09 ip-172-31-40-43 web[12269]:    return self._load_template(name, globals)
May  9 11:20:09 ip-172-31-40-43 web[12269]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/jinja2/environment.py", line 969, in _load_template
May  9 11:20:09 ip-172-31-40-43 web[12269]:    template = self.loader.load(self, name, self.make_globals(globals))
May  9 11:20:09 ip-172-31-40-43 web[12269]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/jinja2/loaders.py", line 125, in load
May  9 11:20:09 ip-172-31-40-43 web[12269]:    source, filename, uptodate = self.get_source(environment, name)
May  9 11:20:09 ip-172-31-40-43 web[12269]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/flask/templating.py", line 65, in get_source
May  9 11:20:09 ip-172-31-40-43 web[12269]:    return self._get_source_fast(environment, template)
May  9 11:20:09 ip-172-31-40-43 web[12269]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/flask/templating.py", line 99, in _get_source_fast
May  9 11:20:09 ip-172-31-40-43 web[12269]:    raise TemplateNotFound(template)
May  9 11:20:09 ip-172-31-40-43 web[12269]: jinja2.exceptions.TemplateNotFound: error.html
May 11 00:21:09 ip-172-31-40-43 web[12269]: [2024-05-11 00:21:09 +0000] [12269] [ERROR] Socket error processing request.
May 11 00:21:09 ip-172-31-40-43 web[12269]: Traceback (most recent call last):
May 11 00:21:09 ip-172-31-40-43 web[12269]:  File "/var/app/current/Program/routes.py", line 58, in index
May 11 00:21:09 ip-172-31-40-43 web[12269]:    return render_template('index.html', user_data=user_data, products=products)
May 11 00:21:09 ip-172-31-40-43 web[12269]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/flask/templating.py", line 150, in render_template
May 11 00:21:09 ip-172-31-40-43 web[12269]:    return _render(app, template, context)
May 11 00:21:09 ip-172-31-40-43 web[12269]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/flask/templating.py", line 131, in _render
May 11 00:21:09 ip-172-31-40-43 web[12269]:    rv = template.render(context)
May 11 00:21:09 ip-172-31-40-43 web[12269]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/jinja2/environment.py", line 1301, in render
May 11 00:21:09 ip-172-31-40-43 web[12269]:    self.environment.handle_exception()
May 11 00:21:09 ip-172-31-40-43 web[12269]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/jinja2/environment.py", line 936, in handle_exception
May 11 00:21:09 ip-172-31-40-43 web[12269]:    raise rewrite_traceback_stack(source=source)
May 11 00:21:09 ip-172-31-40-43 web[12269]:  File "/var/app/current/Program/templates/index.html", line 27, in top-level template code
May 11 00:21:09 ip-172-31-40-43 web[12269]:    <button onclick="location.href='{{ url_for('place_order') }}'">Order</button>
May 11 00:21:09 ip-172-31-40-43 web[12269]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/flask/app.py", line 1084, in url_for
May 11 00:21:09 ip-172-31-40-43 web[12269]:    return self.handle_url_build_error(error, endpoint, values)
May 11 00:21:09 ip-172-31-40-43 web[12269]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/flask/app.py", line 1073, in url_for
May 11 00:21:09 ip-172-31-40-43 web[12269]:    rv = url_adapter.build(  # type: ignore[union-attr]
May 11 00:21:09 ip-172-31-40-43 web[12269]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/werkzeug/routing/map.py", line 926, in build
May 11 00:21:09 ip-172-31-40-43 web[12269]:    raise BuildError(endpoint, values, method, self)
May 11 00:21:09 ip-172-31-40-43 web[12269]: werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'place_order'. Did you mean 'main.place_order' instead?
May 11 00:21:09 ip-172-31-40-43 web[12269]: During handling of the above exception, another exception occurred:
May 11 00:21:09 ip-172-31-40-43 web[12269]: Traceback (most recent call last):
May 11 00:21:09 ip-172-31-40-43 web[12269]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/gunicorn/workers/gthread.py", line 282, in handle
May 11 00:21:09 ip-172-31-40-43 web[12269]:    keepalive = self.handle_request(req, conn)
May 11 00:21:09 ip-172-31-40-43 web[12269]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/gunicorn/workers/gthread.py", line 354, in handle_request
May 11 00:21:09 ip-172-31-40-43 web[12269]:    util.reraise(*sys.exc_info())
May 11 00:21:09 ip-172-31-40-43 web[12269]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/gunicorn/util.py", line 641, in reraise
May 11 00:21:09 ip-172-31-40-43 web[12269]:    raise value
May 11 00:21:09 ip-172-31-40-43 web[12269]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/gunicorn/workers/gthread.py", line 334, in handle_request
May 11 00:21:09 ip-172-31-40-43 web[12269]:    respiter = self.wsgi(environ, resp.start_response)
May 11 00:21:09 ip-172-31-40-43 web[12269]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/flask/app.py", line 1498, in __call__
May 11 00:21:09 ip-172-31-40-43 web[12269]:    return self.wsgi_app(environ, start_response)
May 11 00:21:09 ip-172-31-40-43 web[12269]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/flask/app.py", line 1476, in wsgi_app
May 11 00:21:09 ip-172-31-40-43 web[12269]:    response = self.handle_exception(e)
May 11 00:21:09 ip-172-31-40-43 web[12269]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/flask/app.py", line 1473, in wsgi_app
May 11 00:21:09 ip-172-31-40-43 web[12269]:    response = self.full_dispatch_request()
May 11 00:21:09 ip-172-31-40-43 web[12269]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/flask/app.py", line 882, in full_dispatch_request
May 11 00:21:09 ip-172-31-40-43 web[12269]:    rv = self.handle_user_exception(e)
May 11 00:21:09 ip-172-31-40-43 web[12269]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/flask/app.py", line 880, in full_dispatch_request
May 11 00:21:09 ip-172-31-40-43 web[12269]:    rv = self.dispatch_request()
May 11 00:21:09 ip-172-31-40-43 web[12269]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/flask/app.py", line 865, in dispatch_request
May 11 00:21:09 ip-172-31-40-43 web[12269]:    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
May 11 00:21:09 ip-172-31-40-43 web[12269]:  File "/var/app/current/Program/routes.py", line 63, in index
May 11 00:21:09 ip-172-31-40-43 web[12269]:    return render_template('error.html', error=str(e))
May 11 00:21:09 ip-172-31-40-43 web[12269]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/flask/templating.py", line 149, in render_template
May 11 00:21:09 ip-172-31-40-43 web[12269]:    template = app.jinja_env.get_or_select_template(template_name_or_list)
May 11 00:21:09 ip-172-31-40-43 web[12269]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/jinja2/environment.py", line 1081, in get_or_select_template
May 11 00:21:09 ip-172-31-40-43 web[12269]:    return self.get_template(template_name_or_list, parent, globals)
May 11 00:21:09 ip-172-31-40-43 web[12269]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/jinja2/environment.py", line 1010, in get_template
May 11 00:21:09 ip-172-31-40-43 web[12269]:    return self._load_template(name, globals)
May 11 00:21:09 ip-172-31-40-43 web[12269]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/jinja2/environment.py", line 969, in _load_template
May 11 00:21:09 ip-172-31-40-43 web[12269]:    template = self.loader.load(self, name, self.make_globals(globals))
May 11 00:21:09 ip-172-31-40-43 web[12269]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/jinja2/loaders.py", line 125, in load
May 11 00:21:09 ip-172-31-40-43 web[12269]:    source, filename, uptodate = self.get_source(environment, name)
May 11 00:21:09 ip-172-31-40-43 web[12269]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/flask/templating.py", line 65, in get_source
May 11 00:21:09 ip-172-31-40-43 web[12269]:    return self._get_source_fast(environment, template)
May 11 00:21:09 ip-172-31-40-43 web[12269]:  File "/var/app/venv/staging-LQM1lest/lib64/python3.9/site-packages/flask/templating.py", line 99, in _get_source_fast
May 11 00:21:09 ip-172-31-40-43 web[12269]:    raise TemplateNotFound(template)
May 11 00:21:09 ip-172-31-40-43 web[12269]: jinja2.exceptions.TemplateNotFound: error.html
